BPER/DEVF/force-app/main/default/objects/RoleMDS__c/RoleMDS__c.object-meta.xml
<CustomObject>
    <label>MDS per Ruolo</label>
    <nameField>
        <encryptionScheme>None</encryptionScheme>
        <label>MDS per Ruolo Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>MDS per Ruoli</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

BPER/DEVF/force-app/main/default/objects/RoleMDS__c/fields/PTF_BranchTypology__c.field-meta.xml
<CustomField>
    <fullName>PTF_BranchTypology__c</fullName>
    <label>Tipologia di filiale</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetName>BranchTypology</valueSetName>
    </valueSet>
</CustomField>

BPER/DEVF/force-app/main/default/objects/RoleMDS__c/fields/PTF_EndDate__c.field-meta.xml
<CustomField>
    <fullName>PTF_EndDate__c</fullName>
    <encryptionScheme>None</encryptionScheme>
    <label>Data fine</label>
    <type>Date</type>
</CustomField>

BPER/DEVF/force-app/main/default/objects/RoleMDS__c/fields/PTF_RoleTypology__c.field-meta.xml
<CustomField>
    <fullName>PTF_RoleTypology__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Tipologia di Ruolo</label>
    <referenceTo>RoleTypology__c</referenceTo>
    <relationshipLabel>MDS per Ruoli</relationshipLabel>
    <relationshipName>MDS_per_Ruoli</relationshipName>
    <type>Lookup</type>
</CustomField>

BPER/DEVF/force-app/main/default/objects/RoleMDS__c/fields/PTF_ServiceModel__c.field-meta.xml
<CustomField>
    <fullName>PTF_ServiceModel__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Macro-modello di servizio</label>
    <referenceTo>ServiceModel__c</referenceTo>
    <relationshipLabel>MDS per Ruoli</relationshipLabel>
    <relationshipName>MDS_per_Ruoli</relationshipName>
    <type>Lookup</type>
</CustomField>

BPER/DEVF/force-app/main/default/objects/RoleMDS__c/fields/PTF_StartDate__c.field-meta.xml
<CustomField>
    <fullName>PTF_StartDate__c</fullName>
    <encryptionScheme>None</encryptionScheme>
    <label>Data inizio</label>
    <type>Date</type>
</CustomField>

BPER/DEVF/force-app/main/default/objects/RoleTypology__c/RoleTypology__c.object-meta.xml
<CustomObject>
    <label>Tipologia Ruolo</label>
    <nameField>
        <encryptionScheme>None</encryptionScheme>
        <label>Nome Ruolo</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Tipologia Ruoli</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

BPER/DEVF/force-app/main/default/objects/ServiceModel__c/ServiceModel__c.object-meta.xml
<CustomObject>
    <label>Macro-modello di servizio</label>
    <nameField>
        <encryptionScheme>None</encryptionScheme>
        <label>Nome modello di servizio</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Macro-modelli di servizio</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

BPER/DEVF/force-app/main/default/objects/UtenzeDefault__c/UtenzeDefault__c.object-meta.xml
<CustomObject>
    <customSettingsType>Hierarchy</customSettingsType>
    <label>Utenze default</label>
</CustomObject>

BPER/DEVF/force-app/main/default/objects/UtenzeDefault__c/fields/PTF_POOL_IdOwner__c.field-meta.xml
<CustomField>
    <fullName>PTF_POOL_IdOwner__c</fullName>
    <description>In fase di creazione di un Microportafoglio in Pool, l&apos;ownership del record, nel caso di assegnazione di referenti.</description>
    <encryptionScheme>None</encryptionScheme>
    <label>PTF POOL Id Owner</label>
    <length>18</length>
    <type>Text</type>
</CustomField>

BPER/DEVF/force-app/main/default/objects/Wallet__c/Wallet__c.object-meta.xml
<CustomObject>
    <label>Portafoglio</label>
    <nameField>
        <encryptionScheme>None</encryptionScheme>
        <label>Wallet Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Portafogli</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

BPER/DEVF/force-app/main/default/objects/Wallet__c/fields/PTF_BranchTypology__c.field-meta.xml
<CustomField>
    <fullName>PTF_BranchTypology__c</fullName>
    <formula>TEXT(PTF_Filiale__r.PTF_BranchTypology__c)</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>BranchTypology</label>
    <type>Text</type>
</CustomField>

BPER/DEVF/force-app/main/default/objects/Wallet__c/fields/PTF_Pool__c.field-meta.xml
<CustomField>
    <fullName>PTF_Pool__c</fullName>
    <defaultValue>false</defaultValue>
    <label>Pool</label>
    <type>Checkbox</type>
</CustomField>

BPER/DEVF/force-app/main/default/objects/Wallet__c/recordTypes/Assente.recordType-meta.xml
<RecordType>
    <fullName>Assente</fullName>
    <active>true</active>
    <label>Assente</label>
</RecordType>

BPER/DEVF/force-app/main/default/objects/Wallet__c/recordTypes/MicroWallet.recordType-meta.xml
<RecordType>
    <fullName>MicroWallet</fullName>
    <active>true</active>
    <label>Microportafoglio</label>
</RecordType>

BPER/DEVF/force-app/main/default/objects/Wallet__c/recordTypes/Residuale.recordType-meta.xml
<RecordType>
    <fullName>Residuale</fullName>
    <active>true</active>
    <label>Residuale</label>
</RecordType>

BPER/DEVF/force-app/main/default/objects/Wallet__c/recordTypes/TechnicalWallet.recordType-meta.xml
<RecordType>
    <fullName>TechnicalWallet</fullName>
    <active>true</active>
    <label>Portafoglio Tecnico</label>
</RecordType>

BPER/POLOWEALTH/force-app/main/default/classes/OnWalletTriggerHandlerTest.cls
/*
/**
 * @task              : test BPER_TOM_AssegnazioneAutomatica 
 * @author            : alessandro di nardo @ten
 * @group             : tengroup
 * @last modified on  : 2023-12-12
 * @class to test     : OnWalletTriggerHandler
 * @description       : copecreazione oggetto assegnazione per i portafogli          
                        asseconda del modello del portafoglio( poe,FAMILY,Controparti Istituzionali)
                        e asseconda della tipologia di ruolo dei contatti associati alla filiale

*/
@IsTest
public with sharing class OnWalletTriggerHandlerTest {

    @TestSetup
    static void setup(){
        
        /*UtenzeDefault__c utenzaDefault = new UtenzeDefault__c();
        utenzaDefault.Name = 'Test';
        utenzaDefault.PTF_POOL_IdOwner__c = UserInfo.getUserId();
        insert utenzaDefault;*/

        RoleTypology__c ruolo = new RoleTypology__c();
        ruolo.Name = 'Titolare';
        insert ruolo;

        ServiceModel__c modelloDiServizio = new ServiceModel__c();
        modelloDiServizio.Name = 'Family';
        ServiceModel__c modelloDiServizio2 = new ServiceModel__c();
        modelloDiServizio2.Name = 'Controparti Istituzionali';

        insert new List<ServiceModel__c>{modelloDiServizio, modelloDiServizio2};

        RoleMDS__c ruoloMDS = new RoleMDS__c();
        ruoloMDS.PTF_BranchTypology__c = 'A';
        ruoloMDS.PTF_RoleTypology__c = ruolo.Id;
        ruoloMDS.PTF_ServiceModel__c = modelloDiServizio.Id;
        ruoloMDS.PTF_StartDate__c = Date.today().addDays(-10);
        ruoloMDS.PTF_EndDate__c = Date.today().addDays(10);
        RoleMDS__c ruoloMDS2 = new RoleMDS__c();
        ruoloMDS2.PTF_BranchTypology__c = 'A';
        ruoloMDS2.PTF_RoleTypology__c = ruolo.Id;
        ruoloMDS2.PTF_ServiceModel__c = modelloDiServizio2.Id;
        ruoloMDS2.PTF_StartDate__c = Date.today().addDays(-10);
        ruoloMDS2.PTF_EndDate__c = Date.today().addDays(10);

        insert new List<RoleMDS__c>{ruoloMDS, ruoloMDS2};

        
        Account filiale = AllDataFactory.getAccount('04', 'FilialeDiRelazione');
        filiale.PTF_BranchTypology__c = 'A';
        insert filiale;
        
        Profile profile = [SELECT id FROM Profile WHERE Name =: Label.System_Administrator LIMIT 1];
        User user = AllDataFactory.getUser('01', profile.Id, 'Family');
        insert user;
        List<Contact> listContact = new List<Contact>();//AD
        System.runAs(user){
            Contact contact = AllDataFactory.getContact('01', user.Id, filiale.Id);
            contact.PTF_TipologiaRuolo__c = ruolo.Id;
            //contact.PTF_ProfiloLDAP__c = 'test';AD
            insert contact; 

        }
        
    }
    
    @IsTest
    static void testInsert(){
        
        Account filiale = [SELECT id FROM Account LIMIT 1];

        Wallet__c microPortafoglio = AllDataFactory.getWallet('MicroWallet', filiale.Id, 'Controparti Istituzionali');
        microPortafoglio.PTF_Pool__c=true;
        microPortafoglio.Name='Test1';
        Wallet__c microPortafoglio2 = AllDataFactory.getWallet('MicroWallet', filiale.Id, 'Family');
        microPortafoglio2.Name='Test2';
        Wallet__c portafoglioTecnico = AllDataFactory.getWallet('TechnicalWallet', filiale.Id, 'Family');
        portafoglioTecnico.Name='Test3';
        Wallet__c portafoglioAssente = AllDataFactory.getWallet('Assente', filiale.Id, 'Assente');
        portafoglioTecnico.Name='Test4';
        Wallet__c portafoglioResiduale = AllDataFactory.getWallet('Residuale', filiale.Id, 'Residuale');
        portafoglioResiduale.Name='Test5';
        insert new List<Wallet__c>{microPortafoglio, microPortafoglio2, portafoglioTecnico, portafoglioAssente, portafoglioResiduale};
        
        try{

            delete new List<Wallet__c>{microPortafoglio, portafoglioTecnico, portafoglioAssente, portafoglioResiduale};
        }catch(Exception ex){}
    }    


    
    //AD
    @isTest
    static void testAssegnazioneWallet(){
        RoleTypology__c ruolo = new RoleTypology__c();
        ruolo.Name = 'Titolare';
        insert ruolo;

        ServiceModel__c modelloDiServizio = new ServiceModel__c();
        modelloDiServizio.Name = 'Family';
        ServiceModel__c modelloDiServizio2 = new ServiceModel__c();
        modelloDiServizio2.Name = 'Controparti Istituzionali';

        insert new List<ServiceModel__c>{modelloDiServizio, modelloDiServizio2};

        RoleMDS__c ruoloMDS = new RoleMDS__c();
        ruoloMDS.PTF_BranchTypology__c = 'A';
        ruoloMDS.PTF_RoleTypology__c = ruolo.Id;
        ruoloMDS.PTF_ServiceModel__c = modelloDiServizio.Id;
        ruoloMDS.PTF_StartDate__c = Date.today().addDays(-10);
        ruoloMDS.PTF_EndDate__c = Date.today().addDays(10);
        RoleMDS__c ruoloMDS2 = new RoleMDS__c();
        ruoloMDS2.PTF_BranchTypology__c = 'A';
        ruoloMDS2.PTF_RoleTypology__c = ruolo.Id;
        ruoloMDS2.PTF_ServiceModel__c = modelloDiServizio2.Id;
        ruoloMDS2.PTF_StartDate__c = Date.today().addDays(-10);
        ruoloMDS2.PTF_EndDate__c = Date.today().addDays(10);

        insert new List<RoleMDS__c>{ruoloMDS, ruoloMDS2};

        
        Account filiale = AllDataFactory.getAccount('05', 'FilialeDiRelazione');
        filiale.PTF_BranchTypology__c = 'A';
        insert filiale;
        
        Profile profile = [SELECT id FROM Profile WHERE Name =: Label.System_Administrator LIMIT 1];
        User user = AllDataFactory.getUser('02', profile.Id, 'Family');
        insert user;
        List<Contact> listContact = new List<Contact>();//AD
        System.runAs(user){
            Contact contact = AllDataFactory.getContact('02', user.Id, filiale.Id);
            contact.PTF_TipologiaRuolo__c = ruolo.Id;
            contact.PTF_ProfiloLDAP__c = 'test';
            insert contact; 

        }


        Account filiale2 = [SELECT id FROM Account where Name = 'Account05'];

        Wallet__c microPortafoglio = AllDataFactory.getWallet('MicroWallet', filiale2.Id, 'Controparti Istituzionali');
        microPortafoglio.PTF_Pool__c=true;
        microPortafoglio.Name='Test1';
        Wallet__c microPortafoglio2 = AllDataFactory.getWallet('MicroWallet', filiale2.Id, 'Family');
        microPortafoglio2.Name='Test2';
        Wallet__c portafoglioTecnico = AllDataFactory.getWallet('TechnicalWallet', filiale2.Id, 'Family');
        portafoglioTecnico.Name='Test3';
        Wallet__c portafoglioAssente = AllDataFactory.getWallet('Assente', filiale2.Id, 'Assente');
        portafoglioTecnico.Name='Test4';
        Wallet__c portafoglioResiduale = AllDataFactory.getWallet('Residuale', filiale2.Id, 'Residuale');
        portafoglioResiduale.Name='Test5';
        insert new List<Wallet__c>{microPortafoglio, microPortafoglio2, portafoglioTecnico, portafoglioAssente, portafoglioResiduale};
    }
    
}