BPER/DEVF/force-app/main/default/objects/MiniWallet__c/MiniWallet__c.object-meta.xml
<CustomObject>
    <label>MiniWallet</label>
    <nameField>
        <encryptionScheme>None</encryptionScheme>
        <label>MiniWallet Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>MiniWallets</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

BPER/DEVF/force-app/main/default/objects/MiniWallet__c/fields/PTF_Area__c.field-meta.xml
<CustomField>
    <fullName>PTF_Area__c</fullName>
    <formula>HYPERLINK(&quot;/&quot; &amp; PTF_Portafoglio__r.PTF_Area__c, PTF_Portafoglio__r.PTF_Area__r.Name,&apos;_self&apos;)</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>Area</label>
    <type>Text</type>
</CustomField>

BPER/DEVF/force-app/main/default/objects/MiniWallet__c/fields/PTF_Banca__c.field-meta.xml
<CustomField>
    <fullName>PTF_Banca__c</fullName>
    <formula>HYPERLINK(&quot;/&quot; &amp; PTF_Portafoglio__r.PTF_Banca__c, PTF_Portafoglio__r.PTF_Banca__r.Name ,&apos;_self&apos;)</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>Banca</label>
    <type>Text</type>
</CustomField>

BPER/DEVF/force-app/main/default/objects/MiniWallet__c/fields/PTF_Capofila__c.field-meta.xml
<CustomField>
    <fullName>PTF_Capofila__c</fullName>
    <formula>HYPERLINK(&quot;/&quot; &amp; PTF_Portafoglio__r.PTF_Capofila__c, PTF_Portafoglio__r.PTF_Capofila__r.Name ,&apos;_self&apos;)</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>Capofila</label>
    <type>Text</type>
</CustomField>

BPER/DEVF/force-app/main/default/objects/MiniWallet__c/fields/PTF_DirezioneRegionale__c.field-meta.xml
<CustomField>
    <fullName>PTF_DirezioneRegionale__c</fullName>
    <formula>HYPERLINK(&quot;/&quot; &amp; PTF_Portafoglio__r.PTF_DirezioneRegionale__c, PTF_Portafoglio__r.PTF_DirezioneRegionale__r.Name ,&apos;_self&apos;)</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>DR</label>
    <type>Text</type>
</CustomField>

BPER/DEVF/force-app/main/default/objects/MiniWallet__c/fields/PTF_Filiale__c.field-meta.xml
<CustomField>
    <fullName>PTF_Filiale__c</fullName>
    <formula>HYPERLINK(&quot;/&quot; &amp; PTF_Portafoglio__r.PTF_Filiale__c ,PTF_Portafoglio__r.PTF_Filiale__r.Name ,&apos;_self&apos;)</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>Filiale</label>
    <type>Text</type>
</CustomField>

BPER/DEVF/force-app/main/default/objects/MiniWallet__c/fields/PTF_Portafoglio__c.field-meta.xml
<CustomField>
    <fullName>PTF_Portafoglio__c</fullName>
    <label>Portafoglio Padre</label>
    <referenceTo>Wallet__c</referenceTo>
    <relationshipLabel>MiniWallets</relationshipLabel>
    <relationshipName>MiniWallets</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

BPER/DEVF/force-app/main/default/objects/MiniWallet__c/fields/PTF_SL__c.field-meta.xml
<CustomField>
    <fullName>PTF_SL__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Sportello Leggero</label>
    <referenceTo>Account</referenceTo>
    <relationshipLabel>MiniWallets</relationshipLabel>
    <relationshipName>MiniWallets</relationshipName>
    <type>Lookup</type>
</CustomField>

BPER/DEVF/force-app/main/default/objects/MiniWallet__c/fields/Referente__c.field-meta.xml
<CustomField>
    <fullName>Referente__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Referente Principale</label>
    <referenceTo>Contact</referenceTo>
    <relationshipLabel>MiniWallets</relationshipLabel>
    <relationshipName>MiniWallets</relationshipName>
    <type>Lookup</type>
</CustomField>

BPER/PROD/force-app/main/default/classes/miniWalletAccountController.cls
public with sharing class miniWalletAccountController {
    @AuraEnabled
    public static List<MiniWallet__c> getAllData(String recordId){
        
        return [SELECT Id, Name, PTF_Portafoglio__c, Referente__c,Referente__r.name, PTF_Filiale__c, PTF_Capofila__c, PTF_Area__c, PTF_DirezioneRegionale__c, PTF_Banca__c, PTF_SL__c, PTF_SL__r.Name 
                       FROM MiniWallet__c 
                       WHERE PTF_Portafoglio__c=:recordId];
    }
    @AuraEnabled
    public static List<AggregateResult> getNumNDG(String recordId){
        
        return [SELECT count(id) numMiniWallet,PTF_MiniPortafoglio__c
                FROM Account
                WHERE PTF_MiniPortafoglio__c !=null and PTF_Portafoglio__c=:recordId  group by PTF_MiniPortafoglio__c];
    }
    

}