BPER/DEVF/force-app/main/default/objects/Wallet__c/Wallet__c.object-meta.xml
<CustomObject>
    <label>Portafoglio</label>
    <nameField>
        <encryptionScheme>None</encryptionScheme>
        <label>Wallet Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Portafogli</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

BPER/DEVF/force-app/main/default/objects/Wallet__c/fields/PTF_Filiale__c.field-meta.xml
<CustomField>
    <fullName>PTF_Filiale__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Filiale</label>
    <referenceTo>Account</referenceTo>
    <relationshipLabel>Portafogli (Filiale)</relationshipLabel>
    <relationshipName>Filiali</relationshipName>
    <type>Lookup</type>
</CustomField>

BPER/DEVF/force-app/main/default/objects/Wallet__c/fields/PTF_ModelloDiServizio__c.field-meta.xml
<CustomField>
    <fullName>PTF_ModelloDiServizio__c</fullName>
    <label>Macro-modello di servizio</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetName>Modelli_di_Servizio</valueSetName>
    </valueSet>
</CustomField>

BPER/UNBLU/force-app/main/default/classes/Batch_CalcoloReferentiTest.cls
/**
* Controller of multipleAssignement LWC
*
* @author  Dam Kebe @Lutech
* @version 1.0
* @since   2020-07-27
*/
@isTest
public class Batch_CalcoloReferentiTest {
    // @isTest
    // public static void testGetMicroPortafoglio(){

    //     List<Wallet__c> microPortafoglio = [SELECT id, PTF_Filiale__c, PTF_ModelloDiServizio__c FROM Wallet__c LIMIT 1];
    //     Wallet__c retrievedMW = ManageGestoriController.getMicroPortafoglio(microPortafoglio[0].Id);
    //     System.assert(microPortafoglio[0].Id == retrievedMW.Id, 'error');
    // }

   @isTest(SeeAllData=true)
   private static void testExecute(){
       Database.executeBatch(new Batch_CalcoloReferenti(),1000);
   }
}