BPER/DEVF/force-app/main/default/objects/Numeri_Tecnici__mdt/Numeri_Tecnici__mdt.object-meta.xml
<CustomObject>
    <label>Numeri Tecnici</label>
    <pluralLabel>Numeri Tecnici</pluralLabel>
</CustomObject>

BPER/DEVF/force-app/main/default/objects/Numeri_Tecnici__mdt/fields/Valori__c.field-meta.xml
<CustomField>
    <fullName>Valori__c</fullName>
    <label>Valori</label>
    <precision>18</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

BPER/DEVF/force-app/main/default/objects/ScheduledJob__c/ScheduledJob__c.object-meta.xml
<CustomObject>
    <label>ScheduledJob</label>
    <nameField>
        <encryptionScheme>None</encryptionScheme>
        <label>Nome ScheduledJob</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>ScheduledJob</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

BPER/DEVF/force-app/main/default/objects/SV_Log__c/SV_Log__c.object-meta.xml
<CustomObject>
    <label>Log</label>
    <nameField>
        <displayFormat>LOG-{000000}</displayFormat>
        <label>Log Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Logs</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

BPER/UNBLU/force-app/main/default/classes/Batch_DeleteSVLog_Test.cls
@isTest
public class Batch_DeleteSVLog_Test {
    
    @TestSetup
    static void setup(){
        List<SV_Log__c> svlogs = new List<SV_Log__c>();
        for (Integer i=0; i<10; i++) {
        	SV_Log__c svlog = new SV_Log__c();
            svlogs.add(svlog);
        }
        insert svlogs;
        Numeri_Tecnici__mdt nt = (Numeri_Tecnici__mdt)MetadataUtility.getRecordByName('Numeri_Tecnici__mdt', 'DelSVLogMonths');
        Integer months = Integer.valueOf(nt.Valori__c);
        Date today = Date.today();
        today = today.addMonths(-months);
        DateTime dt = DateTime.newInstanceGmt(today.year(),today.month(),1,0,0,0);
        for (SV_Log__c sv : svlogs) {
        	Test.setCreatedDate(sv.Id, dt.addDays(-1));
        }
    }
    @isTest
    static void unitTest() {
        Test.startTest();
        Batch_DeleteSVLog sv = new Batch_DeleteSVLog();
        sv.initRunner(new List<ScheduledJob__c>());
        Database.executeBatch(sv);
        Test.stopTest();
    }
}