BPER/DEVF/force-app/main/default/objects/CRM_LinkedNDG__c/CRM_LinkedNDG__c.object-meta.xml
<CustomObject>
    <label>NDG collegati</label>
    <nameField>
        <displayFormat>NDGCollegati-{0000000000}</displayFormat>
        <label>Nome NDG collegati</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>NDG collegati</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

BPER/DEVF/force-app/main/default/objects/CRM_LinkedNDG__c/fields/CRM_Account__c.field-meta.xml
<CustomField>
    <fullName>CRM_Account__c</fullName>
    <deleteConstraint>Restrict</deleteConstraint>
    <label>Account</label>
    <referenceTo>Account</referenceTo>
    <relationshipLabel>NDG collegati</relationshipLabel>
    <relationshipName>NDG_collegati</relationshipName>
    <required>true</required>
    <type>Lookup</type>
</CustomField>

BPER/DEVF/force-app/main/default/objects/CRM_LinkedNDG__c/fields/CRM_LinkCode__c.field-meta.xml
<CustomField>
    <fullName>CRM_LinkCode__c</fullName>
    <encryptionScheme>None</encryptionScheme>
    <label>Link Code</label>
    <length>255</length>
    <required>true</required>
    <type>Text</type>
</CustomField>

BPER/DEVF/force-app/main/default/objects/CRM_LinkedNDG__c/fields/CRM_RelatedAccount__c.field-meta.xml
<CustomField>
    <fullName>CRM_RelatedAccount__c</fullName>
    <deleteConstraint>Restrict</deleteConstraint>
    <label>Related Account</label>
    <referenceTo>Account</referenceTo>
    <relationshipLabel>NDG collegati (Related Account)</relationshipLabel>
    <relationshipName>CRM_LinkedNDG</relationshipName>
    <required>true</required>
    <type>Lookup</type>
</CustomField>

BPER/DEVF/force-app/main/default/objects/ScheduledJob__c/ScheduledJob__c.object-meta.xml
<CustomObject>
    <label>ScheduledJob</label>
    <nameField>
        <encryptionScheme>None</encryptionScheme>
        <label>Nome ScheduledJob</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>ScheduledJob</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

BPER/DEV/force-app/main/default/classes/Batch_GruppiFinanziari.cls
global class Batch_GruppiFinanziari implements Database.Batchable<sObject>,Database.stateful,IRunner {

    global List<ScheduledJob__c> sj = new List<ScheduledJob__c>();
    
    global void initRunner(List<ScheduledJob__c> schedules) {
        sj.addAll(schedules);
    }
    
    global Database.QueryLocator start(Database.BatchableContext BC) {
        String query = 'SELECT Id, CRM_Account__c, CRM_Account__r.PTF_PortafoglioAssegnato__c, CRM_RelatedAccount__r.PTF_Portafoglio__c FROM CRM_LinkedNDG__c WHERE CRM_Account__r.RecordType.DeveloperName = \'GruppoFinanziario\' AND CRM_LinkCode__c = \'113\' AND( (CRM_Account__r.PTF_PortafoglioAssegnato__c= true AND CRM_RelatedAccount__r.PTF_Portafoglio__c=null) OR (CRM_Account__r.PTF_PortafoglioAssegnato__c= false AND CRM_RelatedAccount__r.PTF_Portafoglio__c!=null)) ';
        
        
        return Database.getQueryLocator(query);
    }
    
    global void execute(Database.BatchableContext BC, List<CRM_LinkedNDG__c> scope) {
        Map<String, Account> accountToUpdate = new Map<String, Account>();
        for(CRM_LinkedNDG__c link: scope){

           if(!link.CRM_Account__r.PTF_PortafoglioAssegnato__c && String.isNotBlank(link.CRM_RelatedAccount__r.PTF_Portafoglio__c)){
               Account acc= new Account();
               acc.Id=link.CRM_Account__c;
               acc.PTF_PortafoglioAssegnato__c=true;
               accountToUpdate.put(acc.Id, acc);
           }
           else if(link.CRM_Account__r.PTF_PortafoglioAssegnato__c && String.isBlank(link.CRM_RelatedAccount__r.PTF_Portafoglio__c)){
                Account acc= new Account();
                acc.Id=link.CRM_Account__c;
                acc.PTF_PortafoglioAssegnato__c=false;
                accountToUpdate.put(acc.Id, acc);
           }
            

        }
        if(accountToUpdate.size()>0){
            Batch_AccountLink.skipAccountTrigger=true;
            update accountToUpdate.values();
        }
    }
    
    global void finish(Database.BatchableContext BC) {
        
        if (sj!=null && sj.size()>0) {
            JobRunner.executeNext(sj);
        }
    }  
   
}