BPER/DEVF/force-app/main/default/objects/Assignment__c/Assignment__c.object-meta.xml
<CustomObject>
    <label>Portafoglio Assegnato</label>
    <nameField>
        <displayFormat>{000000}</displayFormat>
        <label>Assignment Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Portafogli Assegnati</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

BPER/DEVF/force-app/main/default/objects/Assignment__c/fields/PTF_Filiale__c.field-meta.xml
<CustomField>
    <fullName>PTF_Filiale__c</fullName>
    <formula>PTF_MicroWallet__r.PTF_Filiale__r.Name</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>Filiale</label>
    <type>Text</type>
</CustomField>

BPER/DEVF/force-app/main/default/objects/Assignment__c/recordTypes/Backup.recordType-meta.xml
<RecordType>
    <fullName>Backup</fullName>
    <active>true</active>
    <label>Backup</label>
</RecordType>

BPER/DEVF/force-app/main/default/objects/Assignment__c/recordTypes/Primario.recordType-meta.xml
<RecordType>
    <fullName>Primario</fullName>
    <active>true</active>
    <label>Primario</label>
</RecordType>

BPER/DEVF/force-app/main/default/objects/RoleMDS__c/RoleMDS__c.object-meta.xml
<CustomObject>
    <label>MDS per Ruolo</label>
    <nameField>
        <encryptionScheme>None</encryptionScheme>
        <label>MDS per Ruolo Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>MDS per Ruoli</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

BPER/DEVF/force-app/main/default/objects/RoleMDS__c/fields/PTF_BranchTypology__c.field-meta.xml
<CustomField>
    <fullName>PTF_BranchTypology__c</fullName>
    <label>Tipologia di filiale</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetName>BranchTypology</valueSetName>
    </valueSet>
</CustomField>

BPER/DEVF/force-app/main/default/objects/RoleMDS__c/fields/PTF_EndDate__c.field-meta.xml
<CustomField>
    <fullName>PTF_EndDate__c</fullName>
    <encryptionScheme>None</encryptionScheme>
    <label>Data fine</label>
    <type>Date</type>
</CustomField>

BPER/DEVF/force-app/main/default/objects/RoleMDS__c/fields/PTF_RoleTypology__c.field-meta.xml
<CustomField>
    <fullName>PTF_RoleTypology__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Tipologia di Ruolo</label>
    <referenceTo>RoleTypology__c</referenceTo>
    <relationshipLabel>MDS per Ruoli</relationshipLabel>
    <relationshipName>MDS_per_Ruoli</relationshipName>
    <type>Lookup</type>
</CustomField>

BPER/DEVF/force-app/main/default/objects/RoleMDS__c/fields/PTF_ServiceModel__c.field-meta.xml
<CustomField>
    <fullName>PTF_ServiceModel__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Macro-modello di servizio</label>
    <referenceTo>ServiceModel__c</referenceTo>
    <relationshipLabel>MDS per Ruoli</relationshipLabel>
    <relationshipName>MDS_per_Ruoli</relationshipName>
    <type>Lookup</type>
</CustomField>

BPER/DEVF/force-app/main/default/objects/RoleMDS__c/fields/PTF_StartDate__c.field-meta.xml
<CustomField>
    <fullName>PTF_StartDate__c</fullName>
    <encryptionScheme>None</encryptionScheme>
    <label>Data inizio</label>
    <type>Date</type>
</CustomField>

BPER/DEVF/force-app/main/default/objects/RoleTypology__c/RoleTypology__c.object-meta.xml
<CustomObject>
    <label>Tipologia Ruolo</label>
    <nameField>
        <encryptionScheme>None</encryptionScheme>
        <label>Nome Ruolo</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Tipologia Ruoli</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

BPER/DEVF/force-app/main/default/objects/ServiceModel__c/ServiceModel__c.object-meta.xml
<CustomObject>
    <label>Macro-modello di servizio</label>
    <nameField>
        <encryptionScheme>None</encryptionScheme>
        <label>Nome modello di servizio</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Macro-modelli di servizio</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

BPER/DEVF/force-app/main/default/objects/Wallet__c/Wallet__c.object-meta.xml
<CustomObject>
    <label>Portafoglio</label>
    <nameField>
        <encryptionScheme>None</encryptionScheme>
        <label>Wallet Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Portafogli</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

BPER/DEVF/force-app/main/default/objects/Wallet__c/fields/PTF_BranchTypology__c.field-meta.xml
<CustomField>
    <fullName>PTF_BranchTypology__c</fullName>
    <formula>TEXT(PTF_Filiale__r.PTF_BranchTypology__c)</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>BranchTypology</label>
    <type>Text</type>
</CustomField>

BPER/DEVF/force-app/main/default/objects/Wallet__c/fields/PTF_Filiale__c.field-meta.xml
<CustomField>
    <fullName>PTF_Filiale__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Filiale</label>
    <referenceTo>Account</referenceTo>
    <relationshipLabel>Portafogli (Filiale)</relationshipLabel>
    <relationshipName>Filiali</relationshipName>
    <type>Lookup</type>
</CustomField>

BPER/DEVF/force-app/main/default/objects/Wallet__c/recordTypes/MicroWallet.recordType-meta.xml
<RecordType>
    <fullName>MicroWallet</fullName>
    <active>true</active>
    <label>Microportafoglio</label>
</RecordType>

BPER/POLOWEALTH/force-app/main/default/classes/OnAssignmentTriggerHandlerTest.cls
@IsTest
public with sharing class OnAssignmentTriggerHandlerTest {
    
    @TestSetup
    public static void setup(){
        
        Profile profile = [SELECT id FROM Profile WHERE Name =: Label.System_Administrator LIMIT 1];
        User user = AllDataFactory.getUser('01', profile.Id, 'Couco');
        User user2 = AllDataFactory.getUser('02', profile.Id, 'Couco');
        User user3 = AllDataFactory.getUser('03', profile.Id, 'Couco');
        insert new List<User>{user, user2, user3};
            System.runAs(user3){
                Account banca = AllDataFactory.getAccount('01', 'Banca');
        Account direzioneRegionale = AllDataFactory.getAccount('02', 'DirezioneRegionale');
        Account area = AllDataFactory.getAccount('03', 'Area');
        Account filiale = AllDataFactory.getAccount('04', 'FilialeDiRelazione');
        filiale.PTF_BranchTypology__c = 'A';
        insert new List<Account>{banca, direzioneRegionale, area, filiale};

        RoleTypology__c ruolo = new RoleTypology__c();
        ruolo.Name = 'TestRuolo';
        insert ruolo;

        ServiceModel__c modelloDiServizio = new ServiceModel__c();
        modelloDiServizio.Name = 'Couco';
        insert modelloDiServizio;

        RoleMDS__c ruoloMDS = new RoleMDS__c();
        ruoloMDS.PTF_BranchTypology__c = 'A';
        ruoloMDS.PTF_RoleTypology__c = ruolo.Id;
        ruoloMDS.PTF_ServiceModel__c = modelloDiServizio.Id;
        ruoloMDS.PTF_StartDate__c = Date.today().addDays(-10);
        ruoloMDS.PTF_EndDate__c = Date.today().addDays(10);
        insert ruoloMDS;

        Contact contact = AllDataFactory.getContact('01', user.Id, filiale.Id);
        contact.PTF_TipologiaRuolo__c = ruolo.Id;
        Contact contact2 = AllDataFactory.getContact('02', user2.Id, filiale.Id);
        contact2.PTF_TipologiaRuolo__c = ruolo.Id;
        Contact contact3 = AllDataFactory.getContact('03', user3.Id, filiale.Id);
        contact3.PTF_TipologiaRuolo__c = ruolo.Id;
        insert new List<Contact>{contact, contact2, contact3};

        Wallet__c microPortafoglio = AllDataFactory.getWallet('MicroWallet', filiale.Id, 'Couco');
        insert microPortafoglio;

        Wallet__c microPortafoglio2 = AllDataFactory.getWallet('MicroWallet', '', 'Couco');
        insert microPortafoglio2;

        // Relazione Di Cointestazione
        Account personAccount = AllDataFactory.getAccount('01', 'PersonAccount');
        personAccount.PTF_Portafoglio__c = microPortafoglio.Id;
        personAccount.PTF_Filiale__c = filiale.Id;
        insert personAccount;

        
            }
        
    }
    
    @IsTest
    static void testInsert(){
        
        Wallet__c microPortafoglio = [SELECT ID FROM Wallet__c WHERE RecordType.DeveloperName = 'MicroWallet' and PTF_Filiale__c != null];
        List<Contact> contacts = [SELECT id FROM Contact LIMIT 2];
        Assignment__c backupAssignment = AllDataFactory.getAssignment('Backup', microPortafoglio.Id, contacts[0].Id);
        Assignment__c primarioAssignment = AllDataFactory.getAssignment('Primario', microPortafoglio.Id, contacts[1].Id);
        Test.startTest();
        insert new List<Assignment__c>{backupAssignment, primarioAssignment};
        Test.stopTest();
    }
    @IsTest
    static void testInsert2(){
        
        Wallet__c microPortafoglio = [SELECT ID FROM Wallet__c WHERE RecordType.DeveloperName = 'MicroWallet' and PTF_Filiale__c = null];
        List<Contact> contacts = [SELECT id FROM Contact LIMIT 2];
        Assignment__c backupAssignment = AllDataFactory.getAssignment('Backup', microPortafoglio.Id, contacts[0].Id);
        Assignment__c primarioAssignment = AllDataFactory.getAssignment('Primario', microPortafoglio.Id, contacts[1].Id);
        Test.startTest();
        insert new List<Assignment__c>{backupAssignment, primarioAssignment};
        Test.stopTest();
    }

    @IsTest
    static void testDelete(){
        
        Wallet__c microPortafoglio = [SELECT ID FROM Wallet__c WHERE RecordType.DeveloperName = 'MicroWallet' and PTF_Filiale__c != null];
        List<Contact> contacts = [SELECT id FROM Contact LIMIT 2];
        Assignment__c backupAssignment = AllDataFactory.getAssignment('Backup', microPortafoglio.Id, contacts[0].Id);
        Assignment__c primarioAssignment = AllDataFactory.getAssignment('Primario', microPortafoglio.Id, contacts[1].Id);
        insert new List<Assignment__c>{backupAssignment, primarioAssignment};

        List<Assignment__c> assignmentsToDelete = [SELECT Id, PTF_EndDate__c, PTF_EndDate_DT__c FROM Assignment__c];
        for(Assignment__c assignment : assignmentsToDelete){

            assignment.PTF_EndDate__c = Date.today();
            assignment.PTF_EndDate_DT__c = Datetime.now();
        }

        update assignmentsToDelete;
    }
    @IsTest
    static void tesInvokeBatch(){
        Wallet__c microPortafoglio = [SELECT ID FROM Wallet__c WHERE RecordType.DeveloperName = 'MicroWallet' and PTF_Filiale__c != null];
        List<Contact> contacts = [SELECT id FROM Contact LIMIT 2];
        Assignment__c primarioAssignment = AllDataFactory.getAssignment('Primario', microPortafoglio.Id, contacts[1].Id);
        insert primarioAssignment;
        Set<Id> idAssignment = new Set<Id>();
        Id assId = [SELECT ID FROM Assignment__c LIMIT 1].Id;
        idAssignment.add(assId);


        Id primarioAssignmentId = [SELECT ID FROM Assignment__c LIMIT 1 ].Id;
        OnAssignmentTriggerHandler.invokeBatch('Batch_OnAssignmentTriggerHandler',new Map<String,Object>{'eventType'=> 'onAfterUpdate','idAssignment'=>idAssignment});
    }
}