BPER/DEVF/force-app/main/default/objects/Assignment__c/Assignment__c.object-meta.xml
<CustomObject>
    <label>Portafoglio Assegnato</label>
    <nameField>
        <displayFormat>{000000}</displayFormat>
        <label>Assignment Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Portafogli Assegnati</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

BPER/DEVF/force-app/main/default/objects/Assignment__c/fields/PTF_Filiale__c.field-meta.xml
<CustomField>
    <fullName>PTF_Filiale__c</fullName>
    <formula>PTF_MicroWallet__r.PTF_Filiale__r.Name</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>Filiale</label>
    <type>Text</type>
</CustomField>

BPER/DEVF/force-app/main/default/objects/Assignment__c/fields/PTF_Gestore__c.field-meta.xml
<CustomField>
    <fullName>PTF_Gestore__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Referente</label>
    <referenceTo>Contact</referenceTo>
    <relationshipLabel>Assegnamenti (Referente)</relationshipLabel>
    <relationshipName>Assegnamenti</relationshipName>
    <type>Lookup</type>
</CustomField>

BPER/DEVF/force-app/main/default/objects/Assignment__c/fields/PTF_MicroWallet__c.field-meta.xml
<CustomField>
    <fullName>PTF_MicroWallet__c</fullName>
    <label>Microportafoglio</label>
    <lookupFilter>
        <active>true</active>
        <filterItems>
            <field>Wallet__c.RecordType.DeveloperName</field>
            <operation>equals</operation>
            <value>MicroWallet</value>
        </filterItems>
        <isOptional>false</isOptional>
    </lookupFilter>
    <referenceTo>Wallet__c</referenceTo>
    <relationshipLabel>Assegnamenti</relationshipLabel>
    <relationshipName>Backup_Assignments</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

BPER/DEVF/force-app/main/default/objects/Assignment__c/fields/PTF_ModelloDiServizio__c.field-meta.xml
<CustomField>
    <fullName>PTF_ModelloDiServizio__c</fullName>
    <formula>TEXT( PTF_MicroWallet__r.PTF_ModelloDiServizio__c )</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>Macro-modello di servizio</label>
    <type>Text</type>
</CustomField>

BPER/DEVF/force-app/main/default/objects/Assignment__c/recordTypes/Backup.recordType-meta.xml
<RecordType>
    <fullName>Backup</fullName>
    <active>true</active>
    <label>Backup</label>
</RecordType>

BPER/DEVF/force-app/main/default/objects/Assignment__c/recordTypes/Primario.recordType-meta.xml
<RecordType>
    <fullName>Primario</fullName>
    <active>true</active>
    <label>Primario</label>
</RecordType>

BPER/DEVF/force-app/main/default/objects/CRM_Channel__c/CRM_Channel__c.object-meta.xml
<CustomObject>
    <description>Multicanalità</description>
    <label>Servizio digitale</label>
    <nameField>
        <encryptionScheme>None</encryptionScheme>
        <label>Nome Channel</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Servizi digitali</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

BPER/DEVF/force-app/main/default/objects/CRM_Channel__c/fields/CRM_Account__c.field-meta.xml
<CustomField>
    <fullName>CRM_Account__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Cliente</label>
    <referenceTo>Account</referenceTo>
    <relationshipName>Channel</relationshipName>
    <type>Lookup</type>
</CustomField>

BPER/DEVF/force-app/main/default/objects/CRM_LinkedNDG__c/CRM_LinkedNDG__c.object-meta.xml
<CustomObject>
    <label>NDG collegati</label>
    <nameField>
        <displayFormat>NDGCollegati-{0000000000}</displayFormat>
        <label>Nome NDG collegati</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>NDG collegati</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

BPER/DEVF/force-app/main/default/objects/CRM_LinkedNDG__c/fields/CRM_Account__c.field-meta.xml
<CustomField>
    <fullName>CRM_Account__c</fullName>
    <deleteConstraint>Restrict</deleteConstraint>
    <label>Account</label>
    <referenceTo>Account</referenceTo>
    <relationshipLabel>NDG collegati</relationshipLabel>
    <relationshipName>NDG_collegati</relationshipName>
    <required>true</required>
    <type>Lookup</type>
</CustomField>

BPER/DEVF/force-app/main/default/objects/CRM_LinkedNDG__c/fields/CRM_LinkCode__c.field-meta.xml
<CustomField>
    <fullName>CRM_LinkCode__c</fullName>
    <encryptionScheme>None</encryptionScheme>
    <label>Link Code</label>
    <length>255</length>
    <required>true</required>
    <type>Text</type>
</CustomField>

BPER/DEVF/force-app/main/default/objects/CRM_LinkedNDG__c/fields/CRM_LinkType__c.field-meta.xml
<CustomField>
    <fullName>CRM_LinkType__c</fullName>
    <encryptionScheme>None</encryptionScheme>
    <label>Link Type</label>
    <length>255</length>
    <required>true</required>
    <type>Text</type>
</CustomField>

BPER/DEVF/force-app/main/default/objects/CRM_LinkedNDG__c/fields/CRM_RelatedAccount__c.field-meta.xml
<CustomField>
    <fullName>CRM_RelatedAccount__c</fullName>
    <deleteConstraint>Restrict</deleteConstraint>
    <label>Related Account</label>
    <referenceTo>Account</referenceTo>
    <relationshipLabel>NDG collegati (Related Account)</relationshipLabel>
    <relationshipName>CRM_LinkedNDG</relationshipName>
    <required>true</required>
    <type>Lookup</type>
</CustomField>

BPER/DEVF/force-app/main/default/objects/CRM_LinkedNDG__c/fields/CRM_Status__c.field-meta.xml
<CustomField>
    <fullName>CRM_Status__c</fullName>
    <label>Status</label>
    <required>true</required>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>A</fullName>
            </value>
            <value>
                <fullName>E</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

BPER/DEVF/force-app/main/default/objects/Wallet__c/Wallet__c.object-meta.xml
<CustomObject>
    <label>Portafoglio</label>
    <nameField>
        <encryptionScheme>None</encryptionScheme>
        <label>Wallet Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Portafogli</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

BPER/DEVF/force-app/main/default/objects/Wallet__c/fields/PTF_Filiale__c.field-meta.xml
<CustomField>
    <fullName>PTF_Filiale__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Filiale</label>
    <referenceTo>Account</referenceTo>
    <relationshipLabel>Portafogli (Filiale)</relationshipLabel>
    <relationshipName>Filiali</relationshipName>
    <type>Lookup</type>
</CustomField>

BPER/DEVF/force-app/main/default/objects/Wallet__c/fields/PTF_ModelloDiServizio__c.field-meta.xml
<CustomField>
    <fullName>PTF_ModelloDiServizio__c</fullName>
    <label>Macro-modello di servizio</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetName>Modelli_di_Servizio</valueSetName>
    </valueSet>
</CustomField>

BPER/DEVF/force-app/main/default/objects/Wallet__c/fields/PTF_RegistrationNumber__c.field-meta.xml
<CustomField>
    <fullName>PTF_RegistrationNumber__c</fullName>
    <formula>Owner:User.PTF_RegistrationNumber__c</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>Matricola</label>
    <type>Text</type>
</CustomField>

BPER/DEVF/force-app/main/default/objects/Wallet__c/recordTypes/MicroWallet.recordType-meta.xml
<RecordType>
    <fullName>MicroWallet</fullName>
    <active>true</active>
    <label>Microportafoglio</label>
</RecordType>

BPER/DEVF/force-app/main/default/classes/ApprovalStepsControllerTest.cls
@isTest
public with sharing class ApprovalStepsControllerTest {
    public static final String NDGString = 'NDGTestClass_';
    public static final String USERNAME = 'sitbperbancaapproval@test.test';
    @testSetup 
    public static void setup() {
        Id filialeRTId = [SELECT Id from RecordType where DeveloperName = 'FilialeDiRelazione'][0].Id;
        Id personAccountRTId = [SELECT Id from RecordType where DeveloperName = 'PersonAccount'][0].Id;
        Id cointestazioneRTId = [SELECT Id from RecordType where DeveloperName = 'Cointestazione'][0].Id;
        Id assBackupRTId = [SELECT Id from RecordType where DeveloperName = 'Backup' AND SObjectType = 'Assignment__c'][0].Id;
        Id assPrincipaleRTId = [SELECT Id from RecordType where DeveloperName = 'Primario' AND SObjectType = 'Assignment__c'][0].Id;
        Id microportafoglioRTId = [SELECT Id from RecordType where DeveloperName = 'MicroWallet'][0].Id;
        Id profId = [SELECT Id FROM Profile WHERE Name = 'System Administrator' OR Name = 'Amministratore del sistema'][0].Id;
        User u = new User(Alias = 'standt', Email= USERNAME, 
            EmailEncodingKey='UTF-8', LastName='Testing', LanguageLocaleKey='en_US', 
            LocaleSidKey='en_US', ProfileId = profId, 
            TimeZoneSidKey='America/Los_Angeles', UserName=USERNAME);
        insert u;
        // User u1 = new User(Alias = 'standt1', Email= USERNAME + 'test', 
        //     EmailEncodingKey='UTF-8', LastName='Testing1', LanguageLocaleKey='en_US', 
        //     LocaleSidKey='en_US', ProfileId = profId, 
        //     TimeZoneSidKey='America/Los_Angeles', UserName=USERNAME + 'test');
        // insert u1;
        Account filialeTest1 = new Account(Name = 'Filiale Test 1', RecordTypeId = filialeRTId);
        insert filialeTest1;
        List<Contact> refList = new List<Contact>();
        for (Integer i = 0; i < 5; i++) refList.add(new Contact(LastName = 'Ref_'+i, PTF_RegistrationNumber__c = '00000'+i, AccountId = filialeTest1.Id));
        insert refList;
        List<Wallet__c> walletList = new List<Wallet__c>();
        walletList.add(new Wallet__c(Name = 'Wallet_1', PTF_ModelloDiServizio__c = 'Personal', PTF_Filiale__c = filialeTest1.Id, RecordTypeId = microportafoglioRTId));
        insert walletList;
        List<Assignment__c> assignments = new List<Assignment__c>();
        assignments.add(new Assignment__c(PTF_MicroWallet__c = walletList[0].Id, PTF_Gestore__c = refList[0].Id, RecordTypeId = assPrincipaleRTId));
        assignments.add(new Assignment__c(PTF_MicroWallet__c = walletList[0].Id, PTF_Gestore__c = refList[1].Id, RecordTypeId = assBackupRTId));
        insert assignments;
        List<Account> ndgList = new List<Account>();
        for (Integer i = 0; i < 10; i++) ndgList.add(new Account(LastName = NDGString+i, CRM_NDG__c = '000000'+i, RecordTypeId = personAccountRTId, PTF_Portafoglio__c = walletList[0].Id));
        ndgList.add(new Account(LastName = 'NoWallet_'+NDGString, CRM_NDG__c = '100000', RecordTypeId = personAccountRTId));
        Account coint = new Account(Name = 'NDGCoint', CRM_NDG__c = '200000', RecordTypeId = cointestazioneRTId);
        insert ndgList;
        insert coint;
        CRM_LinkedNDG__c linkedNDG = new CRM_LinkedNDG__c (CRM_Account__c = ndgList[0].Id, CRM_RelatedAccount__c = coint.Id, CRM_LinkCode__c = '0', CRM_LinkType__c = 'Test', CRM_Status__c = 'A');
        insert linkedNDG;
        CRM_Channel__c chan = new CRM_Channel__c(Name = 'Test', CRM_Account__c = ndgList[0].Id);
        insert chan;
        WorkOrder wo = new WorkOrder(Subject = 'WO1', Status = 'Pending');
        insert wo;
        WorkOrderLineItem woli = new WorkOrderLineItem(WorkOrderId = wo.Id);
        insert woli;
        WorkOrderLineItem woli2 = new WorkOrderLineItem(WorkOrderId = wo.Id);
        insert woli2;
        Approval.ProcessSubmitRequest req1 = new Approval.ProcessSubmitRequest();
        req1.setObjectId(wo.Id);
        req1.setProcessDefinitionNameOrId('IterSpostamento3');
        req1.setSkipEntryCriteria(true);
        req1.setNextApproverIds(new Id[] {u.Id});
        Approval.ProcessResult result = Approval.process(req1);

    }

    @isTest
    public static void testing() {
        WorkOrder wo = [SELECT Id FROM WorkOrder WHERE Subject = 'WO1'][0];
		ProcessInstanceWorkitem[] workItems = [ SELECT Id
                                               FROM ProcessInstanceWorkitem 
                                               WHERE ProcessInstance.TargetObjectId =:wo.Id];
        // ProcessInstanceStep procInstStep = new ProcessInstanceStep();
        // procInstStep.ProcessInstanceId = workItems[0].Id;
        // insert procInstStep;

        System.debug('TEST workItems --> ' + workItems);
        ApprovalStepsController.getAllData((workItems[0].Id));
        ApprovalStepsController.testRun();
    }
}