BPER/DEVF/force-app/main/default/objects/Assignment__c/Assignment__c.object-meta.xml
<CustomObject>
    <label>Portafoglio Assegnato</label>
    <nameField>
        <displayFormat>{000000}</displayFormat>
        <label>Assignment Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Portafogli Assegnati</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

BPER/DEVF/force-app/main/default/objects/Assignment__c/fields/PTF_Filiale__c.field-meta.xml
<CustomField>
    <fullName>PTF_Filiale__c</fullName>
    <formula>PTF_MicroWallet__r.PTF_Filiale__r.Name</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>Filiale</label>
    <type>Text</type>
</CustomField>

BPER/DEVF/force-app/main/default/objects/Assignment__c/fields/PTF_MicroWallet__c.field-meta.xml
<CustomField>
    <fullName>PTF_MicroWallet__c</fullName>
    <label>Microportafoglio</label>
    <lookupFilter>
        <active>true</active>
        <filterItems>
            <field>Wallet__c.RecordType.DeveloperName</field>
            <operation>equals</operation>
            <value>MicroWallet</value>
        </filterItems>
        <isOptional>false</isOptional>
    </lookupFilter>
    <referenceTo>Wallet__c</referenceTo>
    <relationshipLabel>Assegnamenti</relationshipLabel>
    <relationshipName>Backup_Assignments</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

BPER/DEVF/force-app/main/default/objects/Assignment__c/fields/PTF_ModelloDiServizio__c.field-meta.xml
<CustomField>
    <fullName>PTF_ModelloDiServizio__c</fullName>
    <formula>TEXT( PTF_MicroWallet__r.PTF_ModelloDiServizio__c )</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>Macro-modello di servizio</label>
    <type>Text</type>
</CustomField>

BPER/DEVF/force-app/main/default/objects/Assignment__c/recordTypes/Primario.recordType-meta.xml
<RecordType>
    <fullName>Primario</fullName>
    <active>true</active>
    <label>Primario</label>
</RecordType>

BPER/DEVF/force-app/main/default/objects/Wallet__c/Wallet__c.object-meta.xml
<CustomObject>
    <label>Portafoglio</label>
    <nameField>
        <encryptionScheme>None</encryptionScheme>
        <label>Wallet Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Portafogli</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

BPER/DEVF/force-app/main/default/objects/Wallet__c/fields/CRM_numNDG__c.field-meta.xml
<CustomField>
    <fullName>CRM_numNDG__c</fullName>
    <defaultValue>0</defaultValue>
    <label>Numero di NDG</label>
    <precision>18</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

BPER/DEVF/force-app/main/default/objects/Wallet__c/fields/CRM_ReferenteFormula__c.field-meta.xml
<CustomField>
    <fullName>CRM_ReferenteFormula__c</fullName>
    <formula>IF(
    PTF_Pool__c,
				&apos;Pool&apos;,
				IF(CRM_ReferentePortafoglio__c != null,
				CRM_ReferentePortafoglio__r.FirstName + &apos; &apos; + CRM_ReferentePortafoglio__r.LastName,
				&apos;Non assegnato&apos;)
)</formula>
    <label>Referente - PTF</label>
    <type>Text</type>
</CustomField>

BPER/DEVF/force-app/main/default/objects/Wallet__c/fields/PTF_Banca__c.field-meta.xml
<CustomField>
    <fullName>PTF_Banca__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Banca</label>
    <referenceTo>Account</referenceTo>
    <relationshipLabel>Portafogli</relationshipLabel>
    <relationshipName>Portafogli</relationshipName>
    <type>Lookup</type>
</CustomField>

BPER/DEVF/force-app/main/default/objects/Wallet__c/fields/PTF_DeletionDate__c.field-meta.xml
<CustomField>
    <fullName>PTF_DeletionDate__c</fullName>
    <encryptionScheme>None</encryptionScheme>
    <label>Data cancellazione</label>
    <type>Date</type>
</CustomField>

BPER/DEVF/force-app/main/default/objects/Wallet__c/fields/PTF_DirezioneRegionale__c.field-meta.xml
<CustomField>
    <fullName>PTF_DirezioneRegionale__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Direzione Regionale</label>
    <referenceTo>Account</referenceTo>
    <relationshipLabel>Portafogli (Direzione Regionale)</relationshipLabel>
    <relationshipName>Portafogli1</relationshipName>
    <type>Lookup</type>
</CustomField>

BPER/DEVF/force-app/main/default/objects/Wallet__c/fields/PTF_Filiale__c.field-meta.xml
<CustomField>
    <fullName>PTF_Filiale__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Filiale</label>
    <referenceTo>Account</referenceTo>
    <relationshipLabel>Portafogli (Filiale)</relationshipLabel>
    <relationshipName>Filiali</relationshipName>
    <type>Lookup</type>
</CustomField>

BPER/DEVF/force-app/main/default/objects/Wallet__c/fields/PTF_isPTFTecnico__c.field-meta.xml
<CustomField>
    <fullName>PTF_isPTFTecnico__c</fullName>
    <formula>IF(
CONTAINS(
TRIM(RIGHT(Name, 7)), &apos;-000075&apos;
), TRUE, FALSE
)</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>Portafoglio 75</label>
    <type>Checkbox</type>
</CustomField>

BPER/DEVF/force-app/main/default/objects/Wallet__c/fields/PTF_ModelloDiServizio__c.field-meta.xml
<CustomField>
    <fullName>PTF_ModelloDiServizio__c</fullName>
    <label>Macro-modello di servizio</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetName>Modelli_di_Servizio</valueSetName>
    </valueSet>
</CustomField>

BPER/DEVF/force-app/main/default/classes/EliminaPortafogliController.cls
public class EliminaPortafogliController {

    // LWC -------------------
    @AuraEnabled
    public static Object init(){
        return new Map<String, Object>{
            'recordList' => [SELECT ID, Name, PTF_ModelloDiServizio__c, PTF_Banca__c, PTF_Banca__r.Name, PTF_Banca__r.FinServ__BankNumber__c, PTF_DirezioneRegionale__c, PTF_DirezioneRegionale__r.Name, PTF_Filiale__c, PTF_Filiale__r.Name, CRM_ReferenteFormula__c, PTF_isPTFTecnico__c FROM Wallet__c WHERE PTF_DeletionDate__c = null AND CRM_numNDG__c = 0 AND 
            Id NOT IN (SELECT PTF_MicroWallet__c FROM Assignment__c WHERE RecordType.DeveloperName = 'Primario' AND PTF_EndDate__c = NULL) AND
            Id NOT IN (SELECT PTF_Destinazione__c FROM WorkOrder WHERE Status = 'Pending') AND (PTF_ModelloDiServizio__c IN ('Personal', 'Small Business', 'Private', 'Consulenti Finanziari', 'Corporate') OR PTF_isPTFTecnico__c = true)]
        };
    }

    @AuraEnabled
    public static void eliminaPortafogli(List<Wallet__c> wallets){
        for (Wallet__c portafoglio : wallets) {
            portafoglio.PTF_DeletionDate__c = Date.today();
        }
        update wallets;
    }
}