BPER/DEVF/force-app/main/default/objects/Assignment__c/Assignment__c.object-meta.xml
<CustomObject>
    <label>Portafoglio Assegnato</label>
    <nameField>
        <displayFormat>{000000}</displayFormat>
        <label>Assignment Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Portafogli Assegnati</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

BPER/DEVF/force-app/main/default/objects/Assignment__c/fields/PTF_Filiale__c.field-meta.xml
<CustomField>
    <fullName>PTF_Filiale__c</fullName>
    <formula>PTF_MicroWallet__r.PTF_Filiale__r.Name</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>Filiale</label>
    <type>Text</type>
</CustomField>

BPER/DEVF/force-app/main/default/objects/Assignment__c/fields/PTF_Gestore__c.field-meta.xml
<CustomField>
    <fullName>PTF_Gestore__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Referente</label>
    <referenceTo>Contact</referenceTo>
    <relationshipLabel>Assegnamenti (Referente)</relationshipLabel>
    <relationshipName>Assegnamenti</relationshipName>
    <type>Lookup</type>
</CustomField>

BPER/DEVF/force-app/main/default/objects/Assignment__c/fields/PTF_Gestore_Name__c.field-meta.xml
<CustomField>
    <fullName>PTF_Gestore_Name__c</fullName>
    <formula>PTF_Gestore__r.FirstName + &quot; &quot; + PTF_Gestore__r.LastName</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>PTF_Gestore_Name</label>
    <type>Text</type>
</CustomField>

BPER/DEVF/force-app/main/default/objects/Assignment__c/fields/PTF_MicroWallet__c.field-meta.xml
<CustomField>
    <fullName>PTF_MicroWallet__c</fullName>
    <label>Microportafoglio</label>
    <lookupFilter>
        <active>true</active>
        <filterItems>
            <field>Wallet__c.RecordType.DeveloperName</field>
            <operation>equals</operation>
            <value>MicroWallet</value>
        </filterItems>
        <isOptional>false</isOptional>
    </lookupFilter>
    <referenceTo>Wallet__c</referenceTo>
    <relationshipLabel>Assegnamenti</relationshipLabel>
    <relationshipName>Backup_Assignments</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

BPER/DEVF/force-app/main/default/objects/Assignment__c/fields/PTF_MiniPortafoglio__c.field-meta.xml
<CustomField>
    <fullName>PTF_MiniPortafoglio__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>MiniWallet</label>
    <referenceTo>MiniWallet__c</referenceTo>
    <relationshipLabel>Assegnamenti</relationshipLabel>
    <relationshipName>Assegnamenti</relationshipName>
    <type>Lookup</type>
</CustomField>

BPER/DEVF/force-app/main/default/objects/Assignment__c/fields/PTF_ModelloDiServizio__c.field-meta.xml
<CustomField>
    <fullName>PTF_ModelloDiServizio__c</fullName>
    <formula>TEXT( PTF_MicroWallet__r.PTF_ModelloDiServizio__c )</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>Macro-modello di servizio</label>
    <type>Text</type>
</CustomField>

BPER/DEVF/force-app/main/default/objects/Assignment__c/recordTypes/Primario.recordType-meta.xml
<RecordType>
    <fullName>Primario</fullName>
    <active>true</active>
    <label>Primario</label>
</RecordType>

BPER/DEVF/force-app/main/default/objects/MiniWallet__c/MiniWallet__c.object-meta.xml
<CustomObject>
    <label>MiniWallet</label>
    <nameField>
        <encryptionScheme>None</encryptionScheme>
        <label>MiniWallet Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>MiniWallets</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

BPER/DEVF/force-app/main/default/objects/MiniWallet__c/fields/PTF_Filiale__c.field-meta.xml
<CustomField>
    <fullName>PTF_Filiale__c</fullName>
    <formula>HYPERLINK(&quot;/&quot; &amp; PTF_Portafoglio__r.PTF_Filiale__c ,PTF_Portafoglio__r.PTF_Filiale__r.Name ,&apos;_self&apos;)</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>Filiale</label>
    <type>Text</type>
</CustomField>

BPER/DEVF/force-app/main/default/objects/MiniWallet__c/fields/PTF_Portafoglio__c.field-meta.xml
<CustomField>
    <fullName>PTF_Portafoglio__c</fullName>
    <label>Portafoglio Padre</label>
    <referenceTo>Wallet__c</referenceTo>
    <relationshipLabel>MiniWallets</relationshipLabel>
    <relationshipName>MiniWallets</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

BPER/DEVF/force-app/main/default/objects/MiniWallet__c/fields/Referente__c.field-meta.xml
<CustomField>
    <fullName>Referente__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Referente Principale</label>
    <referenceTo>Contact</referenceTo>
    <relationshipLabel>MiniWallets</relationshipLabel>
    <relationshipName>MiniWallets</relationshipName>
    <type>Lookup</type>
</CustomField>

BPER/RIORG/force-app/main/default/classes/miniWalletReferentiTableController.cls
public with sharing class miniWalletReferentiTableController {

    @AuraEnabled
    public static List<Assignment__c> getReferenti(String miniwalletId){
        List<Assignment__c> referenti = new List<Assignment__c>();
        MiniWallet__c miniwalletc = [SELECT PTF_Portafoglio__c FROM MiniWallet__c WHERE Id =: miniwalletId LIMIT 1];
        Id walletid = miniwalletc.PTF_Portafoglio__c;
        referenti = [SELECT Id, PTF_Gestore__c, PTF_Gestore_Name__c, PTF_RegistrationNumber__c, PTF_Filiale__c, PTF_ModelloDiServizio__c, PTF_MiniPortafoglio__c
                    FROM Assignment__c
                    WHERE PTF_MicroWallet__c =: walletId
                    AND PTF_EndDate__c = NULL
                    AND PTF_MiniPortafoglio__c = NULL];
        return referenti;
    }

    @AuraEnabled
    public static List<Assignment__c> getReferentiAssegnati(String miniwalletId){
        List<Assignment__c> referentiAssegnati = new List<Assignment__c>();
        referentiAssegnati = [SELECT Id, PTF_Gestore__c, PTF_Gestore_Name__c, PTF_RegistrationNumber__c, PTF_Filiale__c, PTF_ModelloDiServizio__c, PTF_MiniPortafoglio__c
                    FROM Assignment__c
                    WHERE PTF_MiniPortafoglio__c =: miniwalletId
                    AND PTF_EndDate__c = NULL];
        return referentiAssegnati;
    }

    @AuraEnabled
    public static Map<String, String> getReferentePrimario(String miniwalletId){
        String referentePrimarioName = 'si è verificato un errore';
        String idReferentePrimario = '';
        try{
            List<MiniWallet__c> currentMiniwallet = [SELECT Referente__c, Referente__r.Name FROM MiniWallet__c WHERE Id =: miniwalletId LIMIT 1];
            if(currentMiniwallet != null && currentMiniwallet.size() == 1 && currentMiniwallet.get(0).Referente__c != null){
                referentePrimarioName = currentMiniwallet.get(0).Referente__r.Name;
                idReferentePrimario = currentMiniwallet.get(0).Referente__c;
            }else{
                referentePrimarioName = 'nessun referente primario selezionato';
            }        
        }catch(Exception e){
            System.debug('AdF getReferentePrimarioName exception: ' + e.getMessage());
        }

        return new Map<String, String>{
            'name' => referentePrimarioName,
            'id' => idReferentePrimario
        };
    }

    @AuraEnabled
    public static void AssegnaReferenti(String miniWalletID, List<Assignment__c> referenti, List<Assignment__c> referentePrincipale){

        if(miniWalletID != null && referenti != null && miniWalletID != '')
        {

            try{
                
                if(referenti.size() > 0){
                    for(Assignment__c referente : referenti){
                        referente.PTF_MiniPortafoglio__c = miniWalletID;
                    }
                    update referenti;
                }

                if(referentePrincipale != null && referentePrincipale.size() == 1){
                    MiniWallet__c miniwalletc = [SELECT Referente__c FROM MiniWallet__c WHERE Id =: miniwalletId LIMIT 1];
                    miniwalletc.Referente__c = referentePrincipale.get(0).PTF_Gestore__c;
                    update miniwalletc;
                }

            }catch(Exception e){
                System.debug('error AssegnaReferenti: ' + e.getMessage());
            }

        }

    }

    @AuraEnabled
    public static void deleteReferente(String assignment, String referente, String referentePrimario, String miniWalletId){
        try {
            update new Assignment__c (Id = assignment, PTF_MiniPortafoglio__c = null);
            if(referente == referentePrimario){
                update new MiniWallet__c(Id =miniWalletId, Referente__c = null);
            }
        } catch (Exception e) {
            throw new AuraHandledException(e.getMessage());
        }
    }

    @AuraEnabled
    public static void addReferente(List<Assignment__c> referenti, String miniWalletId){
        try {
            for(Assignment__c assignment : referenti){

                assignment.PTF_MiniPortafoglio__c = miniWalletId;
            }
            update referenti;
        } catch (Exception e) {
            throw new AuraHandledException(e.getMessage());
        }
    }

    @AuraEnabled
    public static void addReferentePrimario(String gestore, String miniWalletId){
        try {
            update new MiniWallet__c(Id =miniWalletId, Referente__c = gestore);
        } catch (Exception e) {
            throw new AuraHandledException(e.getMessage());
        }
    }

}