BPER/DEVF/force-app/main/default/objects/Assignment__c/Assignment__c.object-meta.xml
<CustomObject>
    <label>Portafoglio Assegnato</label>
    <nameField>
        <displayFormat>{000000}</displayFormat>
        <label>Assignment Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Portafogli Assegnati</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

BPER/DEVF/force-app/main/default/objects/Assignment__c/fields/PTF_Filiale__c.field-meta.xml
<CustomField>
    <fullName>PTF_Filiale__c</fullName>
    <formula>PTF_MicroWallet__r.PTF_Filiale__r.Name</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>Filiale</label>
    <type>Text</type>
</CustomField>

BPER/DEVF/force-app/main/default/objects/Assignment__c/recordTypes/Backup.recordType-meta.xml
<RecordType>
    <fullName>Backup</fullName>
    <active>true</active>
    <label>Backup</label>
</RecordType>

BPER/DEVF/force-app/main/default/objects/Assignment__c/recordTypes/Primario.recordType-meta.xml
<RecordType>
    <fullName>Primario</fullName>
    <active>true</active>
    <label>Primario</label>
</RecordType>

BPER/DEVF/force-app/main/default/objects/Funzionalita__c/Funzionalita__c.object-meta.xml
<CustomObject>
    <customSettingsType>Hierarchy</customSettingsType>
    <label>Funzionalità</label>
</CustomObject>

BPER/DEVF/force-app/main/default/objects/Funzionalita__c/fields/Disable_Trigger__c.field-meta.xml
<CustomField>
    <fullName>Disable_Trigger__c</fullName>
    <defaultValue>false</defaultValue>
    <label>Disable Trigger</label>
    <type>Checkbox</type>
</CustomField>

BPER/DEVF/force-app/main/default/objects/NDGManagementMember__c/NDGManagementMember__c.object-meta.xml
<CustomObject>
    <label>Referente NDG</label>
    <nameField>
        <displayFormat>{0000}</displayFormat>
        <label>Referente NDG Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Referenti NDG</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

BPER/DEVF/force-app/main/default/objects/NDGManagementMember__c/fields/PTF_EndDate__c.field-meta.xml
<CustomField>
    <fullName>PTF_EndDate__c</fullName>
    <encryptionScheme>None</encryptionScheme>
    <label>Data fine validità</label>
    <type>Date</type>
</CustomField>

BPER/DEVF/force-app/main/default/objects/NDGManagementMember__c/fields/PTF_Filiale__c.field-meta.xml
<CustomField>
    <fullName>PTF_Filiale__c</fullName>
    <formula>PTF_NDG__r.PTF_FilialeNoEncryption__c</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>Filiale</label>
    <type>Text</type>
</CustomField>

BPER/DEVF/force-app/main/default/objects/NDGManagementMember__c/fields/PTF_StartDate__c.field-meta.xml
<CustomField>
    <fullName>PTF_StartDate__c</fullName>
    <encryptionScheme>None</encryptionScheme>
    <label>Data inizio validità</label>
    <type>Date</type>
</CustomField>

BPER/DEVF/force-app/main/default/objects/RoleMDS__c/RoleMDS__c.object-meta.xml
<CustomObject>
    <label>MDS per Ruolo</label>
    <nameField>
        <encryptionScheme>None</encryptionScheme>
        <label>MDS per Ruolo Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>MDS per Ruoli</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

BPER/DEVF/force-app/main/default/objects/RoleMDS__c/fields/PTF_BranchTypology__c.field-meta.xml
<CustomField>
    <fullName>PTF_BranchTypology__c</fullName>
    <label>Tipologia di filiale</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetName>BranchTypology</valueSetName>
    </valueSet>
</CustomField>

BPER/DEVF/force-app/main/default/objects/RoleMDS__c/fields/PTF_EndDate__c.field-meta.xml
<CustomField>
    <fullName>PTF_EndDate__c</fullName>
    <encryptionScheme>None</encryptionScheme>
    <label>Data fine</label>
    <type>Date</type>
</CustomField>

BPER/DEVF/force-app/main/default/objects/RoleMDS__c/fields/PTF_IdCED__c.field-meta.xml
<CustomField>
    <fullName>PTF_IdCED__c</fullName>
    <encryptionScheme>None</encryptionScheme>
    <label>ID CED</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

BPER/DEVF/force-app/main/default/objects/RoleMDS__c/fields/PTF_RoleTypology__c.field-meta.xml
<CustomField>
    <fullName>PTF_RoleTypology__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Tipologia di Ruolo</label>
    <referenceTo>RoleTypology__c</referenceTo>
    <relationshipLabel>MDS per Ruoli</relationshipLabel>
    <relationshipName>MDS_per_Ruoli</relationshipName>
    <type>Lookup</type>
</CustomField>

BPER/DEVF/force-app/main/default/objects/RoleMDS__c/fields/PTF_ServiceModel__c.field-meta.xml
<CustomField>
    <fullName>PTF_ServiceModel__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Macro-modello di servizio</label>
    <referenceTo>ServiceModel__c</referenceTo>
    <relationshipLabel>MDS per Ruoli</relationshipLabel>
    <relationshipName>MDS_per_Ruoli</relationshipName>
    <type>Lookup</type>
</CustomField>

BPER/DEVF/force-app/main/default/objects/RoleMDS__c/fields/PTF_StartDate__c.field-meta.xml
<CustomField>
    <fullName>PTF_StartDate__c</fullName>
    <encryptionScheme>None</encryptionScheme>
    <label>Data inizio</label>
    <type>Date</type>
</CustomField>

BPER/DEVF/force-app/main/default/objects/RoleTypology__c/RoleTypology__c.object-meta.xml
<CustomObject>
    <label>Tipologia Ruolo</label>
    <nameField>
        <encryptionScheme>None</encryptionScheme>
        <label>Nome Ruolo</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Tipologia Ruoli</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

BPER/DEVF/force-app/main/default/objects/RoleTypology__c/fields/PTF_IdCED__c.field-meta.xml
<CustomField>
    <fullName>PTF_IdCED__c</fullName>
    <encryptionScheme>None</encryptionScheme>
    <label>Id CED</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

BPER/DEVF/force-app/main/default/objects/ServiceModel__c/ServiceModel__c.object-meta.xml
<CustomObject>
    <label>Macro-modello di servizio</label>
    <nameField>
        <encryptionScheme>None</encryptionScheme>
        <label>Nome modello di servizio</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Macro-modelli di servizio</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

BPER/DEVF/force-app/main/default/objects/Wallet__c/Wallet__c.object-meta.xml
<CustomObject>
    <label>Portafoglio</label>
    <nameField>
        <encryptionScheme>None</encryptionScheme>
        <label>Wallet Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Portafogli</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

BPER/DEVF/force-app/main/default/objects/Wallet__c/fields/PTF_BranchTypology__c.field-meta.xml
<CustomField>
    <fullName>PTF_BranchTypology__c</fullName>
    <formula>TEXT(PTF_Filiale__r.PTF_BranchTypology__c)</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>BranchTypology</label>
    <type>Text</type>
</CustomField>

BPER/DEVF/force-app/main/default/objects/Wallet__c/fields/PTF_Filiale__c.field-meta.xml
<CustomField>
    <fullName>PTF_Filiale__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Filiale</label>
    <referenceTo>Account</referenceTo>
    <relationshipLabel>Portafogli (Filiale)</relationshipLabel>
    <relationshipName>Filiali</relationshipName>
    <type>Lookup</type>
</CustomField>

BPER/DEVF/force-app/main/default/objects/Wallet__c/recordTypes/MicroWallet.recordType-meta.xml
<RecordType>
    <fullName>MicroWallet</fullName>
    <active>true</active>
    <label>Microportafoglio</label>
</RecordType>

BPER/UNBLU/force-app/main/default/classes/CreateDoppioPresidioControllerTest.cls
@IsTest
public with sharing class CreateDoppioPresidioControllerTest {
    
    @TestSetup
    public static void setup(){
        Funzionalita__c x= new Funzionalita__c();
        x.Disable_Trigger__c=true;
        insert x;
        Profile profile = [SELECT id FROM Profile WHERE Name=: Label.System_Administrator LIMIT 1];
        User user = AllDataFactory.getUser('01', profile.Id, 'CORPORATE');
        User user2 = AllDataFactory.getUser('02', profile.Id, 'CORPORATE');
        User user3 = AllDataFactory.getUser('03', profile.Id, 'CORPORATE');
        insert new List<User>{user, user2, user3};
            System.runAs(user){
                Account banca = AllDataFactory.getAccount('01', 'Banca');
                Account direzioneRegionale = AllDataFactory.getAccount('02', 'DirezioneRegionale');
                Account area = AllDataFactory.getAccount('03', 'Area');
                Account filiale = AllDataFactory.getAccount('04', 'FilialeDiRelazione');
                Account uffPrivate = AllDataFactory.getAccount('99', 'AltraUnitaOrganizzativa');
                uffPrivate.PTF_IdCED__c = '9999';
                uffPrivate.FinServ__BankNumber__c = '05387';
                filiale.PTF_BranchTypology__c = 'A';
                filiale.PTF_IDCEDUffPrivate__c = '9999';
                insert new List<Account>{banca, direzioneRegionale, area, filiale, uffPrivate}
        ;

        Wallet__c microPortafoglio = AllDataFactory.getWallet('MicroWallet', filiale.Id, 'CORPORATE');
        insert microPortafoglio;
        
        Account personAccount = AllDataFactory.getAccount('05', 'PersonAccount');
        personAccount.PTF_Filiale__c = filiale.Id;
        personAccount.PTF_Portafoglio__c = microPortafoglio.Id;
        personAccount.PTF_StatoCRM__c='ATT';
        insert personAccount;

        RoleTypology__c ruolo = new RoleTypology__c();
        ruolo.Name = 'Titolare';
        insert ruolo;

        ServiceModel__c modelloDiServizio = new ServiceModel__c();
        modelloDiServizio.Name = 'CORPORATE';
        insert modelloDiServizio;

        RoleMDS__c ruoloMDS = new RoleMDS__c();
        ruoloMDS.PTF_BranchTypology__c = 'A';
        ruoloMDS.PTF_RoleTypology__c = ruolo.Id;
        ruoloMDS.PTF_ServiceModel__c = modelloDiServizio.Id;
        ruoloMDS.PTF_StartDate__c = Date.today().addDays(-10);
        ruoloMDS.PTF_EndDate__c = Date.today().addDays(10);
        insert ruoloMDS;

        Contact contact = AllDataFactory.getContact('01', user.Id, filiale.Id);
        contact.PTF_TipologiaRuolo__c = ruolo.Id;
        Contact contact2 = AllDataFactory.getContact('02', user2.Id, filiale.Id);
        contact2.PTF_TipologiaRuolo__c = ruolo.Id;
        Contact contact3 = AllDataFactory.getContact('03', user3.Id, filiale.Id);
        contact3.PTF_TipologiaRuolo__c = ruolo.Id;
        insert new List<Contact>{contact, contact2, contact3};

        

        Assignment__c backupAssignment = AllDataFactory.getAssignment('Backup', microPortafoglio.Id, contact.Id);
        Assignment__c primarioAssignment = AllDataFactory.getAssignment('Primario', microPortafoglio.Id, contact2.Id);
        insert new List<Assignment__c>{backupAssignment, primarioAssignment};
            }
        
    }

    @IsTest
    public static void testgetContactRole(){

        User user = [SELECT id FROM User WHERE LastName = 'Test01'];
        System.runAs(user){

            Boolean response = CreateDoppioPresidioController.getContactRole();
        }
    }

    @IsTest
    public static void testGetContactRoleFinanziario(){

        User user = [SELECT id FROM User WHERE LastName = 'Test01' LIMIT 1];
        System.runAs(user){

            Account personAccount = [SELECT id FROM Account WHERE LastName = 'LastName05' LIMIT 1];
            Boolean response = CreateDoppioPresidioController.getContactRoleFinanziario(personAccount.Id);
        }
    }

    @IsTest
    public static void testCreaDoppioPresidioFinanziario(){

        User user = [SELECT id FROM User WHERE LastName = 'Test01' LIMIT 1];
        System.runAs(user){

            Account personAccount = [SELECT id FROM Account WHERE LastName = 'LastName05' LIMIT 1];
            Contact userContact = [SELECT Id FROM Contact WHERE PTF_User__c=:UserInfo.getUserId() LIMIT 1];
            NDGManagementMember__c response = CreateDoppioPresidioController.creaDoppioPresidioFinanziario(personAccount.Id, userContact.Id);
        }
    }

    @IsTest
    public static void testGetNDG(){

        User user = [SELECT id FROM User WHERE LastName = 'Test01' LIMIT 1];
        System.runAs(user){

            Account personAccount = [SELECT id, ModelloDiServizio__c FROM Account WHERE LastName = 'LastName05' LIMIT 1];
            Contact userContact = [SELECT Id FROM Contact WHERE PTF_User__c=:UserInfo.getUserId() LIMIT 1];
            try{
                CreateDoppioPresidioController.DoppioPresidioFinanzirioWrapper response = CreateDoppioPresidioController.getNDG(personAccount.Id, '', '','', new List<String>{personAccount.ModelloDiServizio__c});
            }
            catch(Exception e){
                
            }
        }
    }

    @IsTest
    public static void testGetNDGEstero(){

        User user = [SELECT id FROM User WHERE LastName = 'Test01' LIMIT 1];
        System.runAs(user){

            Account personAccount = [SELECT id, ModelloDiServizio__c FROM Account WHERE LastName = 'LastName05' LIMIT 1];
            Contact userContact = [SELECT Id FROM Contact WHERE PTF_User__c=:UserInfo.getUserId() LIMIT 1];
                CreateDoppioPresidioController.DoppioPresidioEsteroWrapper response = CreateDoppioPresidioController.getNDGEstero(personAccount.Id, '', '', new List<String>{personAccount.ModelloDiServizio__c});
        }
    }

    @IsTest
    public static void testCreateDoppioPresidio(){

        User user = [SELECT id FROM User WHERE LastName = 'Test01' LIMIT 1];
        System.runAs(user){

            Account personAccount = [SELECT id FROM Account WHERE LastName = 'LastName05' LIMIT 1];
            Map<String, SObject> doppiPresidiDaChiudere = SV_Utilities.keyBy([SELECT  Id,
                                PTF_EndDate__c
                        FROM NDGManagementMember__c], 'Id');
            List<NDGManagementMember__c> responseDelete = CreateDoppioPresidioController.deleteDoppioPresidio(personAccount.Id, new List<String>(doppiPresidiDaChiudere.keySet()));
            NDGManagementMember__c response = CreateDoppioPresidioController.createDoppioPresidio(personAccount.Id);
        }
    }

    @IsTest
    public static void testDeleteDoppioPresidioEstero(){

        User user = [SELECT id FROM User WHERE LastName = 'Test01' LIMIT 1];
        System.runAs(user){

            Account personAccount = [SELECT id FROM Account WHERE LastName = 'LastName05' LIMIT 1];
            Map<String, SObject> doppiPresidiDaChiudere = SV_Utilities.keyBy([SELECT  Id,
                                PTF_EndDate__c
                        FROM NDGManagementMember__c], 'Id');
            List<NDGManagementMember__c> responseDelete = CreateDoppioPresidioController.deleteDoppioPresidioEstero(personAccount.Id, new List<String>(doppiPresidiDaChiudere.keySet()));
            
        }
    }

    @IsTest
    public static void testCreaDoppioPresidioEstero(){

        User user = [SELECT id FROM User WHERE LastName = 'Test01' LIMIT 1];
        System.runAs(user){

            Account personAccount = [SELECT id FROM Account WHERE LastName = 'LastName05' LIMIT 1];
            Contact userContact = [SELECT Id FROM Contact WHERE PTF_User__c=:UserInfo.getUserId() LIMIT 1];
            NDGManagementMember__c response = CreateDoppioPresidioController.creazioneDoppioPresidioEstero(personAccount.Id, userContact.Id);
        }
    }

    @IsTest
    public static void testGetDoppioPresidio(){

        User user = [SELECT id FROM User WHERE LastName = 'Test01' LIMIT 1];
        System.runAs(user){

            Account personAccount = [SELECT id, PTF_Filiale__r.PTF_IDCEDUffPrivate__c FROM Account WHERE LastName = 'LastName05' LIMIT 1];
            List<NDGManagementMember__c> response = CreateDoppioPresidioController.getDoppioPresidio(personAccount.Id);
        }
    }

    @IsTest
    public static void testGetDoppioPresidioEstero(){

        User user = [SELECT id FROM User WHERE LastName = 'Test01' LIMIT 1];
        System.runAs(user){

            Account personAccount = [SELECT id FROM Account WHERE LastName = 'LastName05' LIMIT 1];
            List<NDGManagementMember__c> response = CreateDoppioPresidioController.getDoppioPresidioEstero(personAccount.Id);
        }
    }
}