BPER/DEVF/force-app/main/default/objects/Assignment__c/Assignment__c.object-meta.xml
<CustomObject>
    <label>Portafoglio Assegnato</label>
    <nameField>
        <displayFormat>{000000}</displayFormat>
        <label>Assignment Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Portafogli Assegnati</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

BPER/DEVF/force-app/main/default/objects/Assignment__c/recordTypes/Primario.recordType-meta.xml
<RecordType>
    <fullName>Primario</fullName>
    <active>true</active>
    <label>Primario</label>
</RecordType>

BPER/DEVF/force-app/main/default/objects/Funzionalita__c/Funzionalita__c.object-meta.xml
<CustomObject>
    <customSettingsType>Hierarchy</customSettingsType>
    <label>Funzionalità</label>
</CustomObject>

BPER/DEVF/force-app/main/default/objects/Funzionalita__c/fields/Disable_Trigger__c.field-meta.xml
<CustomField>
    <fullName>Disable_Trigger__c</fullName>
    <defaultValue>false</defaultValue>
    <label>Disable Trigger</label>
    <type>Checkbox</type>
</CustomField>

BPER/DEVF/force-app/main/default/objects/Nucleo__c/Nucleo__c.object-meta.xml
<CustomObject>
    <label>Nucleo</label>
    <nameField>
        <displayFormat>N-{00000}</displayFormat>
        <label>Nucleo Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Nucleo</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

BPER/DEVF/force-app/main/default/objects/Nucleo__c/fields/PTF_CodId__c.field-meta.xml
<CustomField>
    <fullName>PTF_CodId__c</fullName>
    <encryptionScheme>None</encryptionScheme>
    <label>Cod Id</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

BPER/DEVF/force-app/main/default/objects/Wallet__c/Wallet__c.object-meta.xml
<CustomObject>
    <label>Portafoglio</label>
    <nameField>
        <encryptionScheme>None</encryptionScheme>
        <label>Wallet Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Portafogli</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

BPER/DEVF/force-app/main/default/objects/Wallet__c/fields/PTF_BranchTypology__c.field-meta.xml
<CustomField>
    <fullName>PTF_BranchTypology__c</fullName>
    <formula>TEXT(PTF_Filiale__r.PTF_BranchTypology__c)</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>BranchTypology</label>
    <type>Text</type>
</CustomField>

BPER/DEVF/force-app/main/default/objects/Wallet__c/fields/PTF_RegistrationNumber__c.field-meta.xml
<CustomField>
    <fullName>PTF_RegistrationNumber__c</fullName>
    <formula>Owner:User.PTF_RegistrationNumber__c</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>Matricola</label>
    <type>Text</type>
</CustomField>

BPER/DEVF/force-app/main/default/objects/Wallet__c/recordTypes/MicroWallet.recordType-meta.xml
<RecordType>
    <fullName>MicroWallet</fullName>
    <active>true</active>
    <label>Microportafoglio</label>
</RecordType>

BPER/RIORG/force-app/main/default/classes/NucleiAppartenenzaControllerTest.cls
@IsTest
public class NucleiAppartenenzaControllerTest {
    
    @IsTest
    static void test(){
        
        Funzionalita__c z= new Funzionalita__c();
        z.Disable_Trigger__c=true;
        insert z;
        
        Test.startTest();
        
        Nucleo__c nuc=new Nucleo__c();
        nuc.PTF_CodId__c ='Test';
        insert nuc;
            
            Account filiale = AllDataFactory.getAccount('04', 'FilialeDiRelazione');
        filiale.PTF_BranchTypology__c = 'A';
        insert filiale;
            
            Contact contact = AllDataFactory.getContact('01', UserInfo.getUserId(), filiale.Id);
            contact.PTF_RegistrationNumber__c='01';
                
            insert new List<Contact>{contact};
        
            Wallet__c microPortafoglio = AllDataFactory.getWallet('MicroWallet', filiale.Id, 'CORPORATE');
                
            insert new List<Wallet__c>{microPortafoglio};
        
                
            Assignment__c primarioAssignment = AllDataFactory.getAssignment('Primario', microPortafoglio.Id, contact.Id);
                
            insert new List<Assignment__c>{primarioAssignment};
            String personAccountRTId= Schema.SObjectType.Account.getRecordTypeInfosByDeveloperName().get('PersonAccount').getRecordTypeId();
            Account acc= new Account();
            acc.LastName='Test';
            acc.PTF_Caponucleo__c=true;
            acc.PTF_Portafoglio__c=microPortafoglio.Id;
            acc.PTF_Nucleo__c=nuc.Id;
            acc.RecordTypeId=personAccountRTId;
              
            Account ndg = AllDataFactory.getAccount('NDG1','PersonAccount');
            ndg.PTF_Portafoglio__c=microPortafoglio.Id;
            ndg.PTF_Nucleo__c=nuc.Id;
            Account ndg2 = AllDataFactory.getAccount('NDG2','Cointestazione');
            ndg2.PTF_Portafoglio__c=microPortafoglio.Id;
            ndg.PTF_Nucleo__c=nuc.Id;
            insert new List<Account>{ndg2, ndg, acc};

            
            System.debug('SV TEST ndg: ' + ndg);
            System.debug('SV TEST ndg2: ' + ndg2);
            
            
            List<String> x = new List<String>();
            x.add(ndg2.Id);
                
            Map<String, Object> a = NucleiAppartenenzaController.getNDG(ndg.Id);
            List<Account> b = NucleiAppartenenzaController.getNDGAppartenenza(ndg.PTF_Nucleo__c,ndg.Id);
            Map<String,Object> c = NucleiAppartenenzaController.loadNdgList(ndg.PTF_Nucleo__c, null, null, ndg.PTF_Portafoglio__c, 1, 1, null, null, null);
            a = NucleiAppartenenzaController.crm_GetNDG(ndg.Id);
            b = NucleiAppartenenzaController.crm_GetNDGAppartenenza(ndg.PTF_Nucleo__c,ndg.Id);
            c = NucleiAppartenenzaController.crm_LoadNdgList(ndg.PTF_Nucleo__c, null, null, ndg.PTF_Portafoglio__c, 1, 1, null, null, null);
            NucleiAppartenenzaController.assignToNucleo(ndg.PTF_Nucleo__c, x);
            
        Test.stopTest();
            
    }

}