BPER/DEVF/force-app/main/default/objects/Assignment__c/Assignment__c.object-meta.xml
<CustomObject>
    <label>Portafoglio Assegnato</label>
    <nameField>
        <displayFormat>{000000}</displayFormat>
        <label>Assignment Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Portafogli Assegnati</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

BPER/DEVF/force-app/main/default/objects/Assignment__c/fields/PTF_Filiale__c.field-meta.xml
<CustomField>
    <fullName>PTF_Filiale__c</fullName>
    <formula>PTF_MicroWallet__r.PTF_Filiale__r.Name</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>Filiale</label>
    <type>Text</type>
</CustomField>

BPER/DEVF/force-app/main/default/objects/Assignment__c/fields/PTF_Gestore__c.field-meta.xml
<CustomField>
    <fullName>PTF_Gestore__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Referente</label>
    <referenceTo>Contact</referenceTo>
    <relationshipLabel>Assegnamenti (Referente)</relationshipLabel>
    <relationshipName>Assegnamenti</relationshipName>
    <type>Lookup</type>
</CustomField>

BPER/DEVF/force-app/main/default/objects/Assignment__c/fields/PTF_MicroWallet__c.field-meta.xml
<CustomField>
    <fullName>PTF_MicroWallet__c</fullName>
    <label>Microportafoglio</label>
    <lookupFilter>
        <active>true</active>
        <filterItems>
            <field>Wallet__c.RecordType.DeveloperName</field>
            <operation>equals</operation>
            <value>MicroWallet</value>
        </filterItems>
        <isOptional>false</isOptional>
    </lookupFilter>
    <referenceTo>Wallet__c</referenceTo>
    <relationshipLabel>Assegnamenti</relationshipLabel>
    <relationshipName>Backup_Assignments</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

BPER/DEVF/force-app/main/default/objects/Assignment__c/fields/PTF_ModelloDiServizio__c.field-meta.xml
<CustomField>
    <fullName>PTF_ModelloDiServizio__c</fullName>
    <formula>TEXT( PTF_MicroWallet__r.PTF_ModelloDiServizio__c )</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>Macro-modello di servizio</label>
    <type>Text</type>
</CustomField>

BPER/DEVF/force-app/main/default/objects/ConfigurazioneSpostamenti__mdt/ConfigurazioneSpostamenti__mdt.object-meta.xml
<CustomObject>
    <label>Configurazione Spostamenti</label>
    <pluralLabel>Configurazione Spostamenti</pluralLabel>
</CustomObject>

BPER/DEVF/force-app/main/default/objects/ConfigurazioneSpostamenti__mdt/fields/Finestra_Temporale__c.field-meta.xml
<CustomField>
    <fullName>Finestra_Temporale__c</fullName>
    <defaultValue>false</defaultValue>
    <label>Finestra Temporale</label>
    <type>Checkbox</type>
</CustomField>

BPER/DEVF/force-app/main/default/objects/ConfigurazioneSpostamenti__mdt/fields/Iter_Approvativo__c.field-meta.xml
<CustomField>
    <fullName>Iter_Approvativo__c</fullName>
    <defaultValue>false</defaultValue>
    <label>Iter Approvativo</label>
    <type>Checkbox</type>
</CustomField>

BPER/DEVF/force-app/main/default/objects/ConfigurazioneSpostamenti__mdt/fields/PTF_Abi__c.field-meta.xml
<CustomField>
    <fullName>PTF_Abi__c</fullName>
    <label>Banca Permessa</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

BPER/DEVF/force-app/main/default/objects/ConfigurazioneSpostamenti__mdt/fields/PTF_CheckCedSpecifico__c.field-meta.xml
<CustomField>
    <fullName>PTF_CheckCedSpecifico__c</fullName>
    <label>Check Ced Specifico</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

BPER/DEVF/force-app/main/default/objects/ConfigurazioneSpostamenti__mdt/fields/PTF_CheckNaturaGiuridica__c.field-meta.xml
<CustomField>
    <fullName>PTF_CheckNaturaGiuridica__c</fullName>
    <label>Check Natura Giuridica</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

BPER/DEVF/force-app/main/default/objects/ConfigurazioneSpostamenti__mdt/fields/PTF_CheckTipologiaFilialeDestinazione__c.field-meta.xml
<CustomField>
    <fullName>PTF_CheckTipologiaFilialeDestinazione__c</fullName>
    <label>Check Tipologia Filiale di Destinazione</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

BPER/DEVF/force-app/main/default/objects/ConfigurazioneSpostamenti__mdt/fields/PTF_CheckTipologiaFilialePartenza__c.field-meta.xml
<CustomField>
    <fullName>PTF_CheckTipologiaFilialePartenza__c</fullName>
    <label>Check Tipologia Filiale di Partenza</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

BPER/DEVF/force-app/main/default/objects/ConfigurazioneSpostamenti__mdt/fields/PTF_Filiale_End__c.field-meta.xml
<CustomField>
    <fullName>PTF_Filiale_End__c</fullName>
    <label>Filiale End</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

BPER/DEVF/force-app/main/default/objects/ConfigurazioneSpostamenti__mdt/fields/PTF_Filiale_Start__c.field-meta.xml
<CustomField>
    <fullName>PTF_Filiale_Start__c</fullName>
    <label>Filiale Start</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

BPER/DEVF/force-app/main/default/objects/ConfigurazioneSpostamenti__mdt/fields/PTF_Filiale_StessaArea__c.field-meta.xml
<CustomField>
    <fullName>PTF_Filiale_StessaArea__c</fullName>
    <defaultValue>false</defaultValue>
    <label>Filiale StessaArea</label>
    <type>Checkbox</type>
</CustomField>

BPER/DEVF/force-app/main/default/objects/ConfigurazioneSpostamenti__mdt/fields/PTF_Filiale_StessaDR__c.field-meta.xml
<CustomField>
    <fullName>PTF_Filiale_StessaDR__c</fullName>
    <defaultValue>false</defaultValue>
    <label>Filiale StessaDR</label>
    <type>Checkbox</type>
</CustomField>

BPER/DEVF/force-app/main/default/objects/ConfigurazioneSpostamenti__mdt/fields/PTF_Filiale_StessoMicroMercato__c.field-meta.xml
<CustomField>
    <fullName>PTF_Filiale_StessoMicroMercato__c</fullName>
    <defaultValue>false</defaultValue>
    <label>Filiale StessoMicroMercato</label>
    <type>Checkbox</type>
</CustomField>

BPER/DEVF/force-app/main/default/objects/ConfigurazioneSpostamenti__mdt/fields/PTF_IsActive__c.field-meta.xml
<CustomField>
    <fullName>PTF_IsActive__c</fullName>
    <defaultValue>true</defaultValue>
    <label>Active</label>
    <type>Checkbox</type>
</CustomField>

BPER/DEVF/force-app/main/default/objects/ConfigurazioneSpostamenti__mdt/fields/PTF_JSON_Approvatori__c.field-meta.xml
<CustomField>
    <fullName>PTF_JSON_Approvatori__c</fullName>
    <label>JSON Approvatori</label>
    <length>131072</length>
    <type>LongTextArea</type>
</CustomField>

BPER/DEVF/force-app/main/default/objects/ConfigurazioneSpostamenti__mdt/fields/PTF_MDS_End__c.field-meta.xml
<CustomField>
    <fullName>PTF_MDS_End__c</fullName>
    <label>MDS End</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

BPER/DEVF/force-app/main/default/objects/ConfigurazioneSpostamenti__mdt/fields/PTF_MDS_Start__c.field-meta.xml
<CustomField>
    <fullName>PTF_MDS_Start__c</fullName>
    <label>MDS Start</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

BPER/DEVF/force-app/main/default/objects/ConfigurazioneSpostamenti__mdt/fields/PTF_StessoReferente__c.field-meta.xml
<CustomField>
    <fullName>PTF_StessoReferente__c</fullName>
    <defaultValue>false</defaultValue>
    <label>Stesso Referente</label>
    <type>Checkbox</type>
</CustomField>

BPER/DEVF/force-app/main/default/objects/ConfigurazioneSpostamenti__mdt/fields/PTF_SuperUsers__c.field-meta.xml
<CustomField>
    <fullName>PTF_SuperUsers__c</fullName>
    <label>Super Users</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

BPER/DEVF/force-app/main/default/objects/ConfigurazioneSpostamenti__mdt/fields/Tipo_di_Spostamento__c.field-meta.xml
<CustomField>
    <fullName>Tipo_di_Spostamento__c</fullName>
    <label>Tipo di Spostamento</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>MDS</fullName>
                <default>true</default>
                <label>MDS</label>
            </value>
            <value>
                <fullName>Filiale</fullName>
            </value>
            <value>
                <fullName>MDS / Filiale</fullName>
            </value>
            <value>
                <fullName>Referenti</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

BPER/DEVF/force-app/main/default/objects/Funzionalita__c/Funzionalita__c.object-meta.xml
<CustomObject>
    <customSettingsType>Hierarchy</customSettingsType>
    <label>Funzionalità</label>
</CustomObject>

BPER/DEVF/force-app/main/default/objects/Funzionalita__c/fields/Disable_Trigger__c.field-meta.xml
<CustomField>
    <fullName>Disable_Trigger__c</fullName>
    <defaultValue>false</defaultValue>
    <label>Disable Trigger</label>
    <type>Checkbox</type>
</CustomField>

BPER/DEVF/force-app/main/default/objects/Nucleo__c/Nucleo__c.object-meta.xml
<CustomObject>
    <label>Nucleo</label>
    <nameField>
        <displayFormat>N-{00000}</displayFormat>
        <label>Nucleo Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Nucleo</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

BPER/DEVF/force-app/main/default/objects/Wallet__c/Wallet__c.object-meta.xml
<CustomObject>
    <label>Portafoglio</label>
    <nameField>
        <encryptionScheme>None</encryptionScheme>
        <label>Wallet Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Portafogli</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

BPER/DEVF/force-app/main/default/objects/Wallet__c/fields/PTF_ABI__c.field-meta.xml
<CustomField>
    <fullName>PTF_ABI__c</fullName>
    <formula>PTF_Banca__r.FinServ__BankNumber__c</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>ABI</label>
    <type>Text</type>
</CustomField>

BPER/DEVF/force-app/main/default/objects/Wallet__c/fields/PTF_Accordato__c.field-meta.xml
<CustomField>
    <fullName>PTF_Accordato__c</fullName>
    <defaultValue>0</defaultValue>
    <label>Accordato</label>
    <precision>18</precision>
    <scale>2</scale>
    <type>Currency</type>
</CustomField>

BPER/DEVF/force-app/main/default/objects/Wallet__c/fields/PTF_Area__c.field-meta.xml
<CustomField>
    <fullName>PTF_Area__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Area</label>
    <referenceTo>Account</referenceTo>
    <relationshipLabel>Portafogli (Area)</relationshipLabel>
    <relationshipName>Portafogli2</relationshipName>
    <type>Lookup</type>
</CustomField>

BPER/DEVF/force-app/main/default/objects/Wallet__c/fields/PTF_Banca__c.field-meta.xml
<CustomField>
    <fullName>PTF_Banca__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Banca</label>
    <referenceTo>Account</referenceTo>
    <relationshipLabel>Portafogli</relationshipLabel>
    <relationshipName>Portafogli</relationshipName>
    <type>Lookup</type>
</CustomField>

BPER/DEVF/force-app/main/default/objects/Wallet__c/fields/PTF_BranchTypeDesc__c.field-meta.xml
<CustomField>
    <fullName>PTF_BranchTypeDesc__c</fullName>
    <formula>PTF_Filiale__r.PTF_BranchTypeDesc__c</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>Modulo</label>
    <type>Text</type>
</CustomField>

BPER/DEVF/force-app/main/default/objects/Wallet__c/fields/PTF_Capofila__c.field-meta.xml
<CustomField>
    <fullName>PTF_Capofila__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Capofila</label>
    <referenceTo>Account</referenceTo>
    <relationshipLabel>Portafogli (Capofila)</relationshipLabel>
    <relationshipName>Portafogli3</relationshipName>
    <type>Lookup</type>
</CustomField>

BPER/DEVF/force-app/main/default/objects/Wallet__c/fields/PTF_DirezioneRegionale__c.field-meta.xml
<CustomField>
    <fullName>PTF_DirezioneRegionale__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Direzione Regionale</label>
    <referenceTo>Account</referenceTo>
    <relationshipLabel>Portafogli (Direzione Regionale)</relationshipLabel>
    <relationshipName>Portafogli1</relationshipName>
    <type>Lookup</type>
</CustomField>

BPER/DEVF/force-app/main/default/objects/Wallet__c/fields/PTF_Fatturato__c.field-meta.xml
<CustomField>
    <fullName>PTF_Fatturato__c</fullName>
    <defaultValue>0</defaultValue>
    <label>Fatturato</label>
    <precision>18</precision>
    <scale>2</scale>
    <type>Currency</type>
</CustomField>

BPER/DEVF/force-app/main/default/objects/Wallet__c/fields/PTF_Filiale__c.field-meta.xml
<CustomField>
    <fullName>PTF_Filiale__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Filiale</label>
    <referenceTo>Account</referenceTo>
    <relationshipLabel>Portafogli (Filiale)</relationshipLabel>
    <relationshipName>Filiali</relationshipName>
    <type>Lookup</type>
</CustomField>

BPER/DEVF/force-app/main/default/objects/Wallet__c/fields/PTF_ModelloDiServizio__c.field-meta.xml
<CustomField>
    <fullName>PTF_ModelloDiServizio__c</fullName>
    <label>Macro-modello di servizio</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetName>Modelli_di_Servizio</valueSetName>
    </valueSet>
</CustomField>

BPER/DEVF/force-app/main/default/objects/Wallet__c/fields/PTF_Patrimonio__c.field-meta.xml
<CustomField>
    <fullName>PTF_Patrimonio__c</fullName>
    <defaultValue>0</defaultValue>
    <label>Patrimonio</label>
    <precision>18</precision>
    <scale>2</scale>
    <type>Currency</type>
</CustomField>

BPER/DEVF/force-app/main/default/objects/Wallet__c/fields/PTF_Pool__c.field-meta.xml
<CustomField>
    <fullName>PTF_Pool__c</fullName>
    <defaultValue>false</defaultValue>
    <label>Pool</label>
    <type>Checkbox</type>
</CustomField>

BPER/DEVF/force-app/main/default/objects/Wallet__c/fields/PTF_Utilizzato__c.field-meta.xml
<CustomField>
    <fullName>PTF_Utilizzato__c</fullName>
    <defaultValue>0</defaultValue>
    <label>Utilizzato</label>
    <precision>18</precision>
    <scale>2</scale>
    <type>Currency</type>
</CustomField>

BPER/DEVF/force-app/main/default/objects/Wallet__c/recordTypes/MicroWallet.recordType-meta.xml
<RecordType>
    <fullName>MicroWallet</fullName>
    <active>true</active>
    <label>Microportafoglio</label>
</RecordType>

BPER/DEVF/force-app/main/default/objects/Wallet__c/recordTypes/TechnicalWallet.recordType-meta.xml
<RecordType>
    <fullName>TechnicalWallet</fullName>
    <active>true</active>
    <label>Portafoglio Tecnico</label>
</RecordType>

BPER/DEV/force-app/main/default/classes/AggiungiMassivamenteNucleiControllerTest.cls
@IsTest
public class AggiungiMassivamenteNucleiControllerTest {
    @TestSetup
    static void setup(){
        Funzionalita__c x = new Funzionalita__c();
        x.Disable_Trigger__c =true;
        insert x;
        Account filiale= new Account();
        filiale.Name='Filiale';
        filiale.RecordTypeId=Schema.SObjectType.Account.getRecordTypeInfosByDeveloperName().get('FilialeDiRelazione').getRecordTypeId();
        filiale.FinServ__BankNumber__c ='05387';
        filiale.PTF_OFS__c =True;
        insert filiale;
       
        
        Account filiale3= new Account();
        filiale3.Name='Filiale';
        filiale3.RecordTypeId=Schema.SObjectType.Account.getRecordTypeInfosByDeveloperName().get('FilialeDiRelazione').getRecordTypeId();
        filiale3.FinServ__BankNumber__c ='05387';
        filiale3.PTF_OFS__c =True;
        filiale3.PTF_IdCED__c = '7113';
        insert filiale3;
        
        Wallet__c microPortafoglio1 = AllDataFactory.getWallet('MicroWallet',  'Filiale', 'Personal');
        microPortafoglio1.Name = 'wallet1';
        microPortafoglio1.PTF_Filiale__c=filiale.Id;
        microPortafoglio1.PTF_Banca__c = filiale.Id;
        insert microPortafoglio1;
        
        Wallet__c microPortafoglio2 = AllDataFactory.getWallet('MicroWallet',  'Filiale', 'Personal');
        microPortafoglio2.PTF_Filiale__c=filiale.Id;
        insert microPortafoglio2;
        
        Wallet__c microPortafoglio3 = AllDataFactory.getWallet('MicroWallet',  'Filiale', 'Personal');
        microPortafoglio3.Name = 'wallet3';
        microPortafoglio3.PTF_Filiale__c=filiale3.Id;
        microPortafoglio3.PTF_Banca__c = filiale3.Id;
        
        
        insert microPortafoglio3;
        List<Nucleo__c> nucToInsert = new List<Nucleo__c>();
        for (Integer i=0; i<3 ; i++){
            Nucleo__c nucleo= new Nucleo__c();
            nucToInsert.add(nucleo);
        }
        insert nucToInsert;
        List<Account> accToInsert= new List<Account>();
        Id rt=Schema.SObjectType.Account.getRecordTypeInfosByDeveloperName().get('PersonAccount').getRecordTypeId();
        for(Integer i=0; i<3 ; i++){
            Account a = new Account();
            a.PTF_Portafoglio__c=microPortafoglio2.Id;
            a.PTF_Nucleo__c=nucToInsert[0].Id;
            if(i==0){
                a.PTF_Caponucleo__c=true;
            }
            if(i<2){
                a.LastName='SI';
            }
            else{
                a.LastName='NO';
            }
            accToInsert.add(a);
        }

        for(Integer i=0; i<3 ; i++){
            Account a = new Account();
            a.PTF_Portafoglio__c=microPortafoglio2.Id;
            a.PTF_Nucleo__c=nucToInsert[1].Id;
            
            if(i==0){
                a.LastName='SI';
                a.PTF_Caponucleo__c=true;
            }
            else{
                a.LastName='NO';
            }
            accToInsert.add(a);
        }

        for(Integer i=0; i<3 ; i++){
            Account a = new Account();
            a.PTF_Portafoglio__c=microPortafoglio2.Id;
            a.PTF_Nucleo__c=nucToInsert[2].Id;
            
            if(i==0){
                a.LastName='NO';
                a.PTF_Caponucleo__c=true;
            }
            else{
                a.LastName='SI';
            }
            accToInsert.add(a);
        }

        

        
        insert accToInsert;
        /*for(Account a: accToInsert){
            System.debug('@@@@ acctoInsert: '+JSON.serialize(a));
        }*/
        

        
    }
    @isTest
    static void testInit(){
        Contact c= new Contact(LastName='test', PTF_User__c=UserInfo.getUserId());
        insert c;
        Wallet__c mp=[SELECT Id, Name, PTF_ModelloDiServizio__c,
        PTF_Filiale__c, PTF_Filiale__r.PTF_BranchTypeDesc__c, PTF_Filiale__r.PTF_BranchTypologyMap__c, PTF_Filiale__r.Name, PTF_FIliale__r.PTF_IdCed__c, PTF_Capofila__c, PTF_Capofila__r.PTF_IdCed__c,
        PTF_Banca__c, PTF_Banca__r.FinServ__BankNumber__c, PTF_Banca__r.PTF_DowngradeReqStartDate__c, PTF_Banca__r.PTF_DowngradeReqEndDate__c, PTF_Banca__r.PTF_IdCed__c,
        PTF_DirezioneRegionale__r.PTF_IdCed__c, PTF_Area__r.PTF_IdCed__c, PTF_DirezioneRegionale__c, PTF_Area__c, Owner.Name, PTF_Fatturato__c, PTF_Patrimonio__c, PTF_Utilizzato__c, PTF_Accordato__c,
        PTF_DirezioneRegionale__r.PTF_DowngradeReqStartDate__c, PTF_DirezioneRegionale__r.PTF_DowngradeReqEndDate__c, PTF_Pool__c, PTF_Filiale__r.PTF_DowngradeReqStartDate__c, PTF_Filiale__r.PTF_DowngradeReqEndDate__c,
        (SELECT id, PTF_Gestore__c, PTF_Gestore__r.PTF_OFS__c, PTF_Gestore__r.Name FROM Backup_Assignments__r )
        FROM Wallet__c LIMIT 1];
        Map<String, Object> output = AggiungiMassivamenteNucleiController.init(mp.Id);
        System.debug('output '+ AggiungiMassivamenteNucleiController.init(mp.Id) );
        System.assertEquals(False,output.get('hasOFS'));
        System.assertEquals([SELECT Id, Profile.Name, Profilo__c, PTF_RuoloLDAP__c, idced__c, PTF_IdCEDPadre__c, banca__c FROM User WHERE id =: UserInfo.getUserId()],output.get('currentUser'));
        
    }

    @isTest
    static void testLoadUpdate(){
        Test.startTest();
        List<Wallet__c> mp=[SELECT Id, PTF_Filiale__c, PTF_Filiale__r.PTF_BranchTypeDesc__c, PTF_Banca__r.FinServ__BankNumber__c, PTF_ModelloDiServizio__c FROM Wallet__c ORDER BY CreatedDate asc LIMIT 2];     
        List<String> rt= new List<String>();
        rt.add('TechnicalWallet');
        Map<String,Object> loadMwListOut=AggiungiMassivamenteNucleiController.loadMwList(mp[0].PTF_Filiale__c, 'Personal', null, mp[0].Id, 0, 5, rt);
        System.Debug('loadMwListOut '+loadMwListOut);
        Map<String,Object> loadNdgListOut = AggiungiMassivamenteNucleiController.loadNdgList(mp[1], 'Test',  null, 0, 5, mp[0]);
        System.Debug('loadNdgListOut '+loadNdgListOut);
        List<Account> ndgList = [SELECT Id, PTF_Nucleo__c ,LastName FROM Account WHERE LastName='SI' ];
        List<String> ndgIdList = new List<String>();
        for(Account a:ndgList){
            ndgIdList.add(a.Id);
            system.debug('@@@: '+a.LastName+'_'+a.PTF_Nucleo__c);
        }
    

        AggiungiMassivamenteNucleiController.moveNdgsToWallet(mp[0].Id, ndgIdList, mp[1].Id);
        Test.stopTest();
    }
    
    
    @isTest
    static void testcheckEligible(){
        Test.startTest();
        Contact c= new Contact(LastName='test', PTF_User__c=UserInfo.getUserId());
        insert c;
        List<Wallet__c> mp=[SELECT Id, PTF_Filiale__c, PTF_Filiale__r.PTF_BranchTypeDesc__c, PTF_Banca__r.FinServ__BankNumber__c, PTF_ModelloDiServizio__c FROM Wallet__c where  Name =: 'wallet1'  LIMIT 1];
        List<String> rt= new List<String>();
        rt.add('TechnicalWallet');
        Map<String,Object> loadMwListOut=AggiungiMassivamenteNucleiController.loadMwList(mp[0].PTF_Filiale__c, 'Personal', null, mp[0].Id, 0, 5, rt);
        Account acc = [SELECT Id ,PTF_OFS__c,LastName,FinServ__BankNumber__c FROM Account WHERE FinServ__BankNumber__c ='05387' limit 1];
        
        ConfigurazioneSpostamenti__mdt cs= [SELECT Id, MasterLabel, PTF_MDS_End__c, PTF_MDS_Start__c,
                                PTF_Abi__c, Finestra_Temporale__c, Iter_Approvativo__c,
                                PTF_Filiale_End__c, PTF_Filiale_Start__c, PTF_Filiale_StessaArea__c, PTF_Filiale_StessaDR__c,
                                PTF_Filiale_StessoMicroMercato__c, PTF_JSON_Approvatori__c, PTF_StessoReferente__c,
                                PTF_CheckNaturaGiuridica__c, PTF_CheckTipologiaFilialeDestinazione__c,
                                PTF_CheckCedSpecifico__c, PTF_CheckTipologiaFilialePartenza__c, Tipo_di_Spostamento__c
                                ,PTF_SuperUsers__c
                                FROM ConfigurazioneSpostamenti__mdt
                                WHERE Tipo_di_Spostamento__c = 'Referenti' AND
                                PTF_MDS_Start__c ='Personal' and PTF_MDS_End__c ='Personal' AND PTF_IsActive__c = true and PTF_Abi__c= '05387' limit 1];
        
		
        AggiungiMassivamenteNucleiController.checkEligible(mp[0],acc , mp[0]);
        Test.stopTest();
    }
    
   
}