BPER/DEVF/force-app/main/default/objects/Assignment__c/Assignment__c.object-meta.xml
<CustomObject>
    <label>Portafoglio Assegnato</label>
    <nameField>
        <displayFormat>{000000}</displayFormat>
        <label>Assignment Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Portafogli Assegnati</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

BPER/DEVF/force-app/main/default/objects/Assignment__c/recordTypes/Primario.recordType-meta.xml
<RecordType>
    <fullName>Primario</fullName>
    <active>true</active>
    <label>Primario</label>
</RecordType>

BPER/DEVF/force-app/main/default/objects/Nucleo__c/Nucleo__c.object-meta.xml
<CustomObject>
    <label>Nucleo</label>
    <nameField>
        <displayFormat>N-{00000}</displayFormat>
        <label>Nucleo Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Nucleo</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

BPER/DEVF/force-app/main/default/objects/Nucleo__c/fields/PTF_CodId__c.field-meta.xml
<CustomField>
    <fullName>PTF_CodId__c</fullName>
    <encryptionScheme>None</encryptionScheme>
    <label>Cod Id</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

BPER/DEVF/force-app/main/default/objects/Wallet__c/Wallet__c.object-meta.xml
<CustomObject>
    <label>Portafoglio</label>
    <nameField>
        <encryptionScheme>None</encryptionScheme>
        <label>Wallet Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Portafogli</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

BPER/DEVF/force-app/main/default/objects/Wallet__c/fields/PTF_BranchTypology__c.field-meta.xml
<CustomField>
    <fullName>PTF_BranchTypology__c</fullName>
    <formula>TEXT(PTF_Filiale__r.PTF_BranchTypology__c)</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>BranchTypology</label>
    <type>Text</type>
</CustomField>

BPER/DEVF/force-app/main/default/objects/Wallet__c/fields/PTF_RegistrationNumber__c.field-meta.xml
<CustomField>
    <fullName>PTF_RegistrationNumber__c</fullName>
    <formula>Owner:User.PTF_RegistrationNumber__c</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>Matricola</label>
    <type>Text</type>
</CustomField>

BPER/DEVF/force-app/main/default/objects/Wallet__c/recordTypes/MicroWallet.recordType-meta.xml
<RecordType>
    <fullName>MicroWallet</fullName>
    <active>true</active>
    <label>Microportafoglio</label>
</RecordType>

BPER/PROD/force-app/main/default/classes/NucleiActionControllerTest.cls
@IsTest
public  class NucleiActionControllerTest {
    @TestSetup
        public static void setup(){

            Account filiale = AllDataFactory.getAccount('04', 'FilialeDiRelazione');
            filiale.PTF_BranchTypology__c = 'A';
            insert filiale;
            
            Nucleo__c nuc=new Nucleo__c();
            nuc.PTF_CodId__c ='Test';
            insert nuc;
            
            Profile profile = [SELECT id FROM Profile WHERE Name =: Label.System_Administrator LIMIT 1];
            User user = AllDataFactory.getUser('01', profile.Id, 'CORPORATE');
            insert user;
            System.runAs(user){
                Contact contact = AllDataFactory.getContact('01', user.Id, filiale.Id);
                contact.PTF_RegistrationNumber__c='01';
                
                insert new List<Contact>{contact};
        
                Wallet__c microPortafoglio = AllDataFactory.getWallet('MicroWallet', filiale.Id, 'CORPORATE');
                
                insert new List<Wallet__c>{microPortafoglio};
        
                
                Assignment__c primarioAssignment = AllDataFactory.getAssignment('Primario', microPortafoglio.Id, contact.Id);
                
                insert new List<Assignment__c>{primarioAssignment};
                String personAccountRTId= Schema.SObjectType.Account.getRecordTypeInfosByDeveloperName().get('PersonAccount').getRecordTypeId();
                Account acc= new Account();
                acc.LastName='Test';
                acc.PTF_Caponucleo__c=true;
                acc.PTF_Portafoglio__c=microPortafoglio.Id;
                acc.PTF_Nucleo__c=nuc.Id;
                acc.RecordTypeId=personAccountRTId;
              
                Account ndg = AllDataFactory.getAccount('NDG1','PersonAccount');
                ndg.PTF_Portafoglio__c=microPortafoglio.Id;
                ndg.PTF_Nucleo__c=nuc.Id;
                Account ndg2 = AllDataFactory.getAccount('NDG2','Cointestazione');
                ndg2.PTF_Portafoglio__c=microPortafoglio.Id;
                ndg.PTF_Nucleo__c=nuc.Id;
                insert new List<Account>{ndg2, ndg, acc};
                }    
        }
        @IsTest
        static void test(){
            Test.startTest();
            User u =[SELECT Id FROM User WHERE LastName='Test01'];
            Account ndg;
            Account ndg2;
            System.runAs(u){
                 ndg= [SELECT Id, PTF_Nucleo__c FROM Account WHERE Name='Test' LIMIT 1];
                 ndg2= [SELECT Id, PTF_Nucleo__c FROM Account WHERE LastName='LastNameNDG1' LIMIT 1];
                
                NucleiActionController.getNDG(ndg.Id);
                NucleiActionController.getNDG_aggiungiNDG(ndg.Id);
                NucleiActionController.assegnaCaponucleo(ndg2);
                NucleiActionController.eliminaNDGDaNucleo(ndg);
            }
            
            Test.stopTest();
            System.assertEquals(true , (NucleiActionController.getNDG(ndg.Id)) != null);
            System.assertEquals(true , (NucleiActionController.getNDG_aggiungiNDG(ndg.Id)) != null);
            System.assertEquals(true , (NucleiActionController.eliminaNDGDaNucleo(ndg)) != null);
            
        }
}