BPER/DEVF/force-app/main/default/objects/Assignment__c/Assignment__c.object-meta.xml
<CustomObject>
    <label>Portafoglio Assegnato</label>
    <nameField>
        <displayFormat>{000000}</displayFormat>
        <label>Assignment Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Portafogli Assegnati</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

BPER/DEVF/force-app/main/default/objects/Assignment__c/fields/PTF_Filiale__c.field-meta.xml
<CustomField>
    <fullName>PTF_Filiale__c</fullName>
    <formula>PTF_MicroWallet__r.PTF_Filiale__r.Name</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>Filiale</label>
    <type>Text</type>
</CustomField>

BPER/DEVF/force-app/main/default/objects/Assignment__c/fields/PTF_MicroWallet__c.field-meta.xml
<CustomField>
    <fullName>PTF_MicroWallet__c</fullName>
    <label>Microportafoglio</label>
    <lookupFilter>
        <active>true</active>
        <filterItems>
            <field>Wallet__c.RecordType.DeveloperName</field>
            <operation>equals</operation>
            <value>MicroWallet</value>
        </filterItems>
        <isOptional>false</isOptional>
    </lookupFilter>
    <referenceTo>Wallet__c</referenceTo>
    <relationshipLabel>Assegnamenti</relationshipLabel>
    <relationshipName>Backup_Assignments</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

BPER/DEVF/force-app/main/default/objects/Assignment__c/fields/PTF_MiniPortafoglio__c.field-meta.xml
<CustomField>
    <fullName>PTF_MiniPortafoglio__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>MiniWallet</label>
    <referenceTo>MiniWallet__c</referenceTo>
    <relationshipLabel>Assegnamenti</relationshipLabel>
    <relationshipName>Assegnamenti</relationshipName>
    <type>Lookup</type>
</CustomField>

BPER/DEVF/force-app/main/default/objects/Assignment__c/fields/PTF_ModelloDiServizio__c.field-meta.xml
<CustomField>
    <fullName>PTF_ModelloDiServizio__c</fullName>
    <formula>TEXT( PTF_MicroWallet__r.PTF_ModelloDiServizio__c )</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>Macro-modello di servizio</label>
    <type>Text</type>
</CustomField>

BPER/DEVF/force-app/main/default/objects/Assignment__c/recordTypes/Primario.recordType-meta.xml
<RecordType>
    <fullName>Primario</fullName>
    <active>true</active>
    <label>Primario</label>
</RecordType>

BPER/DEVF/force-app/main/default/objects/MiniWallet__c/MiniWallet__c.object-meta.xml
<CustomObject>
    <label>MiniWallet</label>
    <nameField>
        <encryptionScheme>None</encryptionScheme>
        <label>MiniWallet Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>MiniWallets</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

BPER/DEVF/force-app/main/default/objects/MiniWallet__c/fields/PTF_Filiale__c.field-meta.xml
<CustomField>
    <fullName>PTF_Filiale__c</fullName>
    <formula>HYPERLINK(&quot;/&quot; &amp; PTF_Portafoglio__r.PTF_Filiale__c ,PTF_Portafoglio__r.PTF_Filiale__r.Name ,&apos;_self&apos;)</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>Filiale</label>
    <type>Text</type>
</CustomField>

BPER/DEVF/force-app/main/default/objects/MiniWallet__c/fields/PTF_Portafoglio__c.field-meta.xml
<CustomField>
    <fullName>PTF_Portafoglio__c</fullName>
    <label>Portafoglio Padre</label>
    <referenceTo>Wallet__c</referenceTo>
    <relationshipLabel>MiniWallets</relationshipLabel>
    <relationshipName>MiniWallets</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

BPER/DEVF/force-app/main/default/objects/MiniWallet__c/fields/PTF_SL__c.field-meta.xml
<CustomField>
    <fullName>PTF_SL__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Sportello Leggero</label>
    <referenceTo>Account</referenceTo>
    <relationshipLabel>MiniWallets</relationshipLabel>
    <relationshipName>MiniWallets</relationshipName>
    <type>Lookup</type>
</CustomField>

BPER/DEVF/force-app/main/default/objects/MiniWallet__c/fields/Referente__c.field-meta.xml
<CustomField>
    <fullName>Referente__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Referente Principale</label>
    <referenceTo>Contact</referenceTo>
    <relationshipLabel>MiniWallets</relationshipLabel>
    <relationshipName>MiniWallets</relationshipName>
    <type>Lookup</type>
</CustomField>

BPER/DEVF/force-app/main/default/objects/Wallet__c/Wallet__c.object-meta.xml
<CustomObject>
    <label>Portafoglio</label>
    <nameField>
        <encryptionScheme>None</encryptionScheme>
        <label>Wallet Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Portafogli</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

BPER/DEVF/force-app/main/default/objects/Wallet__c/fields/PTF_Filiale__c.field-meta.xml
<CustomField>
    <fullName>PTF_Filiale__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Filiale</label>
    <referenceTo>Account</referenceTo>
    <relationshipLabel>Portafogli (Filiale)</relationshipLabel>
    <relationshipName>Filiali</relationshipName>
    <type>Lookup</type>
</CustomField>

BPER/DEVF/force-app/main/default/objects/Wallet__c/fields/PTF_ModelloDiServizio__c.field-meta.xml
<CustomField>
    <fullName>PTF_ModelloDiServizio__c</fullName>
    <label>Macro-modello di servizio</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetName>Modelli_di_Servizio</valueSetName>
    </valueSet>
</CustomField>

BPER/DEVF/force-app/main/default/objects/Wallet__c/recordTypes/MicroWallet.recordType-meta.xml
<RecordType>
    <fullName>MicroWallet</fullName>
    <active>true</active>
    <label>Microportafoglio</label>
</RecordType>

BPER/SIT/force-app/main/default/classes/miniWalletReferentiTableControllerTEST.cls
@isTest
private class miniWalletReferentiTableControllerTEST {

    @isTest
    public static void getReferentiTEST() {

        // BASE DATI
        String miniWalletName = 'nomeDelMiniWallet';

        Account filiale = new Account();
        filiale.Name = 'filialeTest';

        Id RecordTypeIdAccount = Schema.SObjectType.Account.getRecordTypeInfosByDeveloperName().get('AltraUnitaOrganizzativa').getRecordTypeId();
        
        filiale.RecordTypeId = RecordTypeIdAccount;
        filiale.PTF_IdCEDPadre__c = '10';
        filiale.PTF_Livello__c = '210';
        
        insert filiale;

        Account pfiliale = new Account();
        pfiliale.FirstName = 'filialeTest';
        pfiliale.LastName = 'filialeTest';
        pfiliale.PTF_IdCED__c = '10';
        pfiliale.PTF_Livello__c = '210';
        insert pfiliale;

        Wallet__c wallet = new Wallet__c();
        Id RecordTypeIdWallet = Schema.SObjectType.Wallet__c.getRecordTypeInfosByDeveloperName().get('MicroWallet').getRecordTypeId();
        wallet.RecordTypeId = RecordTypeIdWallet;

        wallet.PTF_Filiale__c = pfiliale.Id;
        wallet.PTF_ModelloDiServizio__c = 'Personal';
        insert wallet;

        pfiliale.PTF_Portafoglio__c = wallet.id;
        update pfiliale;

        Contact contact = new Contact();
        contact.FirstName = 'Test43039';
        contact.LastName = 'Test43039';
        insert contact;

        Assignment__c referente = new Assignment__c();
        Id RecordTypeIdAssignment = Schema.SObjectType.Assignment__c.getRecordTypeInfosByName().get('Primario').getRecordTypeId();
        referente.RecordTypeId = RecordTypeIdAssignment;
        referente.PTF_MicroWallet__c = wallet.id;
        referente.PTF_EndDate__c = null;
        referente.PTF_MiniPortafoglio__c = null;
        insert referente;

        MiniWallet__c mw = new MiniWallet__c();
        mw.Name = 'Test43039';
        mw.PTF_Portafoglio__c = wallet.id;
        mw.Referente__c = contact.Id;
        mw.PTF_SL__c = pfiliale.Id;
        insert mw;

        List<Account> sportelliLeggeri = new List<Account>();
        sportelliLeggeri.add(pfiliale);
        // FINE BASE DATI

        List<Assignment__c> referenti = new List<Assignment__c>();
        referenti.add(referente);

        Test.startTest();
            miniWalletReferentiTableController.getReferenti(mw.id);
        Test.stopTest();

    }

    @isTest
    public static void getReferentiAssegnatiTEST() {

        // BASE DATI
        String miniWalletName = 'nomeDelMiniWallet';
        Account filiale = new Account();
        filiale.Name = 'filialeTest';

        Id RecordTypeIdAccount = Schema.SObjectType.Account.getRecordTypeInfosByDeveloperName().get('AltraUnitaOrganizzativa').getRecordTypeId();
        
        filiale.RecordTypeId = RecordTypeIdAccount;
        filiale.PTF_IdCEDPadre__c = '10';
        filiale.PTF_Livello__c = '210';
        
        insert filiale;

        Account pfiliale = new Account();
        pfiliale.FirstName = 'filialeTest';
        pfiliale.LastName = 'filialeTest';
        pfiliale.PTF_IdCED__c = '10';
        pfiliale.PTF_Livello__c = '210';
        insert pfiliale;

        Wallet__c wallet = new Wallet__c();
        Id RecordTypeIdWallet = Schema.SObjectType.Wallet__c.getRecordTypeInfosByDeveloperName().get('MicroWallet').getRecordTypeId();
        wallet.RecordTypeId = RecordTypeIdWallet;

        wallet.PTF_Filiale__c = pfiliale.Id;
        wallet.PTF_ModelloDiServizio__c = 'Personal';
        insert wallet;

        pfiliale.PTF_Portafoglio__c = wallet.id;
        update pfiliale;

        Contact contact = new Contact();
        contact.FirstName = 'Test43039';
        contact.LastName = 'Test43039';
        insert contact;

        Assignment__c referente = new Assignment__c();
        Id RecordTypeIdAssignment = Schema.SObjectType.Assignment__c.getRecordTypeInfosByName().get('Primario').getRecordTypeId();
        referente.RecordTypeId = RecordTypeIdAssignment;
        referente.PTF_MicroWallet__c = wallet.id;
        referente.PTF_EndDate__c = null;
        referente.PTF_MiniPortafoglio__c = null;
        insert referente;
        MiniWallet__c mw = new MiniWallet__c();
        mw.Name = 'Test43039';
        mw.PTF_Portafoglio__c = wallet.id;
        mw.Referente__c = contact.Id;
        mw.PTF_SL__c = pfiliale.Id;
        insert mw;
        referente.PTF_MiniPortafoglio__c = mw.id;
        update referente;
        // FINE BASE DATI

        Test.startTest();
            List<Assignment__c> referentiAssegnati = miniWalletReferentiTableController.getReferentiAssegnati(mw.id);
        Test.stopTest();

        System.assertEquals(true, referentiAssegnati.size() > 0, 'errore in recupero referenti assegnati al mini wallet');

    }

    @isTest
    public static void AssegnaReferentiTest() {

        // BASE DATI
        String miniWalletName = 'nomeDelMiniWallet';

        Account filiale = new Account();
        filiale.Name = 'filialeTest';

        Id RecordTypeIdAccount = Schema.SObjectType.Account.getRecordTypeInfosByDeveloperName().get('AltraUnitaOrganizzativa').getRecordTypeId();
        
        filiale.RecordTypeId = RecordTypeIdAccount;
        filiale.PTF_IdCEDPadre__c = '10';
        filiale.PTF_Livello__c = '210';
        
        insert filiale;

        Account pfiliale = new Account();
        pfiliale.FirstName = 'filialeTest';
        pfiliale.LastName = 'filialeTest';
        pfiliale.PTF_IdCED__c = '10';
        pfiliale.PTF_Livello__c = '210';
        insert pfiliale;

        Wallet__c wallet = new Wallet__c();
        Id RecordTypeIdWallet = Schema.SObjectType.Wallet__c.getRecordTypeInfosByDeveloperName().get('MicroWallet').getRecordTypeId();
        wallet.RecordTypeId = RecordTypeIdWallet;

        wallet.PTF_Filiale__c = pfiliale.Id;
        wallet.PTF_ModelloDiServizio__c = 'Personal';
        insert wallet;

        pfiliale.PTF_Portafoglio__c = wallet.id;
        update pfiliale;

        MiniWallet__c mw = new MiniWallet__c();
        mw.Name = 'Test43039';
        mw.PTF_Portafoglio__c = wallet.id;
        
        mw.PTF_SL__c = pfiliale.Id;
        insert mw;

        Contact contact = new Contact();
        contact.FirstName = 'Test43039';
        contact.LastName = 'Test43039';
        insert contact;

        Assignment__c referente = new Assignment__c();
        Id RecordTypeIdAssignment = Schema.SObjectType.Assignment__c.getRecordTypeInfosByName().get('Primario').getRecordTypeId();
        referente.RecordTypeId = RecordTypeIdAssignment;
        referente.PTF_MicroWallet__c = wallet.id;
        referente.PTF_EndDate__c = null;
        referente.PTF_MiniPortafoglio__c = null;
        insert referente;

        // FINE BASE DATI

        List<Assignment__c> referenti = new List<Assignment__c>();
        referenti.add(referente);

        Test.startTest();
            miniWalletReferentiTableController.AssegnaReferenti(mw.id, referenti, referenti);
        Test.stopTest();

    }

    @isTest
    public static void getReferentePrimarioName(){

        // BASE DATI
        String miniWalletName = 'nomeDelMiniWallet';

        Account filiale = new Account();
        filiale.Name = 'filialeTest';

        Id RecordTypeIdAccount = Schema.SObjectType.Account.getRecordTypeInfosByDeveloperName().get('AltraUnitaOrganizzativa').getRecordTypeId();
        
        filiale.RecordTypeId = RecordTypeIdAccount;
        filiale.PTF_IdCEDPadre__c = '10';
        filiale.PTF_Livello__c = '210';
        
        insert filiale;

        Account pfiliale = new Account();
        pfiliale.FirstName = 'filialeTest';
        pfiliale.LastName = 'filialeTest';
        pfiliale.PTF_IdCED__c = '10';
        pfiliale.PTF_Livello__c = '210';
        insert pfiliale;

        Wallet__c wallet = new Wallet__c();
        Id RecordTypeIdWallet = Schema.SObjectType.Wallet__c.getRecordTypeInfosByDeveloperName().get('MicroWallet').getRecordTypeId();
        wallet.RecordTypeId = RecordTypeIdWallet;

        wallet.PTF_Filiale__c = pfiliale.Id;
        wallet.PTF_ModelloDiServizio__c = 'Personal';
        insert wallet;

        pfiliale.PTF_Portafoglio__c = wallet.id;
        update pfiliale;

        Contact contact = new Contact();
        contact.FirstName = 'Test43039';
        contact.LastName = 'Test43039';
        insert contact;

        MiniWallet__c mw = new MiniWallet__c();
        mw.Name = 'Test43039';
        mw.PTF_Portafoglio__c = wallet.id;
        mw.Referente__c = contact.id;
        mw.PTF_SL__c = pfiliale.Id;
        insert mw;

        // FINE BASE DATI

        Test.startTest();
            //String nomeReferentePrimario = miniWalletReferentiTableController.getReferentePrimarioName(mw.id);
        Test.stopTest();

       // System.assertEquals(true, nomeReferentePrimario == 'Test43039 Test43039', 'errore in recupero nome referente primario mini wallet');

    }
}