BPER/DEVF/force-app/main/default/objects/Assignment__c/Assignment__c.object-meta.xml
<CustomObject>
    <label>Portafoglio Assegnato</label>
    <nameField>
        <displayFormat>{000000}</displayFormat>
        <label>Assignment Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Portafogli Assegnati</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

BPER/DEVF/force-app/main/default/objects/Assignment__c/fields/PTF_Filiale__c.field-meta.xml
<CustomField>
    <fullName>PTF_Filiale__c</fullName>
    <formula>PTF_MicroWallet__r.PTF_Filiale__r.Name</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>Filiale</label>
    <type>Text</type>
</CustomField>

BPER/DEVF/force-app/main/default/objects/Assignment__c/fields/PTF_Gestore__c.field-meta.xml
<CustomField>
    <fullName>PTF_Gestore__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Referente</label>
    <referenceTo>Contact</referenceTo>
    <relationshipLabel>Assegnamenti (Referente)</relationshipLabel>
    <relationshipName>Assegnamenti</relationshipName>
    <type>Lookup</type>
</CustomField>

BPER/DEVF/force-app/main/default/objects/Assignment__c/fields/PTF_MicroWallet__c.field-meta.xml
<CustomField>
    <fullName>PTF_MicroWallet__c</fullName>
    <label>Microportafoglio</label>
    <lookupFilter>
        <active>true</active>
        <filterItems>
            <field>Wallet__c.RecordType.DeveloperName</field>
            <operation>equals</operation>
            <value>MicroWallet</value>
        </filterItems>
        <isOptional>false</isOptional>
    </lookupFilter>
    <referenceTo>Wallet__c</referenceTo>
    <relationshipLabel>Assegnamenti</relationshipLabel>
    <relationshipName>Backup_Assignments</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

BPER/DEVF/force-app/main/default/objects/Assignment__c/fields/PTF_ModelloDiServizio__c.field-meta.xml
<CustomField>
    <fullName>PTF_ModelloDiServizio__c</fullName>
    <formula>TEXT( PTF_MicroWallet__r.PTF_ModelloDiServizio__c )</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>Macro-modello di servizio</label>
    <type>Text</type>
</CustomField>

BPER/DEVF/force-app/main/default/objects/Assignment__c/fields/PTF_NomePortafoglio__c.field-meta.xml
<CustomField>
    <fullName>PTF_NomePortafoglio__c</fullName>
    <formula>PTF_MicroWallet__r.Name</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>Nome portafoglio</label>
    <type>Text</type>
</CustomField>

BPER/DEVF/force-app/main/default/objects/Wallet__c/Wallet__c.object-meta.xml
<CustomObject>
    <label>Portafoglio</label>
    <nameField>
        <encryptionScheme>None</encryptionScheme>
        <label>Wallet Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Portafogli</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

BPER/DEVF/force-app/main/default/objects/Wallet__c/fields/CRM_numNDG__c.field-meta.xml
<CustomField>
    <fullName>CRM_numNDG__c</fullName>
    <defaultValue>0</defaultValue>
    <label>Numero di NDG</label>
    <precision>18</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

BPER/DEVF/force-app/main/default/objects/Wallet__c/fields/PTF_Filiale__c.field-meta.xml
<CustomField>
    <fullName>PTF_Filiale__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Filiale</label>
    <referenceTo>Account</referenceTo>
    <relationshipLabel>Portafogli (Filiale)</relationshipLabel>
    <relationshipName>Filiali</relationshipName>
    <type>Lookup</type>
</CustomField>

BPER/DEVF/force-app/main/default/objects/Wallet__c/fields/PTF_ModelloDiServizio__c.field-meta.xml
<CustomField>
    <fullName>PTF_ModelloDiServizio__c</fullName>
    <label>Macro-modello di servizio</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetName>Modelli_di_Servizio</valueSetName>
    </valueSet>
</CustomField>

BPER/DEVF/force-app/main/default/objects/Wallet__c/fields/PTF_Pool__c.field-meta.xml
<CustomField>
    <fullName>PTF_Pool__c</fullName>
    <defaultValue>false</defaultValue>
    <label>Pool</label>
    <type>Checkbox</type>
</CustomField>

BPER/DEVF/force-app/main/default/objects/Wallet__c/fields/PTF_RegistrationNumber__c.field-meta.xml
<CustomField>
    <fullName>PTF_RegistrationNumber__c</fullName>
    <formula>Owner:User.PTF_RegistrationNumber__c</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>Matricola</label>
    <type>Text</type>
</CustomField>

BPER/UAT/force-app/main/default/classes/sganciaReferentePTF_Controller.cls
public with sharing class sganciaReferentePTF_Controller {

    @AuraEnabled
    public static List<Assignment__c> getWallet(String contactId) {

        System.debug('@@gr contactId: '+ contactId);

        List<Assignment__c> ass = [SELECT RecordType.DeveloperName, PTF_Gestore__r.CRM_NomeReferente__c, PTF_MicroWallet__r.CRM_numNDG__c, PTF_MicroWallet__c, PTF_MicroWallet__r.PTF_Pool__c, PTF_NomePortafoglio__c,PTF_ModelloDiServizio__c, PTF_Filiale__c FROM Assignment__c WHERE PTF_EndDate__c = null AND PTF_Gestore__c =: contactId];

        System.debug('@@gr ass: '+ ass);

        return ass;

    }

    @AuraEnabled
    public static List<Contact> getContact(String contactId) {

        System.debug('@@gr contactId: '+ contactId);

        List<Contact> con = [SELECT CRM_NomeReferente__c, PTF_RegistrationNumber__c, PTF_TipologiaRuolo__r.Name, PTF_MDSConcatList__c,PTF_UnitaOrganizzativaNoEncryption__c, PTF_OFS__c FROM Contact WHERE Id =: contactId];

        System.debug('@@gr ass: '+ con);

        return con;

    }

    @AuraEnabled
    public static void sganciaReferente(List<String> assignmentIds, String nomeReferente, String idReferente) {
        // List<Assignment__c> assignmentList = new List<Assignment__c>();

        //  for (String idAss : assignmentIds) {
        //      Assignment__c ass = new Assignment__c(Id= idAss, PTF_EndDate__c = Date.today());
        //      assignmentList.add(ass);
        //  }
        //  update assignmentList;

        sganciaReferentePTF_Batch batchAss = new sganciaReferentePTF_Batch();
        batchAss.listAssignmentToClose = assignmentIds;
        batchAss.nomeReferente = nomeReferente;
        batchAss.idReferente = idReferente;
        Database.executeBatch(batchAss, 200);
      
       

         
    }


}