BPER/DEVF/force-app/main/default/objects/CRM_IngaggioRetiEsterne__c/CRM_IngaggioRetiEsterne__c.object-meta.xml
<CustomObject>
    <label>Ingaggio Reti Esterne</label>
    <nameField>
        <displayFormat>IREX-{00000000}</displayFormat>
        <label>Ingaggio Reti Esterne</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Ingaggi Reti Esterne</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

BPER/DEVF/force-app/main/default/objects/CRM_IngaggioRetiEsterne__c/fields/CRM_Cliente__c.field-meta.xml
<CustomField>
    <fullName>CRM_Cliente__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Cliente</label>
    <referenceTo>Account</referenceTo>
    <relationshipLabel>Ingaggi Reti Esterne</relationshipLabel>
    <relationshipName>Ingaggi_Reti_Esterne</relationshipName>
    <type>Lookup</type>
</CustomField>

BPER/DEVF/force-app/main/default/objects/CRM_IngaggioRetiEsterne__c/fields/CRM_Esito__c.field-meta.xml
<CustomField>
    <fullName>CRM_Esito__c</fullName>
    <label>Esito</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>Cliente interessato</fullName>
                <default>true</default>
                <label>Cliente interessato</label>
            </value>
            <value>
                <fullName>Da ricontattare</fullName>
            </value>
            <value>
                <fullName>Fissato appuntamento</fullName>
            </value>
            <value>
                <fullName>Prodotto venduto</fullName>
            </value>
            <value>
                <fullName>Prodotto non venduto</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

BPER/DEVF/force-app/main/default/objects/CRM_IngaggioRetiEsterne__c/fields/CRM_Motivo__c.field-meta.xml
<CustomField>
    <fullName>CRM_Motivo__c</fullName>
    <encryptionScheme>None</encryptionScheme>
    <label>Motivo</label>
    <length>5000</length>
    <type>LongTextArea</type>
</CustomField>

BPER/DEVF/force-app/main/default/objects/CRM_IngaggioRetiEsterne__c/fields/CRM_Notes__c.field-meta.xml
<CustomField>
    <fullName>CRM_Notes__c</fullName>
    <encryptionScheme>None</encryptionScheme>
    <label>Note</label>
    <length>100000</length>
    <type>LongTextArea</type>
</CustomField>

BPER/DEV/force-app/main/default/classes/OnCRMRetiEsterneTriggerHandlerTest.cls
@isTest
public with sharing class OnCRMRetiEsterneTriggerHandlerTest {
    @TestSetup
    public static void setup(){

        Profile profile = [SELECT id FROM Profile WHERE Name =: Label.System_Administrator LIMIT 1];
        User user = AllDataFactory.getUser('01', profile.Id, 'CORPORATE');
        insert user;

        System.runAs(user)
        {

            Account acc = AllDataFactory.getAccount('01', 'GruppoFinanziario');
            insert acc;

            CRM_IngaggioRetiEsterne__c  crmIngaggioRetiEsterne = new CRM_IngaggioRetiEsterne__c ();
            crmIngaggioRetiEsterne.CRM_Cliente__c=acc.id;
            crmIngaggioRetiEsterne.CRM_Esito__c='test';
            crmIngaggioRetiEsterne.CRM_Motivo__c='test';
            crmIngaggioRetiEsterne.CRM_Notes__c='test';
            
            insert crmIngaggioRetiEsterne;
        }

    }

    @IsTest
        static void testUpdateIngaggioRetiEsterne(){
            CRM_IngaggioRetiEsterne__c retiEsterne = [SELECT id,CRM_Esito__c FROM CRM_IngaggioRetiEsterne__c WHERE CRM_Esito__c='test'];
            retiEsterne.CRM_Esito__c='TEST2';
            update retiEsterne;
        }
}