BPER/DEVF/force-app/main/default/objects/CRM_Note__c/CRM_Note__c.object-meta.xml
<CustomObject>
    <label>Note</label>
    <nameField>
        <encryptionScheme>None</encryptionScheme>
        <label>Nome Nota</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Note</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

BPER/DEVF/force-app/main/default/objects/CRM_Note__c/fields/CRM_Autore__c.field-meta.xml
<CustomField>
    <fullName>CRM_Autore__c</fullName>
    <formula>CreatedBy.FirstName +&apos; &apos;+CreatedBy.LastName</formula>
    <label>Autore</label>
    <type>Text</type>
</CustomField>

BPER/DEVF/force-app/main/default/objects/CRM_ProposteContrattiPreventivi__c/CRM_ProposteContrattiPreventivi__c.object-meta.xml
<CustomObject>
    <label>Proposte/Contratti BStore</label>
    <nameField>
        <encryptionScheme>None</encryptionScheme>
        <label>Nome Proposte/Simulazioni/Preventivi</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Proposte/Simulazioni/Preventivi</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

BPER/DEVF/force-app/main/default/objects/CRM_ProposteContrattiPreventivi__c/fields/CRM_Banca__c.field-meta.xml
<CustomField>
    <fullName>CRM_Banca__c</fullName>
    <encryptionScheme>None</encryptionScheme>
    <label>Banca</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

BPER/DEVF/force-app/main/default/objects/CRM_ProposteContrattiPreventivi__c/fields/CRM_Codiceprodotto__c.field-meta.xml
<CustomField>
    <fullName>CRM_Codiceprodotto__c</fullName>
    <encryptionScheme>None</encryptionScheme>
    <label>Codice prodotto</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

BPER/DEVF/force-app/main/default/objects/CRM_ProposteContrattiPreventivi__c/fields/CRM_DataInserimento__c.field-meta.xml
<CustomField>
    <fullName>CRM_DataInserimento__c</fullName>
    <encryptionScheme>None</encryptionScheme>
    <label>Data Inserimento</label>
    <type>Date</type>
</CustomField>

BPER/DEVF/force-app/main/default/objects/CRM_ProposteContrattiPreventivi__c/fields/CRM_DataScadenza__c.field-meta.xml
<CustomField>
    <fullName>CRM_DataScadenza__c</fullName>
    <encryptionScheme>None</encryptionScheme>
    <label>Data Scadenza</label>
    <type>Date</type>
</CustomField>

BPER/DEVF/force-app/main/default/objects/CRM_ProposteContrattiPreventivi__c/fields/CRM_DataUltimaModifica__c.field-meta.xml
<CustomField>
    <fullName>CRM_DataUltimaModifica__c</fullName>
    <encryptionScheme>None</encryptionScheme>
    <label>Data Ultima Modifica</label>
    <type>Date</type>
</CustomField>

BPER/DEVF/force-app/main/default/objects/CRM_ProposteContrattiPreventivi__c/fields/CRM_Esito__c.field-meta.xml
<CustomField>
    <fullName>CRM_Esito__c</fullName>
    <label>Esito</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>Da contattare</fullName>
                <default>true</default>
                <label>Da contattare</label>
            </value>
            <value>
                <fullName>Fissato appuntamento</fullName>
            </value>
            <value>
                <fullName>Da ricontattare</fullName>
            </value>
            <value>
                <fullName>Prodotto venduto</fullName>
            </value>
            <value>
                <fullName>Cliente non interessato</fullName>
            </value>
            <value>
                <fullName>Cliente non contattabile</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

BPER/DEVF/force-app/main/default/objects/CRM_ProposteContrattiPreventivi__c/fields/CRM_Filiale__c.field-meta.xml
<CustomField>
    <fullName>CRM_Filiale__c</fullName>
    <encryptionScheme>None</encryptionScheme>
    <label>Filiale</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

BPER/DEVF/force-app/main/default/objects/CRM_ProposteContrattiPreventivi__c/fields/CRM_Motivo__c.field-meta.xml
<CustomField>
    <fullName>CRM_Motivo__c</fullName>
    <encryptionScheme>None</encryptionScheme>
    <label>Motivo</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

BPER/DEVF/force-app/main/default/objects/CRM_ProposteContrattiPreventivi__c/fields/CRM_NDGClienticointestatari__c.field-meta.xml
<CustomField>
    <fullName>CRM_NDGClienticointestatari__c</fullName>
    <encryptionScheme>None</encryptionScheme>
    <label>NDG Clienti cointestatari</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

BPER/DEVF/force-app/main/default/objects/CRM_ProposteContrattiPreventivi__c/fields/CRM_NDGCointestazione__c.field-meta.xml
<CustomField>
    <fullName>CRM_NDGCointestazione__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>NDG Cointestazione</label>
    <referenceTo>Account</referenceTo>
    <relationshipLabel>Proposte/Simulazioni/Preventivi (NDG Cointestazione)</relationshipLabel>
    <relationshipName>Proposte_Simulazioni_Preventivi1</relationshipName>
    <type>Lookup</type>
</CustomField>

BPER/DEVF/force-app/main/default/objects/CRM_ProposteContrattiPreventivi__c/fields/CRM_NDGPrimario__c.field-meta.xml
<CustomField>
    <fullName>CRM_NDGPrimario__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>NDG Primario</label>
    <referenceTo>Account</referenceTo>
    <relationshipLabel>Proposte/Simulazioni/Preventivi</relationshipLabel>
    <relationshipName>Proposte_Simulazioni_Preventivi</relationshipName>
    <type>Lookup</type>
</CustomField>

BPER/DEVF/force-app/main/default/objects/CRM_ProposteContrattiPreventivi__c/fields/CRM_Referente__c.field-meta.xml
<CustomField>
    <fullName>CRM_Referente__c</fullName>
    <encryptionScheme>None</encryptionScheme>
    <label>Matricola</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

BPER/DEVF/force-app/main/default/objects/CRM_ProposteContrattiPreventivi__c/fields/CRM_StatoContratto__c.field-meta.xml
<CustomField>
    <fullName>CRM_StatoContratto__c</fullName>
    <label>Stato Contratto</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>Contratto da perfezionare</fullName>
            </value>
            <value>
                <fullName>Contratto concluso</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

BPER/DEVF/force-app/main/default/objects/CRM_ProposteContrattiPreventivi__c/fields/CRM_StatoProposta__c.field-meta.xml
<CustomField>
    <fullName>CRM_StatoProposta__c</fullName>
    <label>Stato Proposta</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>Proposta in corso</fullName>
            </value>
            <value>
                <fullName>Proposta in scadenza</fullName>
            </value>
            <value>
                <fullName>Proposta scaduta</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

BPER/DEVF/force-app/main/default/objects/CRM_ProposteContrattiPreventivi__c/fields/CRM_TipologiaRecord__c.field-meta.xml
<CustomField>
    <fullName>CRM_TipologiaRecord__c</fullName>
    <encryptionScheme>None</encryptionScheme>
    <label>Tipologia record</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

BPER/CIB/force-app/main/default/classes/REST_ScadenziarioStoricoWebService.cls
@RestResource(urlMapping='/v1/scadenziariostoricowebservice/*')
global class REST_ScadenziarioStoricoWebService {
    
    public class SearchNDGException extends Exception{}

    @HttpPost
    global static GetScadenziarioStoricoWebServiceResponse getScadenziarioStoricoWebServiceRequest(ScadenziarioStoricoWebServiceInputDto scriviPropostaCrm){
        System.debug('@@@@@@ REQUEST: '+JSON.serialize(scriviPropostaCrm));
        GetScadenziarioStoricoWebServiceResponse getScadenziarioStoricoWebServiceResponse = new GetScadenziarioStoricoWebServiceResponse();

        RestResponse res;
        RestRequest req;

        
        try{
            req = RestContext.request;
            res = RestContext.response;

            //Set Response Headers
            setHeaders(req, res);
            
            getScadenziarioStoricoWebServiceResponse=process(scriviPropostaCrm, getScadenziarioStoricoWebServiceResponse);


            // return getScadenziarioStoricoWebServiceResponse;
            //Ricerca NDG START
            

            

        }
        catch(SearchNDGException ex){

            System.debug('SearchNDGException ' + ex.getMessage());
            throw new SearchNDGException(ex.getMessage());

        }
        catch(Exception ex){
            System.debug('Exception ' + ex.getMessage());
            throw new SearchNDGException(ex.getMessage());

        }finally {
            // This gets executed after the exception is handled
            WsRestUtils.writeLog('getScadenziarioStoricoWebService', req.httpMethod, JSON.serializePretty(scriviPropostaCrm), 200, 'status', JSON.serializePretty(getScadenziarioStoricoWebServiceResponse),  req.headers,  res.headers, '', '');
            
        }

        return getScadenziarioStoricoWebServiceResponse;
    }

    global class ScadenziarioStoricoWebServiceInputDto{
        global ScadenziarioStoricoCrmWsServiceRequest ScadenziarioStoricoCrmWsServiceRequest;
    }

    global class ScadenziarioStoricoCrmWsServiceRequest{
        global Proposta proposta;
    }

    global class Proposta{
        global String utente;
        global String dataUltimaModifica;
        global String autore;
        global String banca;
        global String filiale;
        global String idProposta;
        global String ndgClientePrimario;
        global String ndgClienteCointestatari;
        global String ndgCointestazione;
        global String codProdotto;
        global String dataScadenza;
        global String codStatoProposta;
        global String descStatoProposta;
        global String descStatoContratto;
        global String dataInserimento;
        global String tipologiaRecord;
        global String nota;
    }

    private static void setHeaders(RestRequest req, RestResponse res){
        if(req.headers.containsKey('testata_operationId')){
            res.addHeader('testata_operationId', req.headers.get('testata_operationId'));
        }
    }

    global class GetScadenziarioStoricoWebServiceResponse{
        global ScadenziarioStoricoWebServiceOutputDto scriviPropostaCrmResponse;

        public GetScadenziarioStoricoWebServiceResponse(){
            this.scriviPropostaCrmResponse = new ScadenziarioStoricoWebServiceOutputDto();
        }
    }

    global class ScadenziarioStoricoWebServiceOutputDto{
        global ScadenziarioStoricoCrmServiceResponse ScadenziarioStoricoCrmServiceResponse;
        public ScadenziarioStoricoWebServiceOutputDto(){
            this.ScadenziarioStoricoCrmServiceResponse = new ScadenziarioStoricoCrmServiceResponse();
        }
    }

    global class ScadenziarioStoricoCrmServiceResponse{
        global String esitoList;
    }

    private static getScadenziarioStoricoWebServiceResponse process(ScadenziarioStoricoWebServiceInputDto getScadenziarioStoricoWebService, GetScadenziarioStoricoWebServiceResponse x){
        System.debug(X);
        List<CRM_ProposteContrattiPreventivi__c> proposteCOntrattiList = [SELECT Id, CRM_NDGCointestazione__c, CRM_DataUltimaModifica__c, CRM_Autore__c, CRM_Banca__c, CRM_Filiale__c, CRM_Id__c, CRM_NDGPrimario__c, CRM_NDGPrimario__r.CRM_NDG__c, CRM_DataScadenza__c, CRM_StatoProposta__c, CRM_StatoContratto__c, CRM_DataInserimento__c, CRM_TipologiaRecord__c, CRM_Note__c FROM CRM_ProposteContrattiPreventivi__c WHERE CRM_NDGPrimario__r.CRM_NDG__c =: getScadenziarioStoricoWebService.ScadenziarioStoricoCrmWsServiceRequest.proposta.ndgClientePrimario AND CRM_Id__c =: getScadenziarioStoricoWebService.ScadenziarioStoricoCrmWsServiceRequest.proposta.idProposta];
        System.debug(getScadenziarioStoricoWebService.ScadenziarioStoricoCrmWsServiceRequest.proposta.ndgClientePrimario);
        List<Account> ndgList = [ SELECT Id 
                     FROM Account 
                     WHERE CRM_NDG__c =: getScadenziarioStoricoWebService.ScadenziarioStoricoCrmWsServiceRequest.proposta.ndgClientePrimario AND 
                        FinServ__BankNumber__c =: getScadenziarioStoricoWebService.ScadenziarioStoricoCrmWsServiceRequest.proposta.banca];
        
        List<Account> cointestazioneList = new List<Account>();
        if(getScadenziarioStoricoWebService.ScadenziarioStoricoCrmWsServiceRequest.proposta.ndgCointestazione != null) {
            cointestazioneList = [ SELECT Id 
                         FROM Account 
                         WHERE CRM_NDG__c =: getScadenziarioStoricoWebService.ScadenziarioStoricoCrmWsServiceRequest.proposta.ndgCointestazione AND 
                            FinServ__BankNumber__c =: getScadenziarioStoricoWebService.ScadenziarioStoricoCrmWsServiceRequest.proposta.banca];
        }
        
        if(ndgList.size() <= 0){

            //throw new SearchNDGException('NDG ' + getScadenziarioStoricoWebService.ScadenziarioStoricoCrmWsServiceRequest.proposta.ndgClientePrimario + ' ABI ' +
                                        //getScadenziarioStoricoWebService.ScadenziarioStoricoCrmWsServiceRequest.proposta.banca + ' NON TROVATO');
            x.scriviPropostaCrmResponse.ScadenziarioStoricoCrmServiceResponse.esitoList = 'OK';
            return x;
        }
        
        if(proposteCOntrattiList.isEmpty()){

            System.debug('ESITO: INSERT');
            String dataUltimaModifica = getScadenziarioStoricoWebService.ScadenziarioStoricoCrmWsServiceRequest.proposta.dataUltimaModifica;
            String dataScadenza = getScadenziarioStoricoWebService.ScadenziarioStoricoCrmWsServiceRequest.proposta.dataScadenza;
            insert new CRM_ProposteContrattiPreventivi__c(
                CRM_NDGCointestazione__c = cointestazioneList.size() > 0 ? cointestazioneList[0].Id : null,
                CRM_DataUltimaModifica__c = getScadenziarioStoricoWebService.ScadenziarioStoricoCrmWsServiceRequest.proposta.dataUltimaModifica != null ? Date.valueOf(dataUltimaModifica.substring(0,4) + '-' + dataUltimaModifica.substring(4,6) + '-' + dataUltimaModifica.substring(6,8)) : null,
                CRM_Autore__c = getScadenziarioStoricoWebService.ScadenziarioStoricoCrmWsServiceRequest.proposta.autore,
                CRM_Banca__c = getScadenziarioStoricoWebService.ScadenziarioStoricoCrmWsServiceRequest.proposta.banca,
                CRM_Filiale__c = getScadenziarioStoricoWebService.ScadenziarioStoricoCrmWsServiceRequest.proposta.filiale,
                CRM_Id__c = getScadenziarioStoricoWebService.ScadenziarioStoricoCrmWsServiceRequest.proposta.idProposta,
                CRM_NDGPrimario__c = ndgList[0].Id,
                CRM_DataScadenza__c = getScadenziarioStoricoWebService.ScadenziarioStoricoCrmWsServiceRequest.proposta.dataScadenza != null ? Date.valueOf(dataScadenza.substring(0,4) + '-' + dataScadenza.substring(4,6) + '-' + dataScadenza.substring(6,8)) : null,
                CRM_StatoProposta__c = getScadenziarioStoricoWebService.ScadenziarioStoricoCrmWsServiceRequest.proposta.descStatoProposta,
                CRM_StatoContratto__c = getScadenziarioStoricoWebService.ScadenziarioStoricoCrmWsServiceRequest.proposta.descStatoContratto,
                CRM_DataInserimento__c = getScadenziarioStoricoWebService.ScadenziarioStoricoCrmWsServiceRequest.proposta.dataInserimento != null ? Date.valueOf(getScadenziarioStoricoWebService.ScadenziarioStoricoCrmWsServiceRequest.proposta.dataInserimento) : null,
                CRM_TipologiaRecord__c = getScadenziarioStoricoWebService.ScadenziarioStoricoCrmWsServiceRequest.proposta.tipologiaRecord,
                CRM_Referente__c = getScadenziarioStoricoWebService.ScadenziarioStoricoCrmWsServiceRequest.proposta.utente,
                CRM_Codiceprodotto__c = getScadenziarioStoricoWebService.ScadenziarioStoricoCrmWsServiceRequest.proposta.codProdotto,
                CRM_NDGClienticointestatari__c = getScadenziarioStoricoWebService.ScadenziarioStoricoCrmWsServiceRequest.proposta.ndgClienteCointestatari,
                CRM_Note__c = getScadenziarioStoricoWebService.ScadenziarioStoricoCrmWsServiceRequest.proposta.nota,
                CRM_Motivo__c = 'Bstore - Proposta/Contratto'
            );
        }else{

            System.debug('ESITO: UPDATE');
            String dataUltimaModifica = getScadenziarioStoricoWebService.ScadenziarioStoricoCrmWsServiceRequest.proposta.dataUltimaModifica;
            String dataScadenza = getScadenziarioStoricoWebService.ScadenziarioStoricoCrmWsServiceRequest.proposta.dataScadenza;
            proposteCOntrattiList[0].CRM_NDGCointestazione__c = cointestazioneList.size() > 0 ? cointestazioneList[0].Id : null;
            proposteCOntrattiList[0].CRM_DataUltimaModifica__c = getScadenziarioStoricoWebService.ScadenziarioStoricoCrmWsServiceRequest.proposta.dataUltimaModifica != null ? Date.valueOf(dataUltimaModifica.substring(0,4) + '-' + dataUltimaModifica.substring(4,6) + '-' + dataUltimaModifica.substring(6,8)) : null;
            proposteCOntrattiList[0].CRM_Autore__c = getScadenziarioStoricoWebService.ScadenziarioStoricoCrmWsServiceRequest.proposta.autore;
            proposteCOntrattiList[0].CRM_Banca__c = getScadenziarioStoricoWebService.ScadenziarioStoricoCrmWsServiceRequest.proposta.banca;
            proposteCOntrattiList[0].CRM_Filiale__c = getScadenziarioStoricoWebService.ScadenziarioStoricoCrmWsServiceRequest.proposta.filiale;
            proposteCOntrattiList[0].CRM_Id__c = getScadenziarioStoricoWebService.ScadenziarioStoricoCrmWsServiceRequest.proposta.idProposta;
            proposteCOntrattiList[0].CRM_NDGPrimario__c = ndgList[0].Id;
            proposteCOntrattiList[0].CRM_DataScadenza__c = getScadenziarioStoricoWebService.ScadenziarioStoricoCrmWsServiceRequest.proposta.dataScadenza != null ? Date.valueOf(dataScadenza.substring(0,4) + '-' + dataScadenza.substring(4,6) + '-' + dataScadenza.substring(6,8)) : null;
            proposteCOntrattiList[0].CRM_StatoProposta__c = getScadenziarioStoricoWebService.ScadenziarioStoricoCrmWsServiceRequest.proposta.descStatoProposta;
            proposteCOntrattiList[0].CRM_StatoContratto__c = getScadenziarioStoricoWebService.ScadenziarioStoricoCrmWsServiceRequest.proposta.descStatoContratto;
            proposteCOntrattiList[0].CRM_DataInserimento__c = getScadenziarioStoricoWebService.ScadenziarioStoricoCrmWsServiceRequest.proposta.dataInserimento != null ? Date.valueOf(getScadenziarioStoricoWebService.ScadenziarioStoricoCrmWsServiceRequest.proposta.dataInserimento) : null;
            proposteCOntrattiList[0].CRM_TipologiaRecord__c = getScadenziarioStoricoWebService.ScadenziarioStoricoCrmWsServiceRequest.proposta.tipologiaRecord;
            proposteCOntrattiList[0].CRM_Referente__c = getScadenziarioStoricoWebService.ScadenziarioStoricoCrmWsServiceRequest.proposta.utente;
            proposteCOntrattiList[0].CRM_Codiceprodotto__c = getScadenziarioStoricoWebService.ScadenziarioStoricoCrmWsServiceRequest.proposta.codProdotto;
            proposteCOntrattiList[0].CRM_NDGClienticointestatari__c = getScadenziarioStoricoWebService.ScadenziarioStoricoCrmWsServiceRequest.proposta.ndgClienteCointestatari;
            proposteCOntrattiList[0].CRM_Note__c = getScadenziarioStoricoWebService.ScadenziarioStoricoCrmWsServiceRequest.proposta.nota;
            if(getScadenziarioStoricoWebService.ScadenziarioStoricoCrmWsServiceRequest.proposta.descStatoContratto == 'Contratto Concluso'){
                proposteCOntrattiList[0].CRM_Esito__c = 'Prodotto venduto';
            }
            update proposteCOntrattiList;
        }


        x.scriviPropostaCrmResponse.ScadenziarioStoricoCrmServiceResponse.esitoList = 'OK';
      
        return x;
    }


}