BPER/DEVF/force-app/main/default/objects/CRM_PoliticheCreditizie__c/CRM_PoliticheCreditizie__c.object-meta.xml
<CustomObject>
    <label>Politiche Creditizie</label>
    <nameField>
        <displayFormat>PC-{0000}</displayFormat>
        <label>Politiche Creditizie Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Politiche Creditizie</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

BPER/DEVF/force-app/main/default/objects/CRM_PoliticheCreditizie__c/fields/CRM_AccountId__c.field-meta.xml
<CustomField>
    <fullName>CRM_AccountId__c</fullName>
    <label>AccountId</label>
    <referenceTo>Account</referenceTo>
    <relationshipLabel>Politiche Creditizie</relationshipLabel>
    <relationshipName>CRM_PoliticheCreditizie</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

BPER/DEVF/force-app/main/default/objects/CRM_PoliticheCreditizie__c/fields/CRM_DescrizioneNACE__c.field-meta.xml
<CustomField>
    <fullName>CRM_DescrizioneNACE__c</fullName>
    <encryptionScheme>None</encryptionScheme>
    <label>Descrizione NACE</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

BPER/RIORG/force-app/main/default/classes/TestOnPoliticheCreditizieTrigger.cls
@isTest
public class TestOnPoliticheCreditizieTrigger {
    static testMethod void testOnPoliticheCreditizieTrigger() {
        // Crea un Account e un PoliticheCreditizie__c collegato
        Account acc = new Account(Name = 'Test Account');
        insert acc;
        CRM_PoliticheCreditizie__c pc = new CRM_PoliticheCreditizie__c(CRM_AccountId__c = acc.Id, CRM_DescrizioneNACE__c = 'Test NACE Description');
        insert pc;
        
        // Verifica che il campo DescrizioneNACE__c dell'Account sia stato copiato correttamente dal PoliticheCreditizie__c durante l'inserimento
        acc = [SELECT Id, CRM_DescrizioneNACE__c FROM Account WHERE Id = :acc.Id];
        System.assertEquals('Test NACE Description', acc.CRM_DescrizioneNACE__c);
        
        // Aggiorna il PoliticheCreditizie__c e verifica che il campo DescrizioneNACE__c dell'Account sia stato aggiornato correttamente
        pc.CRM_DescrizioneNACE__c = 'Updated NACE Description';
        update pc;
        acc = [SELECT Id, CRM_DescrizioneNACE__c FROM Account WHERE Id = :acc.Id];
        System.assertEquals('Updated NACE Description', acc.CRM_DescrizioneNACE__c);
    }
}