BPER/DEVF/force-app/main/default/objects/CRM_AccountDetail__c/CRM_AccountDetail__c.object-meta.xml
<CustomObject>
    <label>Dettaglio Account</label>
    <nameField>
        <encryptionScheme>None</encryptionScheme>
        <label>Nome Dettaglio Account</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Dettagli Account</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

BPER/DEVF/force-app/main/default/objects/CRM_AccountDetail__c/fields/CRM_Account__c.field-meta.xml
<CustomField>
    <fullName>CRM_Account__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Account</label>
    <referenceTo>Account</referenceTo>
    <relationshipLabel>Dettagli Account</relationshipLabel>
    <relationshipName>Dettagli_Account</relationshipName>
    <type>Lookup</type>
</CustomField>

BPER/DEVF/force-app/main/default/objects/TrackingHistory__c/TrackingHistory__c.object-meta.xml
<CustomObject>
    <description>Object to track changes</description>
    <label>TrackingHistory</label>
    <nameField>
        <displayFormat>TH-{00000000}</displayFormat>
        <label>TrackingHistory Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>TrackingHistories</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

BPER/DEVF/force-app/main/default/objects/TrackingHistory__c/fields/Cliente__c.field-meta.xml
<CustomField>
    <fullName>Cliente__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Cliente</label>
    <referenceTo>Account</referenceTo>
    <relationshipLabel>TrackingHistories</relationshipLabel>
    <relationshipName>TrackingHistories</relationshipName>
    <type>Lookup</type>
</CustomField>

BPER/DEVF/force-app/main/default/objects/TrackingHistory__c/fields/NewValue__c.field-meta.xml
<CustomField>
    <fullName>NewValue__c</fullName>
    <encryptionScheme>None</encryptionScheme>
    <label>NewValue</label>
    <length>32768</length>
    <type>LongTextArea</type>
</CustomField>

BPER/DEVF/force-app/main/default/objects/TrackingHistory__c/fields/OldValue__c.field-meta.xml
<CustomField>
    <fullName>OldValue__c</fullName>
    <encryptionScheme>None</encryptionScheme>
    <label>OldValue</label>
    <length>32768</length>
    <type>LongTextArea</type>
</CustomField>

BPER/DEVF/force-app/main/default/objects/TrackingHistory__c/fields/ParentObject__c.field-meta.xml
<CustomField>
    <fullName>ParentObject__c</fullName>
    <description>Salesforce Id of the modified object</description>
    <encryptionScheme>None</encryptionScheme>
    <label>Parent Object</label>
    <length>18</length>
    <required>true</required>
    <type>Text</type>
</CustomField>

BPER/DEVF/force-app/main/default/objects/TrackingHistory__c/fields/Tracking_Field__c.field-meta.xml
<CustomField>
    <fullName>Tracking_Field__c</fullName>
    <description>API name of modified field</description>
    <encryptionScheme>None</encryptionScheme>
    <label>Tracking Field</label>
    <length>255</length>
    <required>true</required>
    <type>Text</type>
</CustomField>

BPER/DEVF/force-app/main/default/objects/TrackingHistory__c/recordTypes/Event.recordType-meta.xml
<RecordType>
    <fullName>Event</fullName>
    <active>true</active>
    <label>Event</label>
</RecordType>

BPER/DEVF/force-app/main/default/objects/TrackingHistoryConfiguration__mdt/TrackingHistoryConfiguration__mdt.object-meta.xml
<CustomObject>
    <label>TrackingHistoryConfiguration</label>
    <pluralLabel>TrackingHistoryConfigurations</pluralLabel>
</CustomObject>

BPER/DEVF/force-app/main/default/objects/TrackingHistoryConfiguration__mdt/fields/ObjectDevName__c.field-meta.xml
<CustomField>
    <fullName>ObjectDevName__c</fullName>
    <description>Object API name to track</description>
    <label>ObjectDevName</label>
    <length>255</length>
    <required>true</required>
    <type>Text</type>
</CustomField>

BPER/DEVF/force-app/main/default/objects/TrackingHistoryConfiguration__mdt/fields/ParentField__c.field-meta.xml
<CustomField>
    <fullName>ParentField__c</fullName>
    <description>API name of the field in which Id is saved</description>
    <label>ParentField</label>
    <length>255</length>
    <required>true</required>
    <type>Text</type>
</CustomField>

BPER/DEVF/force-app/main/default/objects/TrackingHistoryConfiguration__mdt/fields/RecordTypeDevName__c.field-meta.xml
<CustomField>
    <fullName>RecordTypeDevName__c</fullName>
    <description>Parent object record type developer name to track</description>
    <label>RecordTypeDevName</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

BPER/DEVF/force-app/main/default/objects/TrackingHistoryConfiguration__mdt/fields/TrackingFieldList__c.field-meta.xml
<CustomField>
    <fullName>TrackingFieldList__c</fullName>
    <description>Field API name list to track, separated by &quot;;&quot;</description>
    <label>TrackingFieldList</label>
    <length>255</length>
    <required>true</required>
    <type>Text</type>
</CustomField>

BPER/DEVF/force-app/main/default/classes/OnCRMAccountDetailTriggerHandler.cls
public with sharing class OnCRMAccountDetailTriggerHandler {

    public static Boolean trafficLightTrackingTrigger = false;

    public static void trackHistory(Map<Id, CRM_AccountDetail__c> oldTriggerAccountDetailMap, Map<Id, CRM_AccountDetail__c> newTriggerAccountDetailMap){
	
        //Get apiname of object (Event)
		String objApiName = String.valueOf(newTriggerAccountDetailMap.getSObjectType());
	
        //Get data information from metadata
		TrackingHistoryConfiguration__mdt[] metadataList = [SELECT ParentField__c, TrackingFieldList__c,
                                                            RecordTypeDevName__c, ObjectDevName__c
                                                            FROM TrackingHistoryConfiguration__mdt
                                                            WHERE ObjectDevName__c = :objApiName
                                                            LIMIT 1];
        
		if(metadataList.size() > 0 && !trafficLightTrackingTrigger){													
            TrackingHistoryConfiguration__mdt metadataObj = metadataList.get(0);
		
            //For each record, for each field to track, create a tracking object
            System.debug('Record type dettaglio: '+metadataObj.RecordTypeDevName__c);

            String recordTypeIdString = Schema.SObjectType.TrackingHistory__c.getRecordTypeInfosByDeveloperName().get(metadataObj.RecordTypeDevName__c).getRecordTypeId();
            List<String> trackingFieldList = metadataObj.TrackingFieldList__c.split(';');
            List<TrackingHistory__c> trackingObjectsList = new List<TrackingHistory__c>();
            TrackingHistory__c trackingObj; 

            for(CRM_AccountDetail__c newTriggerAccountDetail : newTriggerAccountDetailMap.values()){
                String trackingFields = '';
                String oldValue = '';
                String newValue = '';
                for(String tf : trackingFieldList){
                    trackingFields = trackingFields + ';' + tf;
                    if(oldTriggerAccountDetailMap.containsKey(newTriggerAccountDetail.Id)){
                        oldValue = oldValue + ';' + oldTriggerAccountDetailMap.get(newTriggerAccountDetail.Id).get(tf);
                    }
                    newValue = newValue + ';' + newTriggerAccountDetail.get(tf);
                }
                trackingFields = trackingFields.substring(1, trackingFields.length());
                if(!String.isBlank(oldValue)) oldValue = oldValue.substring(1, oldValue.length());
                newValue = newValue.substring(1, newValue.length());
				trackingObj = new TrackingHistory__c(
														RecordTypeId = recordTypeIdString,
														ParentObject__c = newTriggerAccountDetail.Id,
                                                        Cliente__c = newTriggerAccountDetail.CRM_Account__c,
														Tracking_Field__c = trackingFields,
														OldValue__c = oldValue,
														NewValue__c = newValue);

                trackingObjectsList.add(trackingObj);
			}
			
			insert trackingObjectsList;
        }
    }
}