BPER/DEVF/force-app/main/default/objects/NDGManagementMember__c/NDGManagementMember__c.object-meta.xml
<CustomObject>
    <label>Referente NDG</label>
    <nameField>
        <displayFormat>{0000}</displayFormat>
        <label>Referente NDG Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Referenti NDG</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

BPER/DEVF/force-app/main/default/objects/NDGManagementMember__c/fields/PTF_ModelloDiServizio__c.field-meta.xml
<CustomField>
    <fullName>PTF_ModelloDiServizio__c</fullName>
    <formula>TEXT(PTF_NDG__r.ModelloDiServizio__c)</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>Macro-modello di servizio</label>
    <type>Text</type>
</CustomField>

BPER/DEVF/force-app/main/default/objects/NDGManagementMember__c/fields/PTF_NDG__c.field-meta.xml
<CustomField>
    <fullName>PTF_NDG__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Nome NDG</label>
    <referenceTo>Account</referenceTo>
    <relationshipLabel>Referenti NDG</relationshipLabel>
    <relationshipName>Storico_Referenti_NDG</relationshipName>
    <type>Lookup</type>
</CustomField>

BPER/DEVF/force-app/main/default/objects/NDGManagementMember__c/recordTypes/DoppioPresidio.recordType-meta.xml
<RecordType>
    <fullName>DoppioPresidio</fullName>
    <active>true</active>
    <label>Doppio Presidio</label>
</RecordType>

BPER/DEVF/force-app/main/default/objects/Wallet__c/Wallet__c.object-meta.xml
<CustomObject>
    <label>Portafoglio</label>
    <nameField>
        <encryptionScheme>None</encryptionScheme>
        <label>Wallet Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Portafogli</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

BPER/DEVF/force-app/main/default/objects/Wallet__c/fields/PTF_ModelloDiServizio__c.field-meta.xml
<CustomField>
    <fullName>PTF_ModelloDiServizio__c</fullName>
    <label>Macro-modello di servizio</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetName>Modelli_di_Servizio</valueSetName>
    </valueSet>
</CustomField>

BPER/POLOWEALTH/force-app/main/default/classes/DoppiPresidiSetEndDateControllerTest.cls
@isTest
private class DoppiPresidiSetEndDateControllerTest {
    
    @isTest
    static void unitTest() {
        Wallet__c ptf = new Wallet__c(PTF_ModelloDiServizio__c='Private');
        insert ptf;
        Account acc = AllDataFactory.getAccount('01', 'Banca');
        acc.PTF_Portafoglio__c = ptf.Id;
        insert acc;
        String recTypeId = SV_Utilities.getRecordTypeByDeveloperName('NDGManagementMember__c','DoppioPresidio');
        NDGManagementMember__c ndgman = new NDGManagementMember__c();
        insert ndgman;
        NDGManagementMember__c ndgman2 = new NDGManagementMember__c(RecordTypeId=recTypeId,PTF_NDG__c=acc.Id);
        insert ndgman2;
        Test.startTest();
        DoppiPresidiSetEndDateController.updateFlagDoppiPresidi(ndgman.Id, null);
        try {
            DoppiPresidiSetEndDateController.updateFlagDoppiPresidi(ndgman2.Id, acc.Id);
        }
        catch(Exception exc) {}
        Test.stopTest();
        System.assertEquals(false, (DoppiPresidiSetEndDateController.updateFlagDoppiPresidi(ndgman.Id, null)));
    }
}