BPER/DEVF/force-app/main/default/objects/CRM_Assenze__c/CRM_Assenze__c.object-meta.xml
<CustomObject>
    <label>Assenze</label>
    <nameField>
        <displayFormat>F-{000000}</displayFormat>
        <label>Ferie Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Assenze</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

BPER/DEVF/force-app/main/default/objects/CRM_Assenze__c/fields/CRM_SyncGenesys__c.field-meta.xml
<CustomField>
    <fullName>CRM_SyncGenesys__c</fullName>
    <defaultValue>false</defaultValue>
    <label>Sync Genesys</label>
    <type>Checkbox</type>
</CustomField>

BPER/DEVF/force-app/main/default/objects/CRM_Assenze__c/fields/CRM_User__c.field-meta.xml
<CustomField>
    <fullName>CRM_User__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>User</label>
    <referenceTo>User</referenceTo>
    <relationshipName>Ferie</relationshipName>
    <type>Lookup</type>
</CustomField>

BPER/PROD/force-app/main/default/classes/CC_retryAssenzeFailed.cls
global class CC_retryAssenzeFailed implements Schedulable {
    global void execute(SchedulableContext sc) {
        // Esegui la query per ottenere gli ID desiderati dalla CRM_Assenze__c
        Set<Id> assenzeIds = new Set<Id>();
        for (CRM_Assenze__c assenza : [SELECT Id
                                        FROM CRM_Assenze__c
                                        WHERE CRM_User__r.CRM_BusinessUnitID__c != null
                                        AND CRM_SyncGenesys__c = false]) {
            assenzeIds.add(assenza.Id);
        }
        
        // Chiamare il metodo runBatch dalla classe Batch_onAssenzeTriggerHandler
        Batch_onAssenzeTriggerHandler.runBatch(assenzeIds);
    }
}