BPER/DEVF/force-app/main/default/objects/CRM_Assenze__c/CRM_Assenze__c.object-meta.xml
<CustomObject>
    <label>Assenze</label>
    <nameField>
        <displayFormat>F-{000000}</displayFormat>
        <label>Ferie Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Assenze</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

BPER/DEVF/force-app/main/default/objects/CRM_Assenze__c/fields/CRM_IdGenesys__c.field-meta.xml
<CustomField>
    <fullName>CRM_IdGenesys__c</fullName>
    <encryptionScheme>None</encryptionScheme>
    <label>IdGenesys</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

BPER/DEVF/force-app/main/default/objects/CRM_Assenze__c/fields/CRM_SyncGenesysDelete__c.field-meta.xml
<CustomField>
    <fullName>CRM_SyncGenesysDelete__c</fullName>
    <defaultValue>false</defaultValue>
    <label>Sync Genesys Delete</label>
    <type>Checkbox</type>
</CustomField>

BPER/BCUSTOMER/force-app/main/default/classes/Batch_onAssenzeDeleteTriggerHandlerTest.cls
@isTest
public with sharing class Batch_onAssenzeDeleteTriggerHandlerTest {
    @isTest
    static void testBatch() {
        CRM_Assenze__c testAssenza = new CRM_Assenze__c();
        testAssenza.CRM_SyncGenesysDelete__c = true; 
        insert testAssenza;

        Set<Id> testIds = new Set<Id>();
        testIds.add(testAssenza.Id);

        Test.startTest();
        Batch_onAssenzeDeleteTriggerHandler.runBatch(testIds);
        Test.stopTest();
    }

    @isTest
    static void testExecuteMethod() {
        // Crea dati di test per il batch
        List<CRM_Assenze__c> testScope = new List<CRM_Assenze__c>();
        for (Integer i = 0; i < 10; i++) {
            CRM_Assenze__c assenza = new CRM_Assenze__c(
                CRM_IdGenesys__c = 'test' + i
            );
            testScope.add(assenza);
        }
        insert testScope;
        
        Set<Id> testScopeIds = new Set<Id>();
        for (CRM_Assenze__c assenza : testScope) {
            testScopeIds.add(assenza.Id);
        }
        
        Batch_onAssenzeDeleteTriggerHandler batchHandler = new Batch_onAssenzeDeleteTriggerHandler(testScopeIds);
        Test.startTest();
        batchHandler.execute(null, testScope);
        Test.stopTest();
        
        
    }
}