BPER/DEVF/force-app/main/default/objects/CCOpportunityMatch__mdt/CCOpportunityMatch__mdt.object-meta.xml
<CustomObject>
    <label>Contact Center Opportunity Match</label>
    <pluralLabel>Contact Center Opportunity Matches</pluralLabel>
</CustomObject>

BPER/DEVF/force-app/main/default/objects/CCOpportunityMatch__mdt/fields/Assegnatario__c.field-meta.xml
<CustomField>
    <fullName>Assegnatario__c</fullName>
    <label>Assegnatario</label>
    <length>255</length>
    <required>true</required>
    <type>Text</type>
</CustomField>

BPER/DEVF/force-app/main/default/objects/CCOpportunityMatch__mdt/fields/Esito__c.field-meta.xml
<CustomField>
    <fullName>Esito__c</fullName>
    <label>Esito</label>
    <required>true</required>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Accettata</fullName>
                <default>true</default>
                <label>Accettata</label>
            </value>
            <value>
                <fullName>Rifiutata</fullName>
            </value>
            <value>
                <fullName>Non raggiungibile</fullName>
            </value>
            <value>
                <fullName>Inviata Filiale</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

BPER/DEVF/force-app/main/default/objects/CCOpportunityMatch__mdt/fields/Prodotto__c.field-meta.xml
<CustomField>
    <fullName>Prodotto__c</fullName>
    <label>Prodotto</label>
    <length>255</length>
    <required>true</required>
    <type>Text</type>
</CustomField>

BPER/DEVF/force-app/main/default/objects/CCOpportunityMatch__mdt/fields/StessoAssegnatario__c.field-meta.xml
<CustomField>
    <fullName>StessoAssegnatario__c</fullName>
    <defaultValue>false</defaultValue>
    <label>Stesso Assegnatario</label>
    <type>Checkbox</type>
</CustomField>

BPER/DEVF/force-app/main/default/objects/SV_FailedRequest__c/SV_FailedRequest__c.object-meta.xml
<CustomObject>
    <label>Failed Request</label>
    <nameField>
        <displayFormat>FR_{0000000}</displayFormat>
        <label>Failed Request Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Failed Requests</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

BPER/DEVF/force-app/main/default/objects/SV_FailedRequest__c/fields/CertificationName__c.field-meta.xml
<CustomField>
    <fullName>CertificationName__c</fullName>
    <encryptionScheme>None</encryptionScheme>
    <label>Certification Name</label>
    <length>255</length>
    <required>true</required>
    <type>Text</type>
</CustomField>

BPER/DEVF/force-app/main/default/objects/SV_FailedRequest__c/fields/FieldsMap__c.field-meta.xml
<CustomField>
    <fullName>FieldsMap__c</fullName>
    <encryptionScheme>None</encryptionScheme>
    <label>FieldsMap</label>
    <length>32768</length>
    <type>LongTextArea</type>
</CustomField>

BPER/DEVF/force-app/main/default/objects/SV_FailedRequest__c/fields/RecordId__c.field-meta.xml
<CustomField>
    <fullName>RecordId__c</fullName>
    <encryptionScheme>None</encryptionScheme>
    <label>Record Id</label>
    <length>255</length>
    <required>true</required>
    <type>Text</type>
</CustomField>

BPER/DEVF/force-app/main/default/objects/SV_FailedRequest__c/fields/RequestName__c.field-meta.xml
<CustomField>
    <fullName>RequestName__c</fullName>
    <encryptionScheme>None</encryptionScheme>
    <label>Request Name</label>
    <length>255</length>
    <required>true</required>
    <type>Text</type>
</CustomField>

BPER/DEVF/force-app/main/default/objects/TrackingHistory__c/TrackingHistory__c.object-meta.xml
<CustomObject>
    <description>Object to track changes</description>
    <label>TrackingHistory</label>
    <nameField>
        <displayFormat>TH-{00000000}</displayFormat>
        <label>TrackingHistory Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>TrackingHistories</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

BPER/DEVF/force-app/main/default/objects/TrackingHistory__c/fields/Cliente__c.field-meta.xml
<CustomField>
    <fullName>Cliente__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Cliente</label>
    <referenceTo>Account</referenceTo>
    <relationshipLabel>TrackingHistories</relationshipLabel>
    <relationshipName>TrackingHistories</relationshipName>
    <type>Lookup</type>
</CustomField>

BPER/DEVF/force-app/main/default/objects/TrackingHistory__c/fields/NewValue__c.field-meta.xml
<CustomField>
    <fullName>NewValue__c</fullName>
    <encryptionScheme>None</encryptionScheme>
    <label>NewValue</label>
    <length>32768</length>
    <type>LongTextArea</type>
</CustomField>

BPER/DEVF/force-app/main/default/objects/TrackingHistory__c/fields/OldValue__c.field-meta.xml
<CustomField>
    <fullName>OldValue__c</fullName>
    <encryptionScheme>None</encryptionScheme>
    <label>OldValue</label>
    <length>32768</length>
    <type>LongTextArea</type>
</CustomField>

BPER/DEVF/force-app/main/default/objects/TrackingHistory__c/fields/ParentObject__c.field-meta.xml
<CustomField>
    <fullName>ParentObject__c</fullName>
    <description>Salesforce Id of the modified object</description>
    <encryptionScheme>None</encryptionScheme>
    <label>Parent Object</label>
    <length>18</length>
    <required>true</required>
    <type>Text</type>
</CustomField>

BPER/DEVF/force-app/main/default/objects/TrackingHistory__c/fields/Tracking_Field__c.field-meta.xml
<CustomField>
    <fullName>Tracking_Field__c</fullName>
    <description>API name of modified field</description>
    <encryptionScheme>None</encryptionScheme>
    <label>Tracking Field</label>
    <length>255</length>
    <required>true</required>
    <type>Text</type>
</CustomField>

BPER/DEVF/force-app/main/default/objects/TrackingHistory__c/fields/Tracking_ObjRecordType__c.field-meta.xml
<CustomField>
    <fullName>Tracking_ObjRecordType__c</fullName>
    <encryptionScheme>None</encryptionScheme>
    <label>Tracking ObjRecordType</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

BPER/DEVF/force-app/main/default/objects/TrackingHistory__c/recordTypes/Event.recordType-meta.xml
<RecordType>
    <fullName>Event</fullName>
    <active>true</active>
    <label>Event</label>
</RecordType>

BPER/DEVF/force-app/main/default/objects/TrackingHistory__c/recordTypes/Opportunity.recordType-meta.xml
<RecordType>
    <fullName>Opportunity</fullName>
    <active>true</active>
    <label>Opportunity_Self</label>
</RecordType>

BPER/DEVF/force-app/main/default/objects/TrackingHistoryConfiguration__mdt/TrackingHistoryConfiguration__mdt.object-meta.xml
<CustomObject>
    <label>TrackingHistoryConfiguration</label>
    <pluralLabel>TrackingHistoryConfigurations</pluralLabel>
</CustomObject>

BPER/DEVF/force-app/main/default/objects/TrackingHistoryConfiguration__mdt/fields/ObjectDevName__c.field-meta.xml
<CustomField>
    <fullName>ObjectDevName__c</fullName>
    <description>Object API name to track</description>
    <label>ObjectDevName</label>
    <length>255</length>
    <required>true</required>
    <type>Text</type>
</CustomField>

BPER/DEVF/force-app/main/default/objects/TrackingHistoryConfiguration__mdt/fields/ParentField__c.field-meta.xml
<CustomField>
    <fullName>ParentField__c</fullName>
    <description>API name of the field in which Id is saved</description>
    <label>ParentField</label>
    <length>255</length>
    <required>true</required>
    <type>Text</type>
</CustomField>

BPER/DEVF/force-app/main/default/objects/TrackingHistoryConfiguration__mdt/fields/RecordTypeDevName__c.field-meta.xml
<CustomField>
    <fullName>RecordTypeDevName__c</fullName>
    <description>Parent object record type developer name to track</description>
    <label>RecordTypeDevName</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

BPER/DEVF/force-app/main/default/objects/TrackingHistoryConfiguration__mdt/fields/TrackingFieldList__c.field-meta.xml
<CustomField>
    <fullName>TrackingFieldList__c</fullName>
    <description>Field API name list to track, separated by &quot;;&quot;</description>
    <label>TrackingFieldList</label>
    <length>255</length>
    <required>true</required>
    <type>Text</type>
</CustomField>

BPER/POLOWEALTH/force-app/main/default/classes/OnOpportunityTriggerHandler.cls
public class OnOpportunityTriggerHandler {
    /*
    public static void publishEvent(List<Opportunity> records, Map<Id,Opportunity> oldMap){
        List<OpportunityDataTableEvent__e> eventList = new List<OpportunityDataTableEvent__e>();
        for(Opportunity o:records){
            OpportunityDataTableEvent__e event = new OpportunityDataTableEvent__e();
            event.OpportunityId__c=o.Id;
            event.UserId__c=UserInfo.getUserId();
            eventList.add(event);
        }
        EventBus.publish(eventList);
    }*/

    public static Boolean trafficLightTrackingTrigger = false;

    public static Set<String> ccOppMatchSet {
        get{

            if(ccOppMatchSet != null){
                return ccOppMatchSet;
            }
            ccOppMatchSet = new Set<String>();
            List<CCOpportunityMatch__mdt> ccOppMatch = [SELECT id, Prodotto__c, Esito__c, Assegnatario__c, StessoAssegnatario__c FROM CCOpportunityMatch__mdt];
            ccOppMatchSet.addAll(SV_Utilities.keyBy(ccOppMatch, '{Prodotto__c}_{Esito__c}_{Assegnatario__c}', true).keySet());
            for(CCOpportunityMatch__mdt ccOpportunityMatch : ccOppMatch){
                if(ccOpportunityMatch.StessoAssegnatario__c){
                    ccOppMatchSet.add(ccOpportunityMatch.Prodotto__c + '_' + ccOpportunityMatch.Esito__c + '_true');
                }
            }
            System.debug('DK ccOppMatchSet: ' + JSON.serialize(ccOppMatchSet));
            return ccOppMatchSet;
        }set;
    }

    public static void makeCallOpportunity(Map<Id,sObject> oldOptMap, Map<Id,sObject> newOptMap){

        List<Id> oppCallIdList = new List<Id>();
        List<Id> oppCCMatched = new List<Id>();

        Map<String, SObject> ownerOppMap = SV_Utilities.keyBy(newOptMap.values(), 'OwnerId');
        Map<String, SOBject> userMap = SV_Utilities.keyBy([SELECT id, Name FROM USer WHERE id IN: ownerOppMap.keySet()], 'Id');

        for(Id oppId : newOptMap.keyset()){
            String requestMatch = (String)newOptMap.get(oppId).get('CRM_ProductCategory__c') + '_' + (String)newOptMap.get(oppId).get('StageName');
            System.debug('DK requestMatch: ' + requestMatch);
            System.debug('DK userMap.get(newOptMap.get(oppId).OwnerId).get(): ' + (String)userMap.get((String)newOptMap.get(oppId).get('OwnerId')).get('Name'));
            if((String)newOptMap.get(oppId).get('RecordTypeId') == SV_Utilities.getRecordTypeByDeveloperName('Opportunity', 'Opportunita_da_cc_vs_rete') &&
                (String)newOptMap.get(oppId).get('StageName') == 'In corso' && 
                !System.isFuture()){
                oppCallIdList.add(oppId);
            }
            
            if(ccOppMatchSet.contains(requestMatch + '_' + (String)userMap.get((String)newOptMap.get(oppId).get('OwnerId')).get('Name')) ||
                ccOppMatchSet.contains(requestMatch + '_Tutti') ||
                ccOppMatchSet.contains(requestMatch + '_' + (UserInfo.getUserId() == (String)newOptMap.get(oppId).get('OwnerId')))){

                oppCCMatched.add(oppId);
            }
        }

        if(oppCallIdList.size()>0){
            
            for(Id oppId :oppCallIdList){

                sendRequest(oppId, 'notificaStatoProcesso');
            }
        }

        if(oppCCMatched.size()>0){
            
            for(Id oppId :oppCCMatched){

                sendRequest(oppId, 'inserisciEventoContactCenter_Opp');
            }
        }
    }

    @future(callout=true)
    public static void sendRequest(Id recordId, String request){

        StaticResource staticResource = [select id,body from StaticResource Where Name = 'jsonWrapper'];
        String jsonWrapper = staticResource.body.toString();
        Map<String, Map<String, Object>> fieldsMap = new Map<String, Map<String, Object>>();
        Map<String, Map<String, String>> conditionMap = new Map<String, Map<String, String>>();
        Map<String,Object> parsedJsonWrapper = (Map<String,Object>)JSON.deserializeUntyped(jsonWrapper);
        Map<String,Object> parsedJsonElement = (Map<String,Object>)JSON.deserializeUntyped(JSON.serialize(parsedJsonWrapper.get(request)));
        Map<String, Object> parsedJsonElementFields = (Map<String, Object>)JSON.deserializeUntyped(JSON.serialize(parsedJsonElement.get('fields')));
        for(String fieldName : parsedJsonElementFields.keySet()){

            fieldsMap.put(fieldName, (Map<String, Object>)JSON.deserializeUntyped(JSON.serialize(parsedJsonElementFields.get(fieldName))));
        }
            
        Map<String, Object> response = (Map<String, Object>)JSON.deserializeUntyped(MakeRequestController.makeRequest(request, recordId, fieldsMap, null, 'salesforceprodclient2024', '',false));
        System.debug('DK response: ' + response);
        if((String)response.get('statusCode') != '204' && request == 'inserisciEventoContactCenter_Opp'){

            insert new SV_FailedRequest__c(RequestName__c = request,
                                RecordId__c = recordId,
                                FieldsMap__c = JSON.serialize(fieldsMap),
                                CertificationName__c = 'salesforceprodclient2024');
        }
    }

    public static void trackHistory(Map<Id, Opportunity> oldTriggerOpportunityMap, Map<Id, Opportunity> newTriggerOpportunityMap){
    
        //Get apiname of object (Opportunity)
        String objApiName = String.valueOf(newTriggerOpportunityMap.getSObjectType());
    
        //Get data information from metadata
        TrackingHistoryConfiguration__mdt[] metadataList = [SELECT ParentField__c, TrackingFieldList__c,
                                                            RecordTypeDevName__c, ObjectDevName__c
                                                            FROM TrackingHistoryConfiguration__mdt
                                                            WHERE ObjectDevName__c = :objApiName
                                                            LIMIT 1];
        
        if(metadataList.size() > 0 && !trafficLightTrackingTrigger){                                                    
            TrackingHistoryConfiguration__mdt metadataObj = metadataList.get(0);
        
            //For each record, for each field to track, create a tracking object
            String recordTypeIdString = Schema.SObjectType.TrackingHistory__c.getRecordTypeInfosByDeveloperName().get(metadataObj.RecordTypeDevName__c).getRecordTypeId();
            List<String> trackingFieldList = metadataObj.TrackingFieldList__c.split(';');
            List<TrackingHistory__c> trackingObjects = new List<TrackingHistory__c>();
            
            for(Opportunity newTriggerOpportunity : newTriggerOpportunityMap.values()){
                for(String trackingField : trackingFieldList){
                    String oldValue;
                    String newValue = (String) newTriggerOpportunity.get(trackingField);
                    
                    if(!(oldTriggerOpportunityMap == null || oldTriggerOpportunityMap.isEmpty())){
                        Opportunity oldTriggerOpportunity = oldTriggerOpportunityMap.get(newTriggerOpportunity.id);
                        oldValue = (String) oldTriggerOpportunity.get(trackingField);
                    }

                    if((!String.isBlank(newValue) && String.isBlank(oldValue)) || (!String.isBlank(newValue) && !String.isBlank(oldValue) && !(newValue.equals(oldValue)))){
                        TrackingHistory__c trackingObj = new TrackingHistory__c(
                                                        RecordTypeId = recordTypeIdString,
                                                        ParentObject__c = newTriggerOpportunity.Id,
                                                        Cliente__c = newTriggerOpportunity.AccountId,
                                                        Tracking_Field__c = trackingField,
                                                        Tracking_ObjRecordType__c = Schema.SObjectType.Opportunity.getRecordTypeInfosById().get(newTriggerOpportunity.RecordTypeId).getDeveloperName(),
                                                        OldValue__c = oldValue,
                                                        NewValue__c = newValue);
                        //get dynamically the field API name which contains the record id from metadata
                        trackingObj.put(metadataObj.ParentField__c, newTriggerOpportunity.id);
                        
                        trackingObjects.add(trackingObj);
                    }

                }
            }
            
            insert trackingObjects;
        }
        
        
    }
    
    public static void populateAccountId(List<Opportunity> newTriggerOpportunity){
        List<Id> listContId = new List<Id>();
        List<Opportunity> listOptItem = new List<Opportunity>();
        for(Opportunity optTemp : newTriggerOpportunity){
            if(optTemp.AccountId == null){
                listContId.add(optTemp.ContactId);
                listOptItem.add(optTemp);
            }
        }
        System.debug('listContId: '+listContId.size());
        System.debug('listOptItem: '+listOptItem.size());
        
        Map<Id,Contact> mapOptCont = new Map <Id,Contact>([Select id, accountId FROM Contact where ID IN :listContId]);
        System.debug('listOptItem: '+mapOptCont.size());
            
        for(Opportunity optTemp : listOptItem){
                optTemp.accountId = mapOptCont.get(optTemp.ContactId).AccountId;
            }
        
    }
}