BPER/DEVF/force-app/main/default/objects/connector_load_schedule_event__e/connector_load_schedule_event__e.object-meta.xml
<CustomObject>
    <label>connector load schedule event</label>
    <pluralLabel>connector load schedule events</pluralLabel>
</CustomObject>

BPER/DEVF/force-app/main/default/objects/connector_load_schedule_event__e/fields/schedule__c.field-meta.xml
<CustomField>
    <fullName>schedule__c</fullName>
    <label>schedule</label>
    <length>32768</length>
    <type>LongTextArea</type>
</CustomField>

BPER/DEVF/force-app/main/default/objects/GenesysSetting__c/GenesysSetting__c.object-meta.xml
<CustomObject>
    <label>Genesys Setting</label>
    <nameField>
        <encryptionScheme>None</encryptionScheme>
        <label>Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Genesys Settings</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

BPER/DEVF/force-app/main/default/objects/GenesysSetting__c/fields/G_MEDIA_TYPE__c.field-meta.xml
<CustomField>
    <fullName>G_MEDIA_TYPE__c</fullName>
    <label>Media Type</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>chat</fullName>
            </value>
            <value>
                <fullName>whatsapp</fullName>
            </value>
            <value>
                <fullName>other</fullName>
            </value>
            <value>
                <fullName>web</fullName>
            </value>
            <value>
                <fullName>unbluchat</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

BPER/DEVF/force-app/main/default/objects/GenesysSetting__c/fields/G_QUEUE_ID__c.field-meta.xml
<CustomField>
    <fullName>G_QUEUE_ID__c</fullName>
    <encryptionScheme>None</encryptionScheme>
    <label>ID Coda</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

BPER/DEVF/force-app/main/default/objects/GenesysSetting__c/fields/G_SCHEDULE_GROUP_ID__c.field-meta.xml
<CustomField>
    <fullName>G_SCHEDULE_GROUP_ID__c</fullName>
    <encryptionScheme>None</encryptionScheme>
    <label>ID Scheduling Group Chat</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

BPER/DEVF/force-app/main/default/objects/GenesysSetting__c/fields/S_MESSAGES_TIMEOUT__c.field-meta.xml
<CustomField>
    <fullName>S_MESSAGES_TIMEOUT__c</fullName>
    <encryptionScheme>None</encryptionScheme>
    <label>Timeout Sessione Messaging</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

BPER/DEVF/force-app/main/default/objects/GenesysSetting__c/fields/S_OMNI_ID__c.field-meta.xml
<CustomField>
    <fullName>S_OMNI_ID__c</fullName>
    <encryptionScheme>None</encryptionScheme>
    <label>ID Presence Status Ready</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

BPER/DEVF/force-app/main/default/objects/GenesysSetting__c/recordTypes/Chat.recordType-meta.xml
<RecordType>
    <fullName>Chat</fullName>
    <active>true</active>
    <label>Chat</label>
</RecordType>

BPER/CIB/force-app/main/default/classes/ConnectorMessagesEventPublish.cls
public with sharing class ConnectorMessagesEventPublish {
    @AuraEnabled(cacheable=false)
    public static void createMessagesEvent(){
   	  JSONGenerator gen = JSON.createGenerator(true);
        try{
            List<GenesysSetting__c> queues = [select id,G_MEDIA_TYPE__c, G_QUEUE_ID__c, G_SCHEDULE_GROUP_ID__c,S_MESSAGES_TIMEOUT__c, S_OMNI_ID__c  from GenesysSetting__c ];
            System.debug('queues : ' + queues);
            gen.writeStartObject();
            for ( GenesysSetting__c q : queues){
               
                System.debug('writing field name : ' + q.G_QUEUE_ID__c);
                  gen.writeFieldName(q.G_QUEUE_ID__c);
                  gen.writeStartObject();  
                System.debug('writing field name : ' + q.G_MEDIA_TYPE__c);
                  gen.writeFieldName(q.G_MEDIA_TYPE__c);
                  gen.writeObject(q);
               
                 if ( q.G_MEDIA_TYPE__c == 'chat' ){               
                  Map<String, Object> schedule = ConnectorScheduleBuilder.loadSchedule(q.G_SCHEDULE_GROUP_ID__c);
                  System.debug('schedule : ' + schedule);
                  gen.writeFieldName('chatSchedule');
                  gen.writeObject(schedule);
                }
                 gen.writeEndObject();
            }
           
            System.debug('payload : ' + gen.getAsString());
        }catch( Exception e ){
            System.debug('error building schedule : ' + e);
            gen = JSON.createGenerator(true);
             gen.writeStartObject();
             gen.writeEndObject();
        }
        // gen.writeEndObject();
        connector_load_schedule_event__e cls = new connector_load_schedule_event__e(schedule__c=gen.getAsString());
        EventBus.publish(cls);
    }
    
    
}