BPER/DEVF/force-app/main/default/objects/CRM_AccountAccountJointOwnershipRelation__c/CRM_AccountAccountJointOwnershipRelation__c.object-meta.xml
<CustomObject>
    <label>Relazione di cointestazione</label>
    <nameField>
        <displayFormat>RDC - {00000000}</displayFormat>
        <label>Nome AccountAccountJointOwnership Relati</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Relazioni di cointestazione</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

BPER/DEVF/force-app/main/default/objects/CRM_AccountAccountJointOwnershipRelation__c/fields/CRM_Account__c.field-meta.xml
<CustomField>
    <fullName>CRM_Account__c</fullName>
    <deleteConstraint>Restrict</deleteConstraint>
    <label>Account</label>
    <referenceTo>Account</referenceTo>
    <relationshipLabel>Relazioni di cointestazione (Account)</relationshipLabel>
    <relationshipName>AccountContactJointOwnershipRelations1</relationshipName>
    <required>true</required>
    <type>Lookup</type>
</CustomField>

BPER/DEVF/force-app/main/default/objects/CRM_AccountAccountJointOwnershipRelation__c/fields/CRM_Active__c.field-meta.xml
<CustomField>
    <fullName>CRM_Active__c</fullName>
    <defaultValue>false</defaultValue>
    <label>Active</label>
    <type>Checkbox</type>
</CustomField>

BPER/DEVF/force-app/main/default/objects/CRM_AccountAccountJointOwnershipRelation__c/fields/CRM_JointOwnership__c.field-meta.xml
<CustomField>
    <fullName>CRM_JointOwnership__c</fullName>
    <deleteConstraint>Restrict</deleteConstraint>
    <label>Joint Ownership</label>
    <lookupFilter>
        <active>true</active>
        <filterItems>
            <field>Account.RecordType.DeveloperName</field>
            <operation>equals</operation>
            <value>Cointestazione</value>
        </filterItems>
        <isOptional>false</isOptional>
    </lookupFilter>
    <referenceTo>Account</referenceTo>
    <relationshipName>AccountContactJointOwnershipRelations</relationshipName>
    <required>true</required>
    <type>Lookup</type>
</CustomField>

BPER/DEVF/force-app/main/default/objects/CRM_AccountAccountJointOwnershipRelation__c/fields/CRM_PrimaryNDG__c.field-meta.xml
<CustomField>
    <fullName>CRM_PrimaryNDG__c</fullName>
    <defaultValue>false</defaultValue>
    <label>Primary NDG</label>
    <type>Checkbox</type>
</CustomField>

BPER/DEVF/force-app/main/default/objects/CRM_IndicatoriCliente__c/CRM_IndicatoriCliente__c.object-meta.xml
<CustomObject>
    <description>Indicatori Commerciali, Economici, Reddituali e di Rischio di un cliente</description>
    <label>Indicatori Cliente</label>
    <nameField>
        <encryptionScheme>None</encryptionScheme>
        <label>Indicatori Cliente Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Indicatori Clienti</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

BPER/DEVF/force-app/main/default/objects/CRM_IndicatoriCliente__c/fields/CRM_Account__c.field-meta.xml
<CustomField>
    <fullName>CRM_Account__c</fullName>
    <deleteConstraint>Restrict</deleteConstraint>
    <label>Nome Cliente</label>
    <referenceTo>Account</referenceTo>
    <relationshipName>Rischio</relationshipName>
    <type>Lookup</type>
</CustomField>

BPER/DEVF/force-app/main/default/objects/CRM_IndicatoriCliente__c/recordTypes/Flat.recordType-meta.xml
<RecordType>
    <fullName>Flat</fullName>
    <active>true</active>
    <label>Flat</label>
</RecordType>

BPER/DEV/force-app/main/default/classes/CRM_EconomicIndicatorController.cls
public with sharing class CRM_EconomicIndicatorController {

    @AuraEnabled
    public static User getUserInfo() {
        return [ SELECT Id, Name FROM User WHERE Id =: UserInfo.getUserId() ];
        
    }

    @AuraEnabled
    public static Account getAccountData(String accId) {
        Account acc = [SELECT id, 
                        CRM_NDG__c,
                        Name
                        FROM Account
                        WHERE Id =: accId];
        return acc;
    }



    @AuraEnabled
    public static Map<String,SObject> getRelazioniAccount(String accId) {
        Map<String,SObject> resultMap = SV_Utilities.keyBy([SELECT id, 
                                                    CRM_Account__c,
                                                    CRM_Account__r.CRM_NDG__c,
                                                    CRM_Account__r.Name,
                                                    CRM_JointOwnership__c,
                                                    CRM_JointOwnership__r.CRM_NDG__c,
                                                    CRM_JointOwnership__r.Name,
                                                    CRM_Active__c
                                                    FROM CRM_AccountAccountJointOwnershipRelation__c
                                                    WHERE CRM_Account__c =: accId 
                                                    AND CRM_PrimaryNDG__c = false ], '{CRM_Account__c}_{CRM_JointOwnership__c}', true);
        
        return resultMap;
    }

    @AuraEnabled
    public static Map<String,Sobject> getCointestazioni(List<String> accIdList){
        Map<String,SObject> resultMap = SV_Utilities.keyBy([SELECT count(id) numeroCointestatari, 
                                                    CRM_JointOwnership__c 
                                                    FROM CRM_AccountAccountJointOwnershipRelation__c 
                                                    WHERE CRM_JointOwnership__c IN:accIdList 
                                                    AND CRM_Active__c = true 
                                                    AND CRM_PrimaryNDG__c = false 
                                                    GROUP BY CRM_JointOwnership__c ], 'CRM_JointOwnership__c', false);
        return resultMap;
    }



    @AuraEnabled
    public static Map<String,Sobject> getIndicatoriCliente(List<String> accIdList){
        Map<String,SObject> resultMap = new Map<String,SObject>();
        String query = String.escapeSingleQuotes(SV_Utilities.selectAllField('CRM_IndicatoriCliente__c'));
        query += ' WHERE  CRM_Account__c  IN: accIdList and RecordType.Developername = \'FLAT\'';

        List<Sobject> slist = Database.query(query);

        System.debug('GB ObjRecord '+slist);
        for(Sobject so : slist){ resultMap.put((String)so.get('CRM_Account__c'),so); }

        return resultMap;
    }

    @AuraEnabled
    public static Map<String,Sobject> getIndicatoriPF(String accId){
        Map<String,SObject> resultMap = new Map<String,SObject>();
        String query = String.escapeSingleQuotes(SV_Utilities.selectAllField('CRM_IndicatoriCliente__c'));
        query += ' WHERE  CRM_Account__c  =: accId and RecordType.Developername = \'FLAT\'';

        List<Sobject> slist = Database.query(query);

        System.debug('GB ObjRecord '+slist);
        for(Sobject so : slist){ resultMap.put((String)so.get('CRM_Account__c'),so); }
        return resultMap;
    }

}