BPER/DEVF/force-app/main/default/objects/CRM_CustomerInterview__c/CRM_CustomerInterview__c.object-meta.xml
<CustomObject>
    <label>Check Up</label>
    <nameField>
        <encryptionScheme>None</encryptionScheme>
        <label>Check-up</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Check Up</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

BPER/DEVF/force-app/main/default/objects/CRM_CustomerInterview__c/fields/CRM_Customer__c.field-meta.xml
<CustomField>
    <fullName>CRM_Customer__c</fullName>
    <label>Cliente</label>
    <referenceTo>Account</referenceTo>
    <relationshipName>Interviews</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

BPER/DEVF/force-app/main/default/objects/TrackingHistory__c/TrackingHistory__c.object-meta.xml
<CustomObject>
    <description>Object to track changes</description>
    <label>TrackingHistory</label>
    <nameField>
        <displayFormat>TH-{00000000}</displayFormat>
        <label>TrackingHistory Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>TrackingHistories</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

BPER/DEVF/force-app/main/default/objects/TrackingHistory__c/fields/Cliente__c.field-meta.xml
<CustomField>
    <fullName>Cliente__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Cliente</label>
    <referenceTo>Account</referenceTo>
    <relationshipLabel>TrackingHistories</relationshipLabel>
    <relationshipName>TrackingHistories</relationshipName>
    <type>Lookup</type>
</CustomField>

BPER/DEVF/force-app/main/default/objects/TrackingHistory__c/fields/NewValue__c.field-meta.xml
<CustomField>
    <fullName>NewValue__c</fullName>
    <encryptionScheme>None</encryptionScheme>
    <label>NewValue</label>
    <length>32768</length>
    <type>LongTextArea</type>
</CustomField>

BPER/DEVF/force-app/main/default/objects/TrackingHistory__c/fields/OldValue__c.field-meta.xml
<CustomField>
    <fullName>OldValue__c</fullName>
    <encryptionScheme>None</encryptionScheme>
    <label>OldValue</label>
    <length>32768</length>
    <type>LongTextArea</type>
</CustomField>

BPER/DEVF/force-app/main/default/objects/TrackingHistory__c/fields/ParentObject__c.field-meta.xml
<CustomField>
    <fullName>ParentObject__c</fullName>
    <description>Salesforce Id of the modified object</description>
    <encryptionScheme>None</encryptionScheme>
    <label>Parent Object</label>
    <length>18</length>
    <required>true</required>
    <type>Text</type>
</CustomField>

BPER/DEVF/force-app/main/default/objects/TrackingHistory__c/fields/Tracking_Field__c.field-meta.xml
<CustomField>
    <fullName>Tracking_Field__c</fullName>
    <description>API name of modified field</description>
    <encryptionScheme>None</encryptionScheme>
    <label>Tracking Field</label>
    <length>255</length>
    <required>true</required>
    <type>Text</type>
</CustomField>

BPER/DEVF/force-app/main/default/objects/TrackingHistory__c/fields/Tracking_ObjRecordType__c.field-meta.xml
<CustomField>
    <fullName>Tracking_ObjRecordType__c</fullName>
    <encryptionScheme>None</encryptionScheme>
    <label>Tracking ObjRecordType</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

BPER/DEVF/force-app/main/default/objects/TrackingHistoryConfiguration__mdt/TrackingHistoryConfiguration__mdt.object-meta.xml
<CustomObject>
    <label>TrackingHistoryConfiguration</label>
    <pluralLabel>TrackingHistoryConfigurations</pluralLabel>
</CustomObject>

BPER/DEVF/force-app/main/default/objects/TrackingHistoryConfiguration__mdt/fields/ObjectDevName__c.field-meta.xml
<CustomField>
    <fullName>ObjectDevName__c</fullName>
    <description>Object API name to track</description>
    <label>ObjectDevName</label>
    <length>255</length>
    <required>true</required>
    <type>Text</type>
</CustomField>

BPER/DEVF/force-app/main/default/objects/TrackingHistoryConfiguration__mdt/fields/ParentField__c.field-meta.xml
<CustomField>
    <fullName>ParentField__c</fullName>
    <description>API name of the field in which Id is saved</description>
    <label>ParentField</label>
    <length>255</length>
    <required>true</required>
    <type>Text</type>
</CustomField>

BPER/DEVF/force-app/main/default/objects/TrackingHistoryConfiguration__mdt/fields/RecordTypeDevName__c.field-meta.xml
<CustomField>
    <fullName>RecordTypeDevName__c</fullName>
    <description>Parent object record type developer name to track</description>
    <label>RecordTypeDevName</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

BPER/DEVF/force-app/main/default/objects/TrackingHistoryConfiguration__mdt/fields/TrackingFieldList__c.field-meta.xml
<CustomField>
    <fullName>TrackingFieldList__c</fullName>
    <description>Field API name list to track, separated by &quot;;&quot;</description>
    <label>TrackingFieldList</label>
    <length>255</length>
    <required>true</required>
    <type>Text</type>
</CustomField>

BPER/RIORG/force-app/main/default/classes/OnCRMCustomerInterviewTriggerHandler.cls
public class OnCRMCustomerInterviewTriggerHandler {

    public static Boolean trafficLightTrackingTrigger = false;


    public static void trackHistory(Map<Id, CRM_CustomerInterview__c> oldTriggerCRM_CustomerInterviewMap, Map<Id, CRM_CustomerInterview__c> newTriggerCRM_CustomerInterviewMap){
	
        //Get apiname of object (CRM_CustomerInterview)
		String objApiName = String.valueOf(newTriggerCRM_CustomerInterviewMap.getSObjectType());
	
        //Get data information from metadata
		TrackingHistoryConfiguration__mdt[] metadataList = [SELECT ParentField__c, TrackingFieldList__c,
                                                            RecordTypeDevName__c, ObjectDevName__c
                                                            FROM TrackingHistoryConfiguration__mdt
                                                            WHERE ObjectDevName__c = :objApiName
                                                            LIMIT 1];
        
        if(metadataList.size() > 0 && !trafficLightTrackingTrigger){
            TrackingHistoryConfiguration__mdt metadataObj = metadataList.get(0);
		
            //For each record, for each field to track, create a tracking object
            String recordTypeIdString = Schema.SObjectType.TrackingHistory__c.getRecordTypeInfosByDeveloperName().get(metadataObj.RecordTypeDevName__c).getRecordTypeId();
            List<String> trackingFieldList = metadataObj.TrackingFieldList__c.split(';');
            List<TrackingHistory__c> trackingObjects = new List<TrackingHistory__c>();
            
            for(CRM_CustomerInterview__c newTriggerCRM_CustomerInterview : newTriggerCRM_CustomerInterviewMap.values()){
                for(String trackingField : trackingFieldList){
                    String oldValue;
                    String newValue = (String) newTriggerCRM_CustomerInterview.get(trackingField);
                    
                    if(!(oldTriggerCRM_CustomerInterviewMap == null || oldTriggerCRM_CustomerInterviewMap.isEmpty())){
                        CRM_CustomerInterview__c oldTriggerCRM_CustomerInterview = oldTriggerCRM_CustomerInterviewMap.get(newTriggerCRM_CustomerInterview.id);
                        oldValue = (String) oldTriggerCRM_CustomerInterview.get(trackingField);
                    }

                    if((!String.isBlank(newValue) && String.isBlank(oldValue)) || (!String.isBlank(newValue) && !String.isBlank(oldValue) && !(newValue.equals(oldValue)))){
                        TrackingHistory__c trackingObj = new TrackingHistory__c(
                                                        RecordTypeId = recordTypeIdString,
                                                        ParentObject__c = newTriggerCRM_CustomerInterview.Id,
                                                        Cliente__c = newTriggerCRM_CustomerInterview.CRM_Customer__c,
                                                        Tracking_Field__c = trackingField,
                                                        Tracking_ObjRecordType__c = Schema.SObjectType.CRM_CustomerInterview__c.getRecordTypeInfosById().get(newTriggerCRM_CustomerInterview.RecordTypeId).getDeveloperName(),
                                                        OldValue__c = oldValue,
                                                        NewValue__c = newValue);
                        //get dynamically the field API name which contains the record id from metadata
                        trackingObj.put(metadataObj.ParentField__c, newTriggerCRM_CustomerInterview.id);
                        
                        trackingObjects.add(trackingObj);
                    }

                }
            }
            
            insert trackingObjects;
            trafficLightTrackingTrigger = true;
        }
		
		
	}
}