BPER/DEVF/force-app/main/default/objects/CRM_InformazioneParticolare__c/CRM_InformazioneParticolare__c.object-meta.xml
<CustomObject>
    <label>Informazione particolare</label>
    <nameField>
        <encryptionScheme>None</encryptionScheme>
        <label>Nome Informazioni particolari</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Informazioni particolari</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

BPER/DEVF/force-app/main/default/objects/CRM_InformazioneParticolare__c/fields/CRM_Account__c.field-meta.xml
<CustomField>
    <fullName>CRM_Account__c</fullName>
    <label>Account</label>
    <referenceTo>Account</referenceTo>
    <relationshipLabel>Informazioni particolari</relationshipLabel>
    <relationshipName>Informazioni_particolari</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

BPER/DEVF/force-app/main/default/objects/CRM_Memo__c/CRM_Memo__c.object-meta.xml
<CustomObject>
    <label>Memo</label>
    <nameField>
        <encryptionScheme>None</encryptionScheme>
        <label>Titolo</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Memo</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

BPER/DEVF/force-app/main/default/objects/Endpoint__c/Endpoint__c.object-meta.xml
<CustomObject>
    <customSettingsType>List</customSettingsType>
    <description>List of Endpoints</description>
    <label>Endpoint List</label>
</CustomObject>

BPER/DEVF/force-app/main/default/objects/Endpoint__c/fields/BodyParams__c.field-meta.xml
<CustomField>
    <fullName>BodyParams__c</fullName>
    <encryptionScheme>None</encryptionScheme>
    <label>Body Params</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

BPER/DEVF/force-app/main/default/objects/Endpoint__c/fields/Endpoint__c.field-meta.xml
<CustomField>
    <fullName>Endpoint__c</fullName>
    <encryptionScheme>None</encryptionScheme>
    <label>Endpoint</label>
    <type>Url</type>
</CustomField>

BPER/DEVF/force-app/main/default/objects/Endpoint__c/fields/EndpointParams__c.field-meta.xml
<CustomField>
    <fullName>EndpointParams__c</fullName>
    <encryptionScheme>None</encryptionScheme>
    <label>Endpoint Params</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

BPER/DEVF/force-app/main/default/objects/Endpoint__c/fields/InList__c.field-meta.xml
<CustomField>
    <fullName>InList__c</fullName>
    <defaultValue>false</defaultValue>
    <label>In List</label>
    <type>Checkbox</type>
</CustomField>

BPER/DEVF/force-app/main/default/objects/Endpoint__c/fields/Method__c.field-meta.xml
<CustomField>
    <fullName>Method__c</fullName>
    <encryptionScheme>None</encryptionScheme>
    <label>Method</label>
    <length>10</length>
    <type>Text</type>
</CustomField>

BPER/DEVF/force-app/main/default/objects/NDGManagementMember__c/NDGManagementMember__c.object-meta.xml
<CustomObject>
    <label>Referente NDG</label>
    <nameField>
        <displayFormat>{0000}</displayFormat>
        <label>Referente NDG Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Referenti NDG</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

BPER/DEVF/force-app/main/default/objects/PDFConfigurator__mdt/PDFConfigurator__mdt.object-meta.xml
<CustomObject>
    <label>PDFConfigurator</label>
    <pluralLabel>PDFConfigurators</pluralLabel>
</CustomObject>

BPER/DEVF/force-app/main/default/objects/PDFConfigurator__mdt/fields/baseXml__c.field-meta.xml
<CustomField>
    <fullName>baseXml__c</fullName>
    <description>Stringa xml relativa alla sezione</description>
    <inlineHelpText>Stringa xml relativa alla sezione
PLACEHOLDERS
SEZIONI
###ZONA_SEZIONI###
COMPONENTI
###ZONA_COMPONENTI###
TABELLA
###XML_DETTAGLIO###
NUMERO RIGHE
###NUMERO_RIGHE###
NOME CAMPO
{!api_name_campo}</inlineHelpText>
    <label>baseXml</label>
    <length>32768</length>
    <type>LongTextArea</type>
</CustomField>

BPER/DEVF/force-app/main/default/objects/PDFConfigurator__mdt/fields/COMPONENT__c.field-meta.xml
<CustomField>
    <fullName>COMPONENT__c</fullName>
    <description>Il nome del componente all&apos;interno della sezione</description>
    <inlineHelpText>Il nome del componente all&apos;interno della sezione</inlineHelpText>
    <label>Componente</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

BPER/DEVF/force-app/main/default/objects/PDFConfigurator__mdt/fields/HasMetodoSelezione__c.field-meta.xml
<CustomField>
    <fullName>HasMetodoSelezione__c</fullName>
    <defaultValue>false</defaultValue>
    <description>Campo che indica se l&apos;xml recupererà dati tramite metodo dedicato</description>
    <inlineHelpText>Campo che indica se l&apos;xml recupererà dati tramite metodo dedicato</inlineHelpText>
    <label>Has Metodo Selezione</label>
    <type>Checkbox</type>
</CustomField>

BPER/DEVF/force-app/main/default/objects/PDFConfigurator__mdt/fields/HasQuery__c.field-meta.xml
<CustomField>
    <fullName>HasQuery__c</fullName>
    <defaultValue>false</defaultValue>
    <description>Campo che indica se l&apos;xml recupererà dati tramite query</description>
    <inlineHelpText>Campo che indica se l&apos;xml recupererà dati tramite query</inlineHelpText>
    <label>Has Query</label>
    <type>Checkbox</type>
</CustomField>

BPER/DEVF/force-app/main/default/objects/PDFConfigurator__mdt/fields/isActive__c.field-meta.xml
<CustomField>
    <fullName>isActive__c</fullName>
    <defaultValue>false</defaultValue>
    <description>Campo che indica se l&apos;xml presente verrà utilizzato per popolare l&apos;xml totale</description>
    <inlineHelpText>Campo che indica se l&apos;xml presente verrà utilizzato per popolare l&apos;xml totale</inlineHelpText>
    <label>isActive</label>
    <type>Checkbox</type>
</CustomField>

BPER/DEVF/force-app/main/default/objects/PDFConfigurator__mdt/fields/isRoot__c.field-meta.xml
<CustomField>
    <fullName>isRoot__c</fullName>
    <defaultValue>false</defaultValue>
    <description>Campo che indica la radice dell&apos;xml</description>
    <inlineHelpText>Campo che indica la radice dell&apos;xml</inlineHelpText>
    <label>isRoot</label>
    <type>Checkbox</type>
</CustomField>

BPER/DEVF/force-app/main/default/objects/PDFConfigurator__mdt/fields/MetodoSelezioneAdditionalParameters__c.field-meta.xml
<CustomField>
    <fullName>MetodoSelezioneAdditionalParameters__c</fullName>
    <description>Parametri aggiuntivi da passare al metodo di selezione, da scrivere in formato json.</description>
    <inlineHelpText>Parametri aggiuntivi da passare al metodo di selezione, da scrivere in formato json.</inlineHelpText>
    <label>Metodo Selezione additional parameters</label>
    <length>32768</length>
    <type>LongTextArea</type>
</CustomField>

BPER/DEVF/force-app/main/default/objects/PDFConfigurator__mdt/fields/MetodoSelezioneClasse__c.field-meta.xml
<CustomField>
    <fullName>MetodoSelezioneClasse__c</fullName>
    <description>API Name della classe da cui richiamare dinamicamente i metodi</description>
    <inlineHelpText>API Name della classe da cui richiamare dinamicamente i metodi</inlineHelpText>
    <label>Metodo Selezione Classe</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

BPER/DEVF/force-app/main/default/objects/PDFConfigurator__mdt/fields/MetodoSelezioneName__c.field-meta.xml
<CustomField>
    <fullName>MetodoSelezioneName__c</fullName>
    <description>API Name del metodo da richiamare dinamicamente</description>
    <inlineHelpText>API Name del metodo da richiamare dinamicamente</inlineHelpText>
    <label>Metodo Selezione Name</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

BPER/DEVF/force-app/main/default/objects/PDFConfigurator__mdt/fields/OBJRECORDTYPE__c.field-meta.xml
<CustomField>
    <fullName>OBJRECORDTYPE__c</fullName>
    <description>Record Type Developer Name dell&apos;oggetto a cui fa riferimento l&apos;xml</description>
    <inlineHelpText>Record Type Developer Name dell&apos;oggetto a cui fa riferimento l&apos;xml</inlineHelpText>
    <label>RECORD TYPE OGGETTO</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>AltraUnitaOrganizzativa</fullName>
            </value>
            <value>
                <fullName>Area</fullName>
            </value>
            <value>
                <fullName>Banca</fullName>
            </value>
            <value>
                <fullName>Cointestazione</fullName>
            </value>
            <value>
                <fullName>DirezioneRegionale</fullName>
            </value>
            <value>
                <fullName>FilialeDiRelazione</fullName>
            </value>
            <value>
                <fullName>GruppoFinanziario</fullName>
            </value>
            <value>
                <fullName>IndustriesHousehold</fullName>
            </value>
            <value>
                <fullName>IndustriesBusiness</fullName>
            </value>
            <value>
                <fullName>PersonAccount</fullName>
            </value>
            <value>
                <fullName>IndustriesIndividual</fullName>
                <isActive>false</isActive>
                <label>IndustriesIndividual</label>
            </value>
            <value>
                <fullName>IndustriesInstitution</fullName>
                <isActive>false</isActive>
                <label>IndustriesInstitution</label>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

BPER/DEVF/force-app/main/default/objects/PDFConfigurator__mdt/fields/OGGETTO__c.field-meta.xml
<CustomField>
    <fullName>OGGETTO__c</fullName>
    <description>API NAME dell&apos;oggetto a cui fa riferimento l&apos;xml</description>
    <inlineHelpText>API NAME dell&apos;oggetto a cui fa riferimento l&apos;xml</inlineHelpText>
    <label>OGGETTO</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

BPER/DEVF/force-app/main/default/objects/PDFConfigurator__mdt/fields/Ordine__c.field-meta.xml
<CustomField>
    <fullName>Ordine__c</fullName>
    <description>Ordine di caricamento delle sezioni e dei componenti (sezione X00, componente XYY)</description>
    <inlineHelpText>Ordine di caricamento delle sezioni e dei componenti (sezione X00, componente XYY)</inlineHelpText>
    <label>Ordine</label>
    <precision>6</precision>
    <scale>2</scale>
    <type>Number</type>
</CustomField>

BPER/DEVF/force-app/main/default/objects/PDFConfigurator__mdt/fields/QueryCampiAggiuntivi__c.field-meta.xml
<CustomField>
    <fullName>QueryCampiAggiuntivi__c</fullName>
    <description>campi relativi alle relazioni, separati da virgola</description>
    <inlineHelpText>Campi relativi alle relazioni, separati da virgola.
In caso di elemento ROOT: utilizzati per recuperare campi addentrati nelle relazioni
In caso di elemento non root: utilizzati solo se Has Query flaggato per recuperare campi addentrati nelle relazioni</inlineHelpText>
    <label>Query Campi Aggiuntivi</label>
    <length>20000</length>
    <type>LongTextArea</type>
</CustomField>

BPER/DEVF/force-app/main/default/objects/PDFConfigurator__mdt/fields/QueryLookup__c.field-meta.xml
<CustomField>
    <fullName>QueryLookup__c</fullName>
    <description>Indicare l&apos;API Name dell&apos;campo lookup in cui è presente l&apos;id dell&apos;oggetto principale</description>
    <inlineHelpText>Indicare l&apos;API Name dell&apos;campo lookup in cui è presente l&apos;id dell&apos;oggetto principale</inlineHelpText>
    <label>Query Lookup</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

BPER/DEVF/force-app/main/default/objects/PDFConfigurator__mdt/fields/QueryObjectType__c.field-meta.xml
<CustomField>
    <fullName>QueryObjectType__c</fullName>
    <description>Indicare l&apos;API Name dell&apos;oggetto su cui effettuare la query</description>
    <inlineHelpText>Indicare l&apos;API Name dell&apos;oggetto su cui effettuare la query</inlineHelpText>
    <label>Query Object Type</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

BPER/DEVF/force-app/main/default/objects/PDFConfigurator__mdt/fields/QueryWhereCondition__c.field-meta.xml
<CustomField>
    <fullName>QueryWhereCondition__c</fullName>
    <description>Indicare le condizioni della Query successive al WHERE, iniziando con AND (es: AND Id != NULL)</description>
    <inlineHelpText>Indicare le condizioni della Query successive al WHERE, iniziando con AND (es: AND Id != NULL)
DEFAULT: AND Id != NULL</inlineHelpText>
    <label>Query Where Condition</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

BPER/DEVF/force-app/main/default/objects/PDFConfigurator__mdt/fields/SECTION__c.field-meta.xml
<CustomField>
    <fullName>SECTION__c</fullName>
    <description>Il nome della sezione dell&apos;xml</description>
    <inlineHelpText>Il nome della sezione dell&apos;xml</inlineHelpText>
    <label>Nome Sezione</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

BPER/DEVF/force-app/main/default/objects/PDFConfigurator__mdt/fields/TemplateIterationXml__c.field-meta.xml
<CustomField>
    <fullName>TemplateIterationXml__c</fullName>
    <description>XML da inserire all&apos;interno del componente che verrà ripetuto per ogni record recuperato</description>
    <inlineHelpText>XML da inserire all&apos;interno del componente che verrà ripetuto per ogni record recuperato
PLACEHOLDERS
NUMERO RIGHE
###NUMERO_RIGHE###
NOME CAMPO
{!api_name_campo}</inlineHelpText>
    <label>Template Iteration Xml</label>
    <length>131072</length>
    <type>LongTextArea</type>
</CustomField>

BPER/DEVF/force-app/main/default/classes/WGC_Storico_AttivitaController_Test.cls
@isTest
public class WGC_Storico_AttivitaController_Test {
    private static List<PDFConfigurator__mdt> selectedSections = new List<PDFConfigurator__mdt>();

    @testsetup
    static void inserts(){
        RecordType rectype = [SELECT Id, DeveloperName FROM RecordType WHERE DeveloperName = 'IndustriesBusiness' LIMIT 1];

        Account acc = new Account(Name = 'Test', RecordTypeId = rectype.Id, PTF_DataApertura__c = DateTime.now(), CRM_DataAggCreditRating__c = Date.today());
        insert acc;

        CRM_InformazioneParticolare__c crm_acc = new CRM_InformazioneParticolare__c(CRM_Account__c = acc.Id);
        insert crm_acc;

        RecordType CreditCardRecordType = [SELECT id FROM RecordType WHERE DeveloperName = 'BankingAccount' AND SobjectType = 'FinServ__FinancialAccount__c' LIMIT 1].get(0);
        
        Account testAcc = new Account(Name = 'testAcc');
        insert testAcc;

        Product2 product = new Product2(
            Name = 'Test'
        );
        insert product;

        FinServ__FinancialAccount__c financialAccount = new FinServ__FinancialAccount__c();
        financialAccount.FinServ__Status__c = 'ATTIVO';
        financialAccount.RecordTypeId = CreditCardRecordType.Id;
        financialAccount.FinServ__ProductName__c = product.Id;
        financialAccount.FinServ__PrimaryOwner__c = testAcc.Id;
        insert financialAccount;

        FinServ__FinancialAccountRole__c financialRole = new FinServ__FinancialAccountRole__c();
        financialRole.FinServ__RelatedAccount__c = testAcc.Id;
        financialRole.FinServ__FinancialAccount__c = financialAccount.Id;
        financialRole.FinServ__Role__c='Primary Owner';
        insert financialRole;

        Endpoint__c generateDocument = (Endpoint__c)JSON.deserialize('{"attributes":{"type":"Endpoint__c","url":""},"IsDeleted":false,"Name":"generateDocument","EndpointParams__c":null,"Endpoint__c":"https://apigw.bper.it/gateway/DocumentsGenerationEngineAPI/v1/documentsgenerationengine/generateDocument","Method__c":"POST","Timeout__c":120000,"BodyParams__c":null,"InList__c":false}', Endpoint__c.class);
        insert generateDocument;
    }

    @isTest
    public static void test_storicoAll(){
        
        
        Account acc = [SELECT Id, Name, RecordTypeId, RecordTypeName__c FROM Account WHERE Name = 'Test' LIMIT 1];
        PDFConfigurator__mdt meta = new PDFConfigurator__mdt();
        meta.baseXml__c = '<tabellaprodotto><tipoTabella>2</tipoTabella><nomeProdotto>TEST CONTI CORRENTI</nomeProdotto><numeroProdotti>###NUMERO_RIGHE###</numeroProdotti>###XML_DETTAGLIO###</tabellaprodotto>';
        meta.MetodoSelezioneClasse__c = 'pdfConfiguratorCallableMethods';
        meta.MetodoSelezioneName__c = 'getProdottiList';
        meta.MetodoSelezioneAdditionalParameters__c = '{"RecordType": "BankingAccount", "statusFinServ": "ATTIVO"}';
        meta.TemplateIterationXml__c = '<dettaglio1>{!financialAccount_Name}</dettaglio1><dettaglio2>{!financialRole_FinServ__Role__c}</dettaglio2></prodottoDettaglio>';
        meta.HasMetodoSelezione__c = true;
        
        Test.startTest();
        //WGC_Storico_AttivitaController.getAllData((String)acc.Id, 'Account', '');
        WGC_Storico_AttivitaController.getAllData((String)acc.Id, 'Opportunity', '','00e3X000002iXa6');
        WGC_Storico_AttivitaController.getAllData((String)acc.Id, 'FinServ__FinancialAccount__c', '','00e3X000002iXa6');

        WGC_Storico_AttivitaController.getAllData((String)acc.Id, 'CRM_Memo__c', '','00e3X000002iXa6');
        //WGC_Storico_AttivitaController.getAllData((String)acc.Id, 'Task', '');
        WGC_Storico_AttivitaController.getAllData((String)acc.Id, 'NDGManagementMember__c', '','00e3X000002iXa6');
        
        
        WGC_Storico_AttivitaController.getUserInfo();
        Object response = WGC_Storico_AttivitaController.initStampa(acc.Id);
        List<PDFConfigurator__mdt> ListMetaData = makeData();
        String rootxml = WGC_Storico_AttivitaController.getRootXML(ListMetaData, acc);
        
        String recordTypeDeveloperName = 'IndustriesBusiness';
        selectedSections = new List<PDFConfigurator__mdt>();
        selectedSections.add(new PDFConfigurator__mdt(SECTION__c = 'Anagrafica'));

        List<PDFConfigurator__mdt> fullMetadata = WGC_Storico_AttivitaController.getFullMetadataFromSelected(selectedSections, 'Account', recordTypeDeveloperName);
        String xmlFromQuery = '';
        for(PDFConfigurator__mdt m2 : ListMetaData){
            if(m2.HasQuery__c){
                Map<String,String> resultMap = WGC_Storico_AttivitaController.getXMLFromQuery4Promise(m2,acc);
                System.debug('xmlFromQuery: '+xmlFromQuery);
            }
        }

        String query = String.escapeSingleQuotes(SV_Utilities.selectAllField('FinServ__FinancialAccount__c'));
        List<FinServ__FinancialAccount__c> recordList = (List<FinServ__FinancialAccount__c>)Database.query(query);
        Map<String, String> recordObjectTypeMap = new map<String, String>();
        for(FinServ__FinancialAccount__c finalcialAccount : recordList){
            recordObjectTypeMap.put(finalcialAccount.Id, 'FinServ__FinancialAccount__c');
        }

        response = WGC_Storico_AttivitaController.getXMLFromMethods4Promise(meta, acc, recordList, recordObjectTypeMap);
        WGC_Storico_AttivitaController.filterDataFunction(acc.Id, 'FinServ__FinancialAccount__c',Date.today().addDays(-365), Date.today().addDays(365));
        Test.stopTest();

    }

    private static List<PDFConfigurator__mdt> makeData(){

        List<PDFConfigurator__mdt> TListMetaData = new List<PDFConfigurator__mdt>();

        PDFConfigurator__mdt metadata = new PDFConfigurator__mdt();
        metadata.MasterLabel = 'rootlabel';
        metadata.DeveloperName = 'rootlabel';

        metadata.Ordine__c = 0;
        metadata.OGGETTO__c = 'Account';

        metadata.OBJRECORDTYPE__c = '';

        metadata.SECTION__c = 'rootxml';
        metadata.COMPONENT__c = '';

        metadata.isActive__c = true;
        metadata.isRoot__c = true;
        metadata.HasQuery__c = false;
        metadata.HasMetodoSelezione__c = false;

        metadata.baseXml__c = '<document>	<documentInfo>	  <documentType>{!RecordTypeName__c}</documentType>	  <datarif>{!RecordTypeName__c}</datarif>	</documentInfo>	<bankInfo>	  <ABI>{!RecordTypeName__c}</ABI>	</bankInfo>	<customer>		<fullname>{!RecordTypeName__c}</fullname>		<ndg>{!RecordTypeName__c}</ndg>	</customer>	<compactLayout>		<banca>{!RecordTypeName__c}</banca>		<nomeCliente>{!RecordTypeName__c}</nomeCliente>		<compactNDG>{!RecordTypeName__c}</compactNDG>		<M-MDS>{!RecordTypeName__c}</M-MDS>		<filiale>{!RecordTypeName__c}</filiale>		<portafoglio>{!RecordTypeName__c}</portafoglio>		<gestoreRiferimento>CAMPO_SCONOSCIUTO</gestoreRiferimento>		<privacy>{!RecordTypeName__c}</privacy>		<dataUltimoContatto>CAMPO_SCONOSCIUTO</dataUltimoContatto>	</compactLayout>	###ZONA_SEZIONI###</document>';
        
        metadata.MetodoSelezioneAdditionalParameters__c = '';
        metadata.MetodoSelezioneClasse__c = '';
        metadata.MetodoSelezioneName__c = '';
        
        
        metadata.QueryCampiAggiuntivi__c = '';
        metadata.QueryLookup__c = '';
        metadata.QueryObjectType__c = '';
        metadata.QueryWhereCondition__c = '';
        
        metadata.TemplateIterationXml__c = '';

        TListMetaData.add(metadata);

        PDFConfigurator__mdt metadata2 = new PDFConfigurator__mdt();
        metadata2.MasterLabel = 'Anagraficalabel';
        metadata2.DeveloperName = 'Anagraficalabel';

        metadata2.Ordine__c = 100;
        metadata2.OGGETTO__c = 'Account';

        metadata2.OBJRECORDTYPE__c = '';

        metadata2.SECTION__c = 'Anagrafica';
        metadata2.COMPONENT__c = '';

        metadata2.isActive__c = true;
        metadata2.isRoot__c = false;
        metadata2.HasQuery__c = false;
        metadata2.HasMetodoSelezione__c = false;

        metadata2.baseXml__c = '<anagrafica>###ZONA_COMPONENTI###</anagrafica>';        
        metadata2.MetodoSelezioneAdditionalParameters__c = '';
        metadata2.MetodoSelezioneClasse__c = '';
        metadata2.MetodoSelezioneName__c = '';
        
        
        metadata2.QueryCampiAggiuntivi__c = '';
        metadata2.QueryLookup__c = '';
        metadata2.QueryObjectType__c = '';
        metadata2.QueryWhereCondition__c = '';
        
        metadata2.TemplateIterationXml__c = '';

        TListMetaData.add(metadata2);

        PDFConfigurator__mdt metadata3 = new PDFConfigurator__mdt();
        metadata3.MasterLabel = 'InfoAnagrafelabel';
        metadata3.DeveloperName = 'InfoAnagrafelabel';

        metadata3.Ordine__c = 100;
        metadata3.OGGETTO__c = 'Account';

        metadata3.OBJRECORDTYPE__c = '';

        metadata3.SECTION__c = 'Anagrafica';
        metadata3.COMPONENT__c = 'Info Anagrafe';

        metadata3.isActive__c = true;
        metadata3.isRoot__c = false;
        metadata3.HasQuery__c = false;
        metadata3.HasMetodoSelezione__c = false;

        metadata3.baseXml__c = '<infoAnagrafe>    <informazioniAnagrafe>{!CRM_InformazioniInAnagrafe__c}</informazioniAnagrafe>    <informazioniRiservate>{!CRM_InformazioniRiservate__c}</informazioniRiservate></infoAnagrafe>';        
        metadata3.MetodoSelezioneAdditionalParameters__c = '';
        metadata3.MetodoSelezioneClasse__c = '';
        metadata3.MetodoSelezioneName__c = '';
        
        
        metadata3.QueryCampiAggiuntivi__c = '';
        metadata3.QueryLookup__c = '';
        metadata3.QueryObjectType__c = '';
        metadata3.QueryWhereCondition__c = '';
        
        metadata3.TemplateIterationXml__c = '';

        TListMetaData.add(metadata3);
        
        PDFConfigurator__mdt metadata4 = new PDFConfigurator__mdt();
        metadata4.MasterLabel = 'infoParticolarilabel';
        metadata4.DeveloperName = 'infoParticolarilabel';

        metadata4.Ordine__c = 107;
        metadata4.OGGETTO__c = 'Account';

        metadata4.OBJRECORDTYPE__c = '';

        metadata4.SECTION__c = 'Anagrafica';
        metadata4.COMPONENT__c = 'infoParticolari';

        metadata4.isActive__c = true;
        metadata4.isRoot__c = false;
        metadata4.HasQuery__c = true;
        metadata4.HasMetodoSelezione__c = false;

        metadata4.baseXml__c = '<infoParticolari>			<tabellaGenerica>				<tipoTabella>4</tipoTabella>				<titoloTabella>Informazioni Particolari</titoloTabella> <numeroRighe>###NUMERO_RIGHE###</numeroRighe>				<dettaglio>					<tipoRiga>T</tipoRiga>					<colonna1>CODICE</colonna1>					<colonna2>DESCRIZIONE</colonna2>					<colonna3>DA</colonna3>					<colonna4>A</colonna4>				</dettaglio>###XML_DETTAGLIO###</infoParticolari>';
        metadata4.MetodoSelezioneClasse__c = '';
        metadata4.MetodoSelezioneName__c = '';
        
        
        metadata4.QueryCampiAggiuntivi__c = '';
        metadata4.QueryLookup__c = 'CRM_Account__c';
        metadata4.QueryObjectType__c = 'CRM_InformazioneParticolare__c';
        metadata4.QueryWhereCondition__c = 'AND id != null';
        
        metadata4.TemplateIterationXml__c = '<dettaglio>					<tipoRiga>D</tipoRiga>					<colonna1>{!Id}</colonna1>				</dettaglio>';
        TListMetaData.add(metadata4);

        return TListMetaData;
    }
}