BPER/DEVF/force-app/main/default/objects/CH_Memo__c/CH_Memo__c.object-meta.xml
<CustomObject>
    <label>CH - Memo</label>
    <nameField>
        <encryptionScheme>None</encryptionScheme>
        <label>CH - Memo</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>CH - Memo</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

BPER/DEVF/force-app/main/default/objects/CH_Memo__c/fields/CRM_Account__c.field-meta.xml
<CustomField>
    <fullName>CRM_Account__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Cliente</label>
    <referenceTo>Account</referenceTo>
    <relationshipLabel>CH - Memo</relationshipLabel>
    <relationshipName>CH_Memo</relationshipName>
    <type>Lookup</type>
</CustomField>

BPER/DEVF/force-app/main/default/objects/CH_Memo__c/fields/CRM_FineValidita__c.field-meta.xml
<CustomField>
    <fullName>CRM_FineValidita__c</fullName>
    <encryptionScheme>None</encryptionScheme>
    <label>Fine validità</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

BPER/DEVF/force-app/main/default/objects/CH_Memo__c/fields/CRM_PopupCassa__c.field-meta.xml
<CustomField>
    <fullName>CRM_PopupCassa__c</fullName>
    <defaultValue>false</defaultValue>
    <label>Flag pop up di cassa</label>
    <type>Checkbox</type>
</CustomField>

BPER/DEVF/force-app/main/default/objects/CH_Memo__c/fields/CRM_Tipologia__c.field-meta.xml
<CustomField>
    <fullName>CRM_Tipologia__c</fullName>
    <encryptionScheme>None</encryptionScheme>
    <label>Tipologia</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

BPER/DEVF/force-app/main/default/objects/CRM_Memo__c/CRM_Memo__c.object-meta.xml
<CustomObject>
    <label>Memo</label>
    <nameField>
        <encryptionScheme>None</encryptionScheme>
        <label>Titolo</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Memo</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

BPER/DEVF/force-app/main/default/objects/CRM_Memo__c/fields/Cliente__c.field-meta.xml
<CustomField>
    <fullName>Cliente__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Cliente</label>
    <referenceTo>Account</referenceTo>
    <relationshipName>NoteTest</relationshipName>
    <type>Lookup</type>
</CustomField>

BPER/DEVF/force-app/main/default/objects/CRM_Memo__c/fields/CRM_FineValidita__c.field-meta.xml
<CustomField>
    <fullName>CRM_FineValidita__c</fullName>
    <encryptionScheme>None</encryptionScheme>
    <label>Fine validità</label>
    <type>Date</type>
</CustomField>

BPER/DEVF/force-app/main/default/objects/CRM_Memo__c/fields/CRM_PopupCassa__c.field-meta.xml
<CustomField>
    <fullName>CRM_PopupCassa__c</fullName>
    <defaultValue>false</defaultValue>
    <label>Popup di Cassa</label>
    <type>Checkbox</type>
</CustomField>

BPER/DEVF/force-app/main/default/objects/CRM_Memo__c/fields/CRM_Tipologia__c.field-meta.xml
<CustomField>
    <fullName>CRM_Tipologia__c</fullName>
    <encryptionScheme>None</encryptionScheme>
    <label>Tipologia</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

BPER/DEVF/force-app/main/default/objects/RoleMDS__c/RoleMDS__c.object-meta.xml
<CustomObject>
    <label>MDS per Ruolo</label>
    <nameField>
        <encryptionScheme>None</encryptionScheme>
        <label>MDS per Ruolo Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>MDS per Ruoli</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

BPER/DEVF/force-app/main/default/objects/RoleMDS__c/fields/PTF_BranchTypology__c.field-meta.xml
<CustomField>
    <fullName>PTF_BranchTypology__c</fullName>
    <label>Tipologia di filiale</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetName>BranchTypology</valueSetName>
    </valueSet>
</CustomField>

BPER/DEVF/force-app/main/default/objects/RoleMDS__c/fields/PTF_EndDate__c.field-meta.xml
<CustomField>
    <fullName>PTF_EndDate__c</fullName>
    <encryptionScheme>None</encryptionScheme>
    <label>Data fine</label>
    <type>Date</type>
</CustomField>

BPER/DEVF/force-app/main/default/objects/RoleMDS__c/fields/PTF_RoleTypology__c.field-meta.xml
<CustomField>
    <fullName>PTF_RoleTypology__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Tipologia di Ruolo</label>
    <referenceTo>RoleTypology__c</referenceTo>
    <relationshipLabel>MDS per Ruoli</relationshipLabel>
    <relationshipName>MDS_per_Ruoli</relationshipName>
    <type>Lookup</type>
</CustomField>

BPER/DEVF/force-app/main/default/objects/RoleMDS__c/fields/PTF_ServiceModel__c.field-meta.xml
<CustomField>
    <fullName>PTF_ServiceModel__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Macro-modello di servizio</label>
    <referenceTo>ServiceModel__c</referenceTo>
    <relationshipLabel>MDS per Ruoli</relationshipLabel>
    <relationshipName>MDS_per_Ruoli</relationshipName>
    <type>Lookup</type>
</CustomField>

BPER/DEVF/force-app/main/default/objects/RoleMDS__c/fields/PTF_StartDate__c.field-meta.xml
<CustomField>
    <fullName>PTF_StartDate__c</fullName>
    <encryptionScheme>None</encryptionScheme>
    <label>Data inizio</label>
    <type>Date</type>
</CustomField>

BPER/DEVF/force-app/main/default/objects/RoleTypology__c/RoleTypology__c.object-meta.xml
<CustomObject>
    <label>Tipologia Ruolo</label>
    <nameField>
        <encryptionScheme>None</encryptionScheme>
        <label>Nome Ruolo</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Tipologia Ruoli</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

BPER/DEVF/force-app/main/default/objects/ServiceModel__c/ServiceModel__c.object-meta.xml
<CustomObject>
    <label>Macro-modello di servizio</label>
    <nameField>
        <encryptionScheme>None</encryptionScheme>
        <label>Nome modello di servizio</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Macro-modelli di servizio</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

BPER/DEVF/force-app/main/default/objects/Wallet__c/Wallet__c.object-meta.xml
<CustomObject>
    <label>Portafoglio</label>
    <nameField>
        <encryptionScheme>None</encryptionScheme>
        <label>Wallet Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Portafogli</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

BPER/DEVF/force-app/main/default/objects/Wallet__c/fields/PTF_BranchTypology__c.field-meta.xml
<CustomField>
    <fullName>PTF_BranchTypology__c</fullName>
    <formula>TEXT(PTF_Filiale__r.PTF_BranchTypology__c)</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>BranchTypology</label>
    <type>Text</type>
</CustomField>

BPER/DEVF/force-app/main/default/objects/Wallet__c/fields/PTF_Filiale__c.field-meta.xml
<CustomField>
    <fullName>PTF_Filiale__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Filiale</label>
    <referenceTo>Account</referenceTo>
    <relationshipLabel>Portafogli (Filiale)</relationshipLabel>
    <relationshipName>Filiali</relationshipName>
    <type>Lookup</type>
</CustomField>

BPER/DEVF/force-app/main/default/objects/Wallet__c/recordTypes/MicroWallet.recordType-meta.xml
<RecordType>
    <fullName>MicroWallet</fullName>
    <active>true</active>
    <label>Microportafoglio</label>
</RecordType>

BPER/DEVF/force-app/main/default/objects/Wallet__c/recordTypes/TechnicalWallet.recordType-meta.xml
<RecordType>
    <fullName>TechnicalWallet</fullName>
    <active>true</active>
    <label>Portafoglio Tecnico</label>
</RecordType>

BPER/DEV/force-app/main/default/classes/CRM_MemoController_Test.cls
@IsTest
public with sharing class CRM_MemoController_Test {
    @TestSetup
    public static void setup(){
        Account filiale = AllDataFactory.getAccount('01', 'FilialeDiRelazione');
        insert filiale;

        Wallet__c microPortafoglioFamily = AllDataFactory.getWallet('MicroWallet',  filiale.Id, 'Family');
        Wallet__c microPortafoglioPersonal = AllDataFactory.getWallet('MicroWallet',  filiale.Id, 'Personal');
        Wallet__c portafoglioTecnico = AllDataFactory.getWallet('TechnicalWallet',  filiale.Id, 'Private');
        insert new List<Wallet__c>{microPortafoglioFamily, portafoglioTecnico, microPortafoglioPersonal};

        RoleTypology__c ruolo = new RoleTypology__c();
        ruolo.Name = 'Titolare';
        insert ruolo;

        ServiceModel__c modelloDiServizio = new ServiceModel__c();
        modelloDiServizio.Name = 'Personal';
        insert modelloDiServizio;

        RoleMDS__c ruoloMDS = new RoleMDS__c();
        ruoloMDS.PTF_BranchTypology__c = 'A';
        ruoloMDS.PTF_RoleTypology__c = ruolo.Id;
        ruoloMDS.PTF_ServiceModel__c = modelloDiServizio.Id;
        ruoloMDS.PTF_StartDate__c = Date.today().addDays(-10);
        ruoloMDS.PTF_EndDate__c = Date.today().addDays(10);
        insert ruoloMDS;
        
        Contact contact = AllDataFactory.getContact('01', UserInfo.getUserId(), filiale.Id);
        contact.PTF_TipologiaRuolo__c = ruolo.Id;
        insert contact;

        // Relazione Di Cointestazione
        Account personAccount = AllDataFactory.getAccount('01', 'PersonAccount');
        personAccount.PTF_Portafoglio__c = microPortafoglioPersonal.Id;
        personAccount.PTF_Filiale__c = filiale.Id;
        personAccount.PTF_StatoCRM__c = 'ATT';
        insert personAccount;

        CRM_Memo__c memo = new CRM_Memo__c();
        memo.Cliente__c = personAccount.id;
        memo.Name = 'test';
        memo.CRM_Tipologia__c = 'PUBBLICO';
        memo.CRM_FineValidita__c = Date.today();
        memo.CRM_PopupCassa__c = false;
        insert memo;

        CH_Memo__c chMemo = new CH_Memo__c();
        chMemo.CRM_Account__c = personAccount.id;
        chMemo.Name = 'test';
        chMemo.CRM_Tipologia__c = 'PUBBLICO';
        chMemo.CRM_FineValidita__c = Datetime.now().format('yyyy-MM-dd');
        chMemo.CRM_PopupCassa__c = false;
        insert chMemo;

    }

    @IsTest
    public static void test1(){
        List<Account> accList = [SELECT id FROM Account WHERE RecordType.Developername = 'PersonAccount' LIMIT 1];
        test.startTest();
        User user = CRM_MemoController.getUserInfo();
        CRM_MemoController.getAllData(acclist[0].Id);
        test.stopTest();
        System.assertEquals(true, user !=null);
        System.assertEquals(true,(CRM_MemoController.getAllData(acclist[0].Id)) !=null);
    }
}