BPER/DEVF/force-app/main/default/objects/ConfigurazioneSpostamenti__mdt/ConfigurazioneSpostamenti__mdt.object-meta.xml
<CustomObject>
    <label>Configurazione Spostamenti</label>
    <pluralLabel>Configurazione Spostamenti</pluralLabel>
</CustomObject>

BPER/DEVF/force-app/main/default/objects/ConfigurazioneSpostamenti__mdt/fields/Finestra_Temporale__c.field-meta.xml
<CustomField>
    <fullName>Finestra_Temporale__c</fullName>
    <defaultValue>false</defaultValue>
    <label>Finestra Temporale</label>
    <type>Checkbox</type>
</CustomField>

BPER/DEVF/force-app/main/default/objects/ConfigurazioneSpostamenti__mdt/fields/Iter_Approvativo__c.field-meta.xml
<CustomField>
    <fullName>Iter_Approvativo__c</fullName>
    <defaultValue>false</defaultValue>
    <label>Iter Approvativo</label>
    <type>Checkbox</type>
</CustomField>

BPER/DEVF/force-app/main/default/objects/ConfigurazioneSpostamenti__mdt/fields/PTF_Abi__c.field-meta.xml
<CustomField>
    <fullName>PTF_Abi__c</fullName>
    <label>Banca Permessa</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

BPER/DEVF/force-app/main/default/objects/ConfigurazioneSpostamenti__mdt/fields/PTF_CheckCedSpecifico__c.field-meta.xml
<CustomField>
    <fullName>PTF_CheckCedSpecifico__c</fullName>
    <label>Check Ced Specifico</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

BPER/DEVF/force-app/main/default/objects/ConfigurazioneSpostamenti__mdt/fields/PTF_CheckNaturaGiuridica__c.field-meta.xml
<CustomField>
    <fullName>PTF_CheckNaturaGiuridica__c</fullName>
    <label>Check Natura Giuridica</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

BPER/DEVF/force-app/main/default/objects/ConfigurazioneSpostamenti__mdt/fields/PTF_CheckTipologiaFilialeDestinazione__c.field-meta.xml
<CustomField>
    <fullName>PTF_CheckTipologiaFilialeDestinazione__c</fullName>
    <label>Check Tipologia Filiale di Destinazione</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

BPER/DEVF/force-app/main/default/objects/ConfigurazioneSpostamenti__mdt/fields/PTF_CheckTipologiaFilialePartenza__c.field-meta.xml
<CustomField>
    <fullName>PTF_CheckTipologiaFilialePartenza__c</fullName>
    <label>Check Tipologia Filiale di Partenza</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

BPER/DEVF/force-app/main/default/objects/ConfigurazioneSpostamenti__mdt/fields/PTF_Filiale_End__c.field-meta.xml
<CustomField>
    <fullName>PTF_Filiale_End__c</fullName>
    <label>Filiale End</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

BPER/DEVF/force-app/main/default/objects/ConfigurazioneSpostamenti__mdt/fields/PTF_Filiale_Start__c.field-meta.xml
<CustomField>
    <fullName>PTF_Filiale_Start__c</fullName>
    <label>Filiale Start</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

BPER/DEVF/force-app/main/default/objects/ConfigurazioneSpostamenti__mdt/fields/PTF_JSON_Approvatori__c.field-meta.xml
<CustomField>
    <fullName>PTF_JSON_Approvatori__c</fullName>
    <label>JSON Approvatori</label>
    <length>131072</length>
    <type>LongTextArea</type>
</CustomField>

BPER/DEVF/force-app/main/default/objects/ConfigurazioneSpostamenti__mdt/fields/PTF_MDS_End__c.field-meta.xml
<CustomField>
    <fullName>PTF_MDS_End__c</fullName>
    <label>MDS End</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

BPER/DEVF/force-app/main/default/objects/ConfigurazioneSpostamenti__mdt/fields/PTF_MDS_Start__c.field-meta.xml
<CustomField>
    <fullName>PTF_MDS_Start__c</fullName>
    <label>MDS Start</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

BPER/DEVF/force-app/main/default/objects/ConfigurazioneSpostamenti__mdt/fields/PTF_StessoReferente__c.field-meta.xml
<CustomField>
    <fullName>PTF_StessoReferente__c</fullName>
    <defaultValue>false</defaultValue>
    <label>Stesso Referente</label>
    <type>Checkbox</type>
</CustomField>

BPER/DEVF/force-app/main/default/objects/ConfigurazioneSpostamenti__mdt/fields/PTF_SuperUsers__c.field-meta.xml
<CustomField>
    <fullName>PTF_SuperUsers__c</fullName>
    <label>Super Users</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

BPER/DEVF/force-app/main/default/objects/ConfigurazioneSpostamenti__mdt/fields/Tipo_di_Spostamento__c.field-meta.xml
<CustomField>
    <fullName>Tipo_di_Spostamento__c</fullName>
    <label>Tipo di Spostamento</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>MDS</fullName>
                <default>true</default>
                <label>MDS</label>
            </value>
            <value>
                <fullName>Filiale</fullName>
            </value>
            <value>
                <fullName>MDS / Filiale</fullName>
            </value>
            <value>
                <fullName>Referenti</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

BPER/DEVF/force-app/main/default/objects/CRM_AccountAccountJointOwnershipRelation__c/CRM_AccountAccountJointOwnershipRelation__c.object-meta.xml
<CustomObject>
    <label>Relazione di cointestazione</label>
    <nameField>
        <displayFormat>RDC - {00000000}</displayFormat>
        <label>Nome AccountAccountJointOwnership Relati</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Relazioni di cointestazione</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

BPER/DEVF/force-app/main/default/objects/CRM_AccountAccountJointOwnershipRelation__c/fields/CRM_Account__c.field-meta.xml
<CustomField>
    <fullName>CRM_Account__c</fullName>
    <deleteConstraint>Restrict</deleteConstraint>
    <label>Account</label>
    <referenceTo>Account</referenceTo>
    <relationshipLabel>Relazioni di cointestazione (Account)</relationshipLabel>
    <relationshipName>AccountContactJointOwnershipRelations1</relationshipName>
    <required>true</required>
    <type>Lookup</type>
</CustomField>

BPER/DEVF/force-app/main/default/objects/CRM_AccountAccountJointOwnershipRelation__c/fields/CRM_Active__c.field-meta.xml
<CustomField>
    <fullName>CRM_Active__c</fullName>
    <defaultValue>false</defaultValue>
    <label>Active</label>
    <type>Checkbox</type>
</CustomField>

BPER/DEVF/force-app/main/default/objects/CRM_AccountAccountJointOwnershipRelation__c/fields/CRM_JointOwnership__c.field-meta.xml
<CustomField>
    <fullName>CRM_JointOwnership__c</fullName>
    <deleteConstraint>Restrict</deleteConstraint>
    <label>Joint Ownership</label>
    <lookupFilter>
        <active>true</active>
        <filterItems>
            <field>Account.RecordType.DeveloperName</field>
            <operation>equals</operation>
            <value>Cointestazione</value>
        </filterItems>
        <isOptional>false</isOptional>
    </lookupFilter>
    <referenceTo>Account</referenceTo>
    <relationshipName>AccountContactJointOwnershipRelations</relationshipName>
    <required>true</required>
    <type>Lookup</type>
</CustomField>

BPER/DEVF/force-app/main/default/objects/CRM_AccountAccountJointOwnershipRelation__c/fields/CRM_PrimaryNDG__c.field-meta.xml
<CustomField>
    <fullName>CRM_PrimaryNDG__c</fullName>
    <defaultValue>false</defaultValue>
    <label>Primary NDG</label>
    <type>Checkbox</type>
</CustomField>

BPER/DEVF/force-app/main/default/objects/CRM_AccountAccountJointOwnershipRelation__c/fields/PTF_ABI__c.field-meta.xml
<CustomField>
    <fullName>PTF_ABI__c</fullName>
    <formula>CRM_Account__r.FinServ__BankNumber__c</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>ABI</label>
    <type>Text</type>
</CustomField>

BPER/DEVF/force-app/main/default/objects/CRM_LinkedNDG__c/CRM_LinkedNDG__c.object-meta.xml
<CustomObject>
    <label>NDG collegati</label>
    <nameField>
        <displayFormat>NDGCollegati-{0000000000}</displayFormat>
        <label>Nome NDG collegati</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>NDG collegati</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

BPER/DEVF/force-app/main/default/objects/CRM_LinkedNDG__c/fields/CRM_Account__c.field-meta.xml
<CustomField>
    <fullName>CRM_Account__c</fullName>
    <deleteConstraint>Restrict</deleteConstraint>
    <label>Account</label>
    <referenceTo>Account</referenceTo>
    <relationshipLabel>NDG collegati</relationshipLabel>
    <relationshipName>NDG_collegati</relationshipName>
    <required>true</required>
    <type>Lookup</type>
</CustomField>

BPER/DEVF/force-app/main/default/objects/CRM_LinkedNDG__c/fields/CRM_LinkCode__c.field-meta.xml
<CustomField>
    <fullName>CRM_LinkCode__c</fullName>
    <encryptionScheme>None</encryptionScheme>
    <label>Link Code</label>
    <length>255</length>
    <required>true</required>
    <type>Text</type>
</CustomField>

BPER/DEVF/force-app/main/default/objects/CRM_LinkedNDG__c/fields/CRM_LinkType__c.field-meta.xml
<CustomField>
    <fullName>CRM_LinkType__c</fullName>
    <encryptionScheme>None</encryptionScheme>
    <label>Link Type</label>
    <length>255</length>
    <required>true</required>
    <type>Text</type>
</CustomField>

BPER/DEVF/force-app/main/default/objects/CRM_LinkedNDG__c/fields/CRM_RelatedAccount__c.field-meta.xml
<CustomField>
    <fullName>CRM_RelatedAccount__c</fullName>
    <deleteConstraint>Restrict</deleteConstraint>
    <label>Related Account</label>
    <referenceTo>Account</referenceTo>
    <relationshipLabel>NDG collegati (Related Account)</relationshipLabel>
    <relationshipName>CRM_LinkedNDG</relationshipName>
    <required>true</required>
    <type>Lookup</type>
</CustomField>

BPER/DEVF/force-app/main/default/objects/CRM_LinkedNDG__c/fields/CRM_Status__c.field-meta.xml
<CustomField>
    <fullName>CRM_Status__c</fullName>
    <label>Status</label>
    <required>true</required>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>A</fullName>
            </value>
            <value>
                <fullName>E</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

BPER/DEVF/force-app/main/default/objects/IterConfiguration__c/IterConfiguration__c.object-meta.xml
<CustomObject>
    <label>Iter Configuration</label>
    <nameField>
        <displayFormat>IC-{000000}</displayFormat>
        <label>Iter Configuration Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Iter Configurations</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

BPER/DEVF/force-app/main/default/objects/IterConfiguration__c/fields/UnitaOrganizzativa__c.field-meta.xml
<CustomField>
    <fullName>UnitaOrganizzativa__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Unità Organizzativa</label>
    <referenceTo>Account</referenceTo>
    <relationshipLabel>Iter Configurations</relationshipLabel>
    <relationshipName>IterConfigurations</relationshipName>
    <type>Lookup</type>
</CustomField>

BPER/DEVF/force-app/main/default/objects/ServiceModel__c/ServiceModel__c.object-meta.xml
<CustomObject>
    <label>Macro-modello di servizio</label>
    <nameField>
        <encryptionScheme>None</encryptionScheme>
        <label>Nome modello di servizio</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Macro-modelli di servizio</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

BPER/DEVF/force-app/main/default/objects/ServiceModel__c/fields/PTF_Division__c.field-meta.xml
<CustomField>
    <fullName>PTF_Division__c</fullName>
    <encryptionScheme>None</encryptionScheme>
    <label>Filiera</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

BPER/DEVF/force-app/main/default/objects/ServiceModel__c/fields/PTF_MacroDivision__c.field-meta.xml
<CustomField>
    <fullName>PTF_MacroDivision__c</fullName>
    <encryptionScheme>None</encryptionScheme>
    <label>Macrofiliera</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

BPER/DEVF/force-app/main/default/objects/Wallet__c/Wallet__c.object-meta.xml
<CustomObject>
    <label>Portafoglio</label>
    <nameField>
        <encryptionScheme>None</encryptionScheme>
        <label>Wallet Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Portafogli</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

BPER/DEVF/force-app/main/default/objects/Wallet__c/fields/PTF_ABI__c.field-meta.xml
<CustomField>
    <fullName>PTF_ABI__c</fullName>
    <formula>PTF_Banca__r.FinServ__BankNumber__c</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>ABI</label>
    <type>Text</type>
</CustomField>

BPER/DEVF/force-app/main/default/objects/Wallet__c/fields/PTF_Area__c.field-meta.xml
<CustomField>
    <fullName>PTF_Area__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Area</label>
    <referenceTo>Account</referenceTo>
    <relationshipLabel>Portafogli (Area)</relationshipLabel>
    <relationshipName>Portafogli2</relationshipName>
    <type>Lookup</type>
</CustomField>

BPER/DEVF/force-app/main/default/objects/Wallet__c/fields/PTF_Banca__c.field-meta.xml
<CustomField>
    <fullName>PTF_Banca__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Banca</label>
    <referenceTo>Account</referenceTo>
    <relationshipLabel>Portafogli</relationshipLabel>
    <relationshipName>Portafogli</relationshipName>
    <type>Lookup</type>
</CustomField>

BPER/DEVF/force-app/main/default/objects/Wallet__c/fields/PTF_BranchTypology__c.field-meta.xml
<CustomField>
    <fullName>PTF_BranchTypology__c</fullName>
    <formula>TEXT(PTF_Filiale__r.PTF_BranchTypology__c)</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>BranchTypology</label>
    <type>Text</type>
</CustomField>

BPER/DEVF/force-app/main/default/objects/Wallet__c/fields/PTF_DirezioneRegionale__c.field-meta.xml
<CustomField>
    <fullName>PTF_DirezioneRegionale__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Direzione Regionale</label>
    <referenceTo>Account</referenceTo>
    <relationshipLabel>Portafogli (Direzione Regionale)</relationshipLabel>
    <relationshipName>Portafogli1</relationshipName>
    <type>Lookup</type>
</CustomField>

BPER/DEVF/force-app/main/default/objects/Wallet__c/fields/PTF_Filiale__c.field-meta.xml
<CustomField>
    <fullName>PTF_Filiale__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Filiale</label>
    <referenceTo>Account</referenceTo>
    <relationshipLabel>Portafogli (Filiale)</relationshipLabel>
    <relationshipName>Filiali</relationshipName>
    <type>Lookup</type>
</CustomField>

BPER/DEVF/force-app/main/default/objects/Wallet__c/recordTypes/MicroWallet.recordType-meta.xml
<RecordType>
    <fullName>MicroWallet</fullName>
    <active>true</active>
    <label>Microportafoglio</label>
</RecordType>

BPER/DEVF/force-app/main/default/classes/Batch_CloseIterTest.cls
@isTest
public with sharing class Batch_CloseIterTest {
    
    @TestSetup
    static void makeData(){
        // TriggerControl__c tc = new TriggerControl__c();
        // tc.name = 'TEST';
        // insert tc;

        ServiceModel__c personal = new ServiceModel__c(Name = 'Personal',
        PTF_Division__c = 'PE',
        PTF_MacroDivision__c = 'WM');

        ServiceModel__c family = new ServiceModel__c(Name = 'Family',
        PTF_Division__c = 'FP',
        PTF_MacroDivision__c = 'EB');
        insert new List<ServiceModel__c>{personal, family};

        Account banca = AllDataFactory.getAccount('10', 'Banca');
        banca.FinServ__BankNumber__c = '05387';
        insert banca;
        Account dir = AllDataFactory.getAccount('09', 'DirezioneRegionale');
        // dir.PTF_ABICED__c = '05387';
        dir.parentId = banca.Id;
        insert dir;
        Account area = AllDataFactory.getAccount('08', 'Area');
        // area.PTF_ABICED__c = '05387';
        area.parentId = dir.Id;
        insert area;
        Account filiale = AllDataFactory.getAccount('01', 'FilialeDiRelazione');
        // filiale.PTF_ABICED__c = '05387';
        filiale.parentId = area.Id;
        filiale.PTF_BranchTypology__c = 'A';

        Account ufficioPersonal = AllDataFactory.getAccount('11', 'FilialeDiRelazione');
        // filiale.PTF_ABICED__c = '05387';
        ufficioPersonal.parentId = area.Id;
        ufficioPersonal.PTF_BranchTypology__c = 'A';
        ufficioPersonal.PTF_Division__c = 'PE';
        ufficioPersonal.PTF_MacroDivision__c = 'WM';
        Account ufficioFamily = AllDataFactory.getAccount('12', 'FilialeDiRelazione');
        // filiale.PTF_ABICED__c = '05387';
        ufficioFamily.parentId = area.Id;
        ufficioFamily.PTF_BranchTypology__c = 'A';
        ufficioFamily.PTF_Division__c = 'FP';
        ufficioFamily.PTF_MacroDivision__c = 'EB';
        insert new List<Account>{filiale, ufficioPersonal, ufficioFamily};

        Wallet__c microPortafoglioFamily = AllDataFactory.getWallet('MicroWallet',  null, 'Family');
        Wallet__c microPortafoglioPersonal = AllDataFactory.getWallet('MicroWallet',  null, 'Personal');
        insert new List<Wallet__c>{microPortafoglioFamily, microPortafoglioPersonal};
        microPortafoglioFamily.PTF_Filiale__c = filiale.Id;
        microPortafoglioFamily.PTF_Area__c = area.Id;
        microPortafoglioFamily.PTF_DirezioneRegionale__c = dir.id;
        microPortafoglioFamily.PTF_Banca__c = banca.Id;
        microPortafoglioPersonal.PTF_Filiale__c = filiale.Id;
        microPortafoglioPersonal.PTF_Area__c = area.Id;
        microPortafoglioPersonal.PTF_DirezioneRegionale__c = dir.id;
        microPortafoglioPersonal.PTF_Banca__c = banca.Id;

        update new List<Wallet__c>{microPortafoglioFamily, microPortafoglioPersonal};

        // Relazione Di Cointestazione
        Account personAccount = AllDataFactory.getAccount('01', 'PersonAccount');
        personAccount.PTF_Portafoglio__c = microPortafoglioPersonal.Id;
        personAccount.PTF_Filiale__c = filiale.Id;

        Account personAccount2 = AllDataFactory.getAccount('02', 'PersonAccount');
        personAccount2.PTF_Portafoglio__c = microPortafoglioFamily.Id;
        personAccount2.PTF_Filiale__c = filiale.Id;

        Account personAccount3 = AllDataFactory.getAccount('03', 'PersonAccount');
        personAccount3.PTF_Portafoglio__c = microPortafoglioPersonal.Id;
        personAccount3.PTF_Filiale__c = filiale.Id;

        Account cointestazione = AllDataFactory.getAccount('04', 'Cointestazione');
        cointestazione.PTF_Portafoglio__c = microPortafoglioPersonal.Id;
        cointestazione.PTF_Filiale__c = filiale.Id;

        // Gruppo
        Account gruppo = AllDataFactory.getAccount('05', 'GruppoFinanziario');
        gruppo.PTF_Portafoglio__c = microPortafoglioFamily.Id;
        gruppo.PTF_Filiale__c = filiale.Id;
        gruppo.PTF_NaturaGiuridica__c = 'GF';

        Account business = AllDataFactory.getAccount('06', 'IndustriesBusiness');
        business.PTF_Portafoglio__c = microPortafoglioPersonal.Id;
        business.PTF_Filiale__c = filiale.Id;

        Account business2 = AllDataFactory.getAccount('07', 'IndustriesBusiness');
        business2.PTF_Portafoglio__c = microPortafoglioFamily.Id;
        business2.PTF_Filiale__c = filiale.Id;

        insert new List<Account>{personAccount, personAccount2, personAccount3, cointestazione, gruppo, business, business2};

        CRM_LinkedNDG__c capoGruppo = new CRM_LinkedNDG__c(
            CRM_Account__c = gruppo.Id,
            CRM_RelatedAccount__c = business.Id,
            CRM_LinkCode__c = '113',
            CRM_Status__c = 'A',
            CRM_LinkType__c = 'CAPOGRUPPO'
        );
        CRM_LinkedNDG__c membroGruppo = new CRM_LinkedNDG__c(
            CRM_Account__c = gruppo.Id,
            CRM_RelatedAccount__c = business2.Id,
            CRM_LinkCode__c = '165',
            CRM_Status__c = 'A',
            CRM_LinkType__c = 'CONN.GIUR.'
        );
        insert new List<CRM_LinkedNDG__c>{capoGruppo, membroGruppo};

        CRM_AccountAccountJointOwnershipRelation__c relazioneDiCointestazionePrimario = new CRM_AccountAccountJointOwnershipRelation__c();
        relazioneDiCointestazionePrimario.CRM_PrimaryNDG__c = true;
        relazioneDiCointestazionePrimario.CRM_Account__c = personAccount.Id;
        relazioneDiCointestazionePrimario.CRM_JointOwnership__c = cointestazione.Id;
        relazioneDiCointestazionePrimario.CRM_Active__c = true;

        CRM_AccountAccountJointOwnershipRelation__c relazioneDiCointestazioneCointestatario = new CRM_AccountAccountJointOwnershipRelation__c();
        relazioneDiCointestazioneCointestatario.CRM_PrimaryNDG__c = false;
        relazioneDiCointestazioneCointestatario.CRM_Account__c = personAccount2.Id;
        relazioneDiCointestazioneCointestatario.CRM_JointOwnership__c = cointestazione.Id;
        relazioneDiCointestazioneCointestatario.CRM_Active__c = true;

        CRM_AccountAccountJointOwnershipRelation__c relazioneDiCointestazioneCointestatario2 = new CRM_AccountAccountJointOwnershipRelation__c();
        relazioneDiCointestazioneCointestatario2.CRM_PrimaryNDG__c = false;
        relazioneDiCointestazioneCointestatario2.CRM_Account__c = personAccount3.Id;
        relazioneDiCointestazioneCointestatario2.CRM_JointOwnership__c = cointestazione.Id;
        relazioneDiCointestazioneCointestatario2.CRM_Active__c = true;
        insert new List<CRM_AccountAccountJointOwnershipRelation__c>{relazioneDiCointestazionePrimario, relazioneDiCointestazioneCointestatario, relazioneDiCointestazioneCointestatario2};

        Profile profile = [SELECT id FROM Profile WHERE  Name =: Label.System_Administrator LIMIT 1];
        
        User user = AllDataFactory.getUser('10', profile.Id, 'Personal');
        user.FederationIdentifier='10';
        User ufficioModelliDistributivi = AllDataFactory.getUser('11', profile.Id, 'Personal');
        ufficioModelliDistributivi.FederationIdentifier = '11';
        ufficioModelliDistributivi.Profilo__c = 'NEC_D.0';

        User NECT4Personal = AllDataFactory.getUser('12', profile.Id, 'Personal');
        NECT4Personal.FederationIdentifier = '12';
        NECT4Personal.Profilo__c = 'NEC_T.4';
        User NECT4Family = AllDataFactory.getUser('13', profile.Id, 'Personal');
        NECT4Family.FederationIdentifier = '13';
        NECT4Family.Profilo__c = 'NEC_T.4';
        User NECA1 = AllDataFactory.getUser('14', profile.Id, 'Personal');
        NECA1.FederationIdentifier = '14';
        NECA1.Profilo__c = 'NEC_A.1';
        insert new List<User>{user, NECT4Personal, NECT4Family, NECA1, ufficioModelliDistributivi};
        
        Contact contactUffModDis = AllDataFactory.getContact('01', ufficioModelliDistributivi.Id, banca.id);
        contactUffModDis.PTF_Ruolo__c = '100';
        Contact contactNECT4Personal = AllDataFactory.getContact('02', NECT4Personal.Id, ufficioPersonal.id);
        contactNECT4Personal.PTF_Ruolo__c = '100';
        Contact contactNECT4Family = AllDataFactory.getContact('03', NECT4Family.Id, ufficioFamily.id);
        contactNECT4Family.PTF_Ruolo__c = '100';
        Contact contactNECA1 = AllDataFactory.getContact('04', NECA1.Id, area.id);
        contactNECA1.PTF_Ruolo__c = '100';
        System.runAs(user){
            insert new List<Contact>{contactUffModDis, contactNECT4Personal, contactNECT4Family, contactNECA1};
    
            ConfigurazioneSpostamenti__mdt iter = [ SELECT Id, MasterLabel, PTF_MDS_End__c, PTF_MDS_Start__c,
                                                PTF_Abi__c, Finestra_Temporale__c, Iter_Approvativo__c,
                                                PTF_Filiale_End__c, PTF_Filiale_Start__c, PTF_JSON_Approvatori__c, PTF_StessoReferente__c,
                                                PTF_CheckNaturaGiuridica__c, PTF_CheckCedSpecifico__c, PTF_CheckTipologiaFilialeDestinazione__c, PTF_CheckTipologiaFilialePartenza__c, Tipo_di_Spostamento__c
                                                ,PTF_SuperUsers__c
                                                FROM ConfigurazioneSpostamenti__mdt
                                                WHERE Tipo_di_Spostamento__c = 'MDS' AND PTF_Abi__c = '05387' AND
                                                PTF_MDS_Start__c = 'Personal' AND PTF_MDS_End__c = 'Family'];
                                                
                                                Map<String, SObject> ndgIterMap = new Map<String, SObject>{
                                                    personAccount.Id => iter
                                                };
                                                Map<String, String> ndgIterTypeMap = new Map<String, String>{
                                                    personAccount.Id => 'MDS'
            };
            Map<String, String> subjectMap = new Map<String, String>{
                personAccount.Id => 'MDS Personal - Family'
            };
            Map<String, String> configurationKeyMap = new Map<String, String>{
                personAccount.Id => 'Personal_Family'
            };
            RestRequest req = new RestRequest(); 
            RestResponse res = new RestResponse();
            
            req.requestURI = 'callout:CallMeBack/services/apexrest/createQueues';  
            req.httpMethod = 'POST';
            req.requestBody = Blob.valueof(JSON.serialize(
            new Map<String,Object>{
                'accountList' => new List<Account>{personAccount},
                'ndgIterMap' => ndgIterMap,
                'portafoglioDiPartenza' => microPortafoglioPersonal,
                'portafoglioDiDestinazione' => microPortafoglioFamily,
                'process' => ''
            }
            ));
            RestContext.request = req;
            RestContext.response = res;
            
            
            Map<String, Object> response = (Map<String, Object>)JSON.deserializeUntyped(CreateQueuesController.createQueues());
            System.debug('DK response: ' + JSON.serialize(response));
            Map<String, String> accountWorkOrderKeyMap = (Map<String, String>)JSON.deserialize((String)JSON.serialize(response.get('accountWorkOrderKeyMap')), Map<String, String>.class);
            System.debug('DK accountWorkOrderKeyMap: ' + JSON.serialize(accountWorkOrderKeyMap));
            Map<String, String> woStepMap = (Map<String, String>)JSON.deserialize((String)JSON.serialize(response.get('woStepMap')), Map<String, String>.class);
            System.debug('DK woStepMap: ' + JSON.serialize(woStepMap));
            // Test.stopTest();
    
            req = new RestRequest(); 
            res = new RestResponse();
    
            // req.requestURI = 'callout:CallMeBack/services/apexrest/createQueues';  
            req.httpMethod = 'PATCH';
            req.requestBody = Blob.valueof(JSON.serialize(
                new Map<String,Object>{
                    'ndgList' => new List<Account>{personAccount},
                    'ndgIterTypeMap' => ndgIterTypeMap,
                    'portafoglioDestinazione' => microPortafoglioFamily.Id,
                    'accountKeyMap' => accountWorkOrderKeyMap,
                    'currentNDGId' => personAccount.Id,
                    'gruppoFinanziarioId' => '',
                    'primari' => new List<String>{personAccount.id},
                    'woStepMap' => woStepMap,
                    'ownerId' => UserInfo.getuserId(),
                    'configurationKeyMap' => configurationKeyMap,
                    'subjectMap' => subjectMap,
                    'note' => 'TEST',
                    'process' => '',
                    'motivazione' => '',
                    'lineItemIter' => true
                }
            ));
    
            RestContext.request = req;
            RestContext.response = res;
            CreateQueuesController.sendMovementsRequest();

            IterConfiguration__c iterConfig = new IterConfiguration__c(
                UnitaOrganizzativa__c = filiale.Id,
                TipoSpostamento__c = 'MDS',
                GiorniAnnullamento__c = -1
            );
            insert iterConfig;
        }
    }

    @isTest
    public static void testBatch(){
        Test.startTest();
        Batch_CloseIter batch = new Batch_CloseIter();
        Id batchJobId = Database.executeBatch(batch, 50);
        Test.stopTest();
    }
}