BPER/DEVF/force-app/main/default/objects/ConfigurazioneSpostamenti__mdt/ConfigurazioneSpostamenti__mdt.object-meta.xml
<CustomObject>
    <label>Configurazione Spostamenti</label>
    <pluralLabel>Configurazione Spostamenti</pluralLabel>
</CustomObject>

BPER/DEVF/force-app/main/default/objects/ConfigurazioneSpostamenti__mdt/fields/Finestra_Temporale__c.field-meta.xml
<CustomField>
    <fullName>Finestra_Temporale__c</fullName>
    <defaultValue>false</defaultValue>
    <label>Finestra Temporale</label>
    <type>Checkbox</type>
</CustomField>

BPER/DEVF/force-app/main/default/objects/ConfigurazioneSpostamenti__mdt/fields/Iter_Approvativo__c.field-meta.xml
<CustomField>
    <fullName>Iter_Approvativo__c</fullName>
    <defaultValue>false</defaultValue>
    <label>Iter Approvativo</label>
    <type>Checkbox</type>
</CustomField>

BPER/DEVF/force-app/main/default/objects/ConfigurazioneSpostamenti__mdt/fields/PTF_Abi__c.field-meta.xml
<CustomField>
    <fullName>PTF_Abi__c</fullName>
    <label>Banca Permessa</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

BPER/DEVF/force-app/main/default/objects/ConfigurazioneSpostamenti__mdt/fields/PTF_CheckCedSpecifico__c.field-meta.xml
<CustomField>
    <fullName>PTF_CheckCedSpecifico__c</fullName>
    <label>Check Ced Specifico</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

BPER/DEVF/force-app/main/default/objects/ConfigurazioneSpostamenti__mdt/fields/PTF_CheckNaturaGiuridica__c.field-meta.xml
<CustomField>
    <fullName>PTF_CheckNaturaGiuridica__c</fullName>
    <label>Check Natura Giuridica</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

BPER/DEVF/force-app/main/default/objects/ConfigurazioneSpostamenti__mdt/fields/PTF_CheckTipologiaFilialeDestinazione__c.field-meta.xml
<CustomField>
    <fullName>PTF_CheckTipologiaFilialeDestinazione__c</fullName>
    <label>Check Tipologia Filiale di Destinazione</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

BPER/DEVF/force-app/main/default/objects/ConfigurazioneSpostamenti__mdt/fields/PTF_CheckTipologiaFilialePartenza__c.field-meta.xml
<CustomField>
    <fullName>PTF_CheckTipologiaFilialePartenza__c</fullName>
    <label>Check Tipologia Filiale di Partenza</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

BPER/DEVF/force-app/main/default/objects/ConfigurazioneSpostamenti__mdt/fields/PTF_Filiale_End__c.field-meta.xml
<CustomField>
    <fullName>PTF_Filiale_End__c</fullName>
    <label>Filiale End</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

BPER/DEVF/force-app/main/default/objects/ConfigurazioneSpostamenti__mdt/fields/PTF_Filiale_Start__c.field-meta.xml
<CustomField>
    <fullName>PTF_Filiale_Start__c</fullName>
    <label>Filiale Start</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

BPER/DEVF/force-app/main/default/objects/ConfigurazioneSpostamenti__mdt/fields/PTF_IsActive__c.field-meta.xml
<CustomField>
    <fullName>PTF_IsActive__c</fullName>
    <defaultValue>true</defaultValue>
    <label>Active</label>
    <type>Checkbox</type>
</CustomField>

BPER/DEVF/force-app/main/default/objects/ConfigurazioneSpostamenti__mdt/fields/PTF_JSON_Approvatori__c.field-meta.xml
<CustomField>
    <fullName>PTF_JSON_Approvatori__c</fullName>
    <label>JSON Approvatori</label>
    <length>131072</length>
    <type>LongTextArea</type>
</CustomField>

BPER/DEVF/force-app/main/default/objects/ConfigurazioneSpostamenti__mdt/fields/PTF_MDS_End__c.field-meta.xml
<CustomField>
    <fullName>PTF_MDS_End__c</fullName>
    <label>MDS End</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

BPER/DEVF/force-app/main/default/objects/ConfigurazioneSpostamenti__mdt/fields/PTF_MDS_Start__c.field-meta.xml
<CustomField>
    <fullName>PTF_MDS_Start__c</fullName>
    <label>MDS Start</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

BPER/DEVF/force-app/main/default/objects/ConfigurazioneSpostamenti__mdt/fields/PTF_StessoReferente__c.field-meta.xml
<CustomField>
    <fullName>PTF_StessoReferente__c</fullName>
    <defaultValue>false</defaultValue>
    <label>Stesso Referente</label>
    <type>Checkbox</type>
</CustomField>

BPER/DEVF/force-app/main/default/objects/ConfigurazioneSpostamenti__mdt/fields/PTF_SuperUsers__c.field-meta.xml
<CustomField>
    <fullName>PTF_SuperUsers__c</fullName>
    <label>Super Users</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

BPER/DEVF/force-app/main/default/objects/ConfigurazioneSpostamenti__mdt/fields/Tipo_di_Spostamento__c.field-meta.xml
<CustomField>
    <fullName>Tipo_di_Spostamento__c</fullName>
    <label>Tipo di Spostamento</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>MDS</fullName>
                <default>true</default>
                <label>MDS</label>
            </value>
            <value>
                <fullName>Filiale</fullName>
            </value>
            <value>
                <fullName>MDS / Filiale</fullName>
            </value>
            <value>
                <fullName>Referenti</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

BPER/DEVF/force-app/main/default/objects/ServiceModel__c/ServiceModel__c.object-meta.xml
<CustomObject>
    <label>Macro-modello di servizio</label>
    <nameField>
        <encryptionScheme>None</encryptionScheme>
        <label>Nome modello di servizio</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Macro-modelli di servizio</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

BPER/DEVF/force-app/main/default/objects/ServiceModel__c/fields/PTF_Division__c.field-meta.xml
<CustomField>
    <fullName>PTF_Division__c</fullName>
    <encryptionScheme>None</encryptionScheme>
    <label>Filiera</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

BPER/DEVF/force-app/main/default/objects/ServiceModel__c/fields/PTF_MacroDivision__c.field-meta.xml
<CustomField>
    <fullName>PTF_MacroDivision__c</fullName>
    <encryptionScheme>None</encryptionScheme>
    <label>Macrofiliera</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

BPER/DEVF/force-app/main/default/objects/Wallet__c/Wallet__c.object-meta.xml
<CustomObject>
    <label>Portafoglio</label>
    <nameField>
        <encryptionScheme>None</encryptionScheme>
        <label>Wallet Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Portafogli</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

BPER/DEVF/force-app/main/default/objects/Wallet__c/fields/PTF_ABI__c.field-meta.xml
<CustomField>
    <fullName>PTF_ABI__c</fullName>
    <formula>PTF_Banca__r.FinServ__BankNumber__c</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>ABI</label>
    <type>Text</type>
</CustomField>

BPER/DEVF/force-app/main/default/objects/Wallet__c/fields/PTF_Area__c.field-meta.xml
<CustomField>
    <fullName>PTF_Area__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Area</label>
    <referenceTo>Account</referenceTo>
    <relationshipLabel>Portafogli (Area)</relationshipLabel>
    <relationshipName>Portafogli2</relationshipName>
    <type>Lookup</type>
</CustomField>

BPER/DEVF/force-app/main/default/objects/Wallet__c/fields/PTF_Banca__c.field-meta.xml
<CustomField>
    <fullName>PTF_Banca__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Banca</label>
    <referenceTo>Account</referenceTo>
    <relationshipLabel>Portafogli</relationshipLabel>
    <relationshipName>Portafogli</relationshipName>
    <type>Lookup</type>
</CustomField>

BPER/DEVF/force-app/main/default/objects/Wallet__c/fields/PTF_BranchTypology__c.field-meta.xml
<CustomField>
    <fullName>PTF_BranchTypology__c</fullName>
    <formula>TEXT(PTF_Filiale__r.PTF_BranchTypology__c)</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>BranchTypology</label>
    <type>Text</type>
</CustomField>

BPER/DEVF/force-app/main/default/objects/Wallet__c/fields/PTF_DirezioneRegionale__c.field-meta.xml
<CustomField>
    <fullName>PTF_DirezioneRegionale__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Direzione Regionale</label>
    <referenceTo>Account</referenceTo>
    <relationshipLabel>Portafogli (Direzione Regionale)</relationshipLabel>
    <relationshipName>Portafogli1</relationshipName>
    <type>Lookup</type>
</CustomField>

BPER/DEVF/force-app/main/default/objects/Wallet__c/fields/PTF_Filiale__c.field-meta.xml
<CustomField>
    <fullName>PTF_Filiale__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Filiale</label>
    <referenceTo>Account</referenceTo>
    <relationshipLabel>Portafogli (Filiale)</relationshipLabel>
    <relationshipName>Filiali</relationshipName>
    <type>Lookup</type>
</CustomField>

BPER/DEVF/force-app/main/default/objects/Wallet__c/recordTypes/MicroWallet.recordType-meta.xml
<RecordType>
    <fullName>MicroWallet</fullName>
    <active>true</active>
    <label>Microportafoglio</label>
</RecordType>

BPER/PROD/force-app/main/default/classes/IterHandlerTest.cls
@istest
public with sharing class IterHandlerTest {
    @TestSetup
    static void makeData(){

        ServiceModel__c personal = new ServiceModel__c(Name = 'Personal',
        PTF_Division__c = 'PE',
        PTF_MacroDivision__c = 'WM');

        ServiceModel__c family = new ServiceModel__c(Name = 'Family',
        PTF_Division__c = 'PE',
        PTF_MacroDivision__c = 'EB');
        insert new List<ServiceModel__c>{personal, family};
        Account banca = AllDataFactory.getAccount('10', 'Banca');
        banca.FinServ__BankNumber__c = '05387';
        insert banca;
        Account dir = AllDataFactory.getAccount('09', 'DirezioneRegionale');
        dir.FinServ__BankNumber__c = '05387';
        dir.parentId = banca.Id;
        dir.PTF_Banca__c = banca.Id;
        insert dir;
        Account area = AllDataFactory.getAccount('08', 'Area');
        area.FinServ__BankNumber__c = '05387';
        area.parentId = dir.Id;
        area.PTF_Banca__c = banca.Id;
        area.PTF_DirezioneRegionale__c = dir.Id;
        insert area;
        Account filiale = AllDataFactory.getAccount('01', 'FilialeDiRelazione');
        filiale.FinServ__BankNumber__c = '05387';
        filiale.parentId = area.Id;
        filiale.PTF_BranchTypology__c = 'A';
        filiale.PTF_Banca__c = banca.Id;
        filiale.PTF_DirezioneRegionale__c = dir.Id;
        filiale.PTF_Area__c = area.Id;

        Account filiale2 = AllDataFactory.getAccount('30', 'FilialeDiRelazione');
        filiale2.FinServ__BankNumber__c = '05387';
        filiale2.parentId = area.Id;
        filiale2.PTF_BranchTypology__c = 'A';
        filiale2.PTF_Banca__c = banca.Id;
        filiale2.PTF_DirezioneRegionale__c = dir.Id;
        filiale2.PTF_Area__c = area.Id;
        insert new List<Account>{filiale, filiale2};
        Wallet__c microPortafoglioFamily = AllDataFactory.getWallet('MicroWallet',  filiale.Id, 'Family');
        Wallet__c microPortafoglioPersonal = AllDataFactory.getWallet('MicroWallet',  filiale2.Id, 'Personal');
        insert new List<Wallet__c>{microPortafoglioFamily, microPortafoglioPersonal};

        // Relazione Di Cointestazione
        Account personAccount = AllDataFactory.getAccount('01', 'PersonAccount');
        personAccount.PTF_Portafoglio__c = microPortafoglioPersonal.Id;
        personAccount.PTF_Filiale__c = filiale.Id;

        Account personAccount2 = AllDataFactory.getAccount('02', 'PersonAccount');
        personAccount2.PTF_Portafoglio__c = microPortafoglioFamily.Id;
        personAccount2.PTF_Filiale__c = filiale.Id;

        insert new List<Account>{personAccount, personAccount2};
        
        Profile profile = [SELECT id FROM Profile WHERE  Name =: Label.System_Administrator LIMIT 1];
        
        User user = AllDataFactory.getUser('10', profile.Id, 'Personal');
        user.FederationIdentifier='10';
        user.Profilo__c = 'ADMIN';
        insert new List<User>{user};
        
         WorkOrder wo = new WorkOrder(Status = 'pending', Queues__c = 'STEP1(NEC_F.1), STEP2(NEC_T.4, NEC_T.4), STEP3(NEC_A.1)', OriginalOwner__c = user.Id, PTF_Origine__c = microPortafoglioFamily.Id, PTF_Destinazione__c = microPortafoglioPersonal.Id, Step__c = '1');
         insert wo;
       
        
        Contact contact = AllDataFactory.getContact('02', user.Id, filiale.id);
        System.runAs(user){
            
            insert contact;
            ConfigurazioneSpostamenti__mdt iter = [ SELECT Id, MasterLabel, PTF_MDS_End__c, PTF_MDS_Start__c,
                                                PTF_Abi__c, Finestra_Temporale__c, Iter_Approvativo__c,
                                                PTF_Filiale_End__c, PTF_Filiale_Start__c, PTF_JSON_Approvatori__c, PTF_StessoReferente__c,
                                                PTF_CheckNaturaGiuridica__c, PTF_CheckCedSpecifico__c, PTF_CheckTipologiaFilialeDestinazione__c, PTF_CheckTipologiaFilialePartenza__c, Tipo_di_Spostamento__c
                                                ,PTF_SuperUsers__c
                                                FROM ConfigurazioneSpostamenti__mdt
                                                WHERE Tipo_di_Spostamento__c = 'MDS' AND PTF_Abi__c = '05387' AND
                                                PTF_MDS_Start__c = 'Personal' AND PTF_MDS_End__c = 'Family' AND 
                                                PTF_IsActive__c = true];
                                                
                                                Map<String, SObject> ndgIterMap = new Map<String, SObject>{
                                                    personAccount.Id => iter
                                                };
                                                Map<String, String> ndgIterTypeMap = new Map<String, String>{
                                                    personAccount.Id => 'MDS'
            };
            Map<String, String> subjectMap = new Map<String, String>{
                personAccount.Id => iter.MasterLabel
            };
            Map<String, String> configurationKeyMap = new Map<String, String>{
                personAccount.Id => 'Personal_Family'
            };
            RestRequest req = new RestRequest(); 
            RestResponse res = new RestResponse();
            
            req.requestURI = 'callout:CallMeBack/services/apexrest/createQueues';  
            req.httpMethod = 'POST';
            req.requestBody = Blob.valueof(JSON.serialize(
            new Map<String,Object>{
                'accountList' => new List<Account>{personAccount},
                'ndgIterMap' => ndgIterMap,
                'portafoglioDiPartenza' => microPortafoglioPersonal,
                'portafoglioDiDestinazione' => microPortafoglioFamily,
                'process' => ''
            }
            ));
            RestContext.request = req;
            RestContext.response = res;
            
            
            Map<String, Object> response = (Map<String, Object>)JSON.deserializeUntyped(CreateQueuesController.createQueues());
            System.debug('DK response: ' + JSON.serialize(response));
            Map<String, String> accountWorkOrderKeyMap = (Map<String, String>)JSON.deserialize((String)JSON.serialize(response.get('accountWorkOrderKeyMap')), Map<String, String>.class);
            System.debug('DK accountWorkOrderKeyMap: ' + JSON.serialize(accountWorkOrderKeyMap));
            Map<String, String> woStepMap = (Map<String, String>)JSON.deserialize((String)JSON.serialize(response.get('woStepMap')), Map<String, String>.class);
            System.debug('DK woStepMap: ' + JSON.serialize(woStepMap));
            // Test.stopTest();
    
            req = new RestRequest(); 
            res = new RestResponse();
    
            // req.requestURI = 'callout:CallMeBack/services/apexrest/createQueues';  
            req.httpMethod = 'PATCH';
            req.requestBody = Blob.valueof(JSON.serialize(
                new Map<String,Object>{
                    'ndgList' => new List<Account>{personAccount},
                    'ndgIterTypeMap' => ndgIterTypeMap,
                    'portafoglioDestinazione' => microPortafoglioFamily.Id,
                    'accountKeyMap' => accountWorkOrderKeyMap,
                    'currentNDGId' => personAccount.Id,
                    'gruppoFinanziarioId' => '',
                    'primari' => new List<String>{personAccount.id},
                    'woStepMap' => woStepMap,
                    'ownerId' => UserInfo.getuserId(),
                    'configurationKeyMap' => configurationKeyMap,
                    'subjectMap' => subjectMap,
                    'note' => 'TEST',
                    'process' => '',
                    'motivazione' => '',
                    'lineItemIter' => true
                }
            ));
    
            RestContext.request = req;
            RestContext.response = res;
            CreateQueuesController.sendMovementsRequest();
        }
    }

    @istest
    static void test() {
        User user = [SELECT id FROm user WHERE FederationIdentifier = '10' LIMIT 1];
        WorkOrder wo = [SELECT id FROM WorkOrder LIMIT 1];
        Test.startTest();
        System.runAs(user){

            RestRequest req = new RestRequest(); 
            RestResponse res = new RestResponse();

            req.requestURI = 'callout:CallMeBack/services/apexrest/iterHandler';  
            req.httpMethod = 'POST';
            req.requestBody = Blob.valueof(JSON.serialize(
                new Map<String,Object>{
                    wo.id => 'Annullato'
                }
            ));

            RestContext.request = req;
            RestContext.response = res;
            Test.setMock(HttpCalloutMock.class, new MockHttpResponse());
            IterHandler.annullater();
        }
        Test.stopTest();
        System.assertEquals(true, (IterHandler.annullater()) != null);
    }

    @istest
    static void testKO() {
        User user = [SELECT id FROm user WHERE FederationIdentifier = '10' LIMIT 1];
        WorkOrder wo = [SELECT id FROm WorkOrder LIMIT 1];
        Test.startTest();
        System.runAs(user){

            RestRequest req = new RestRequest(); 
            RestResponse res = new RestResponse();

            req.requestURI = 'callout:CallMeBack/services/apexrest/iterHandler';  
            req.httpMethod = 'POST';
            req.requestBody = Blob.valueof(JSON.serialize(
                new Map<String,Object>{
                     wo.id => ''
                }
            ));

            RestContext.request = req;
            RestContext.response = res;
            Test.setMock(HttpCalloutMock.class, new MockHttpResponse());
            try {
                
                IterHandler.annullater();
            } catch (Exception ex) {
                
                System.debug('DK Exception: ' + ex  + '; Stacktrace: ' + ex.getStackTraceString());
            }
        }
        Test.stopTest();
        System.assertEquals(true, (IterHandler.annullater()) !=null);
    }


    @istest
    static void testCloseIter() {
        User user = [SELECT id FROm user WHERE FederationIdentifier = '10' LIMIT 1];
        WorkOrder wo = [SELECT id FROm WorkOrder LIMIT 1];
        Test.startTest();
        System.runAs(user){

            RestRequest req = new RestRequest(); 
            RestResponse res = new RestResponse();

            req.requestURI = 'callout:CallMeBack/services/apexrest/iterHandler';  
            req.httpMethod = 'PATCH';
            req.requestBody = Blob.valueof(JSON.serialize(
                new Map<String,Object>{
                    'recordId' => wo.id,
                    'queueId' => '',
                    'status' => 'Approvato'
                }
            ));

            RestContext.request = req;
            RestContext.response = res;
            Test.setMock(HttpCalloutMock.class, new MockHttpResponse());
            IterHandler.closeIter();
        }
        Test.stopTest();
        System.assertEquals(true, IterHandler.closeIter() !=null);
    }
}