BPER/DEVF/force-app/main/default/objects/SocialCustomerServiceSettings__c/SocialCustomerServiceSettings__c.object-meta.xml
<CustomObject>
    <customSettingsType>Hierarchy</customSettingsType>
    <label>Social Customer Service Setting</label>
</CustomObject>

BPER/DEVF/force-app/main/default/objects/SocialCustomerServiceSettings__c/fields/FBPageAccessToken__c.field-meta.xml
<CustomField>
    <fullName>FBPageAccessToken__c</fullName>
    <encryptionScheme>None</encryptionScheme>
    <label>FB Page Access Token</label>
    <type>TextArea</type>
</CustomField>

BPER/DEVF/force-app/main/default/objects/SocialCustomerServiceSettings__c/fields/FBTakeHeadControlURL__c.field-meta.xml
<CustomField>
    <fullName>FBTakeHeadControlURL__c</fullName>
    <encryptionScheme>None</encryptionScheme>
    <label>FB Take Head Control URL</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

BPER/POLOWEALTH/force-app/main/default/classes/FBBotTakeHeadControl_Test.cls
@isTest
private class FBBotTakeHeadControl_Test {
    
    @testSetup static void setup() {
        insert new SocialCustomerServiceSettings__c(FBPageAccessToken__c = 'access_token', FBTakeHeadControlURL__c = 'www.example.com');
        
        Contact c = new Contact(LastName = 'Test');
        
        insert c;
        
        SocialPersona persona = new SocialPersona(Name = 'Test', Provider = 'Facebook', ParentId = c.Id, ExternalId = '0001');
        
        insert persona;
        
        List<Case> cases = new List<Case>();
        
        for (Integer i = 0; i < 10; i++){
            cases.add(new Case(SocialPersona__c = persona.Id, Origin = 'Facebook'));
        }
        
        insert cases;        
    }
    
    @isTest static void takeHeadControl() {
        Test.setMock(HttpCalloutMock.class, new FBMockGenerator());
        
        Map<Id, Case> cases = new Map<Id, Case>([SELECT Id FROM Case]);
        List<Id> ids = new List<Id>();
        
        ids.addAll(cases.KeySet());
        
        FBBotTakeHeadControl.takeHeadControl(ids);
    }
    
    class FBMockGenerator implements HttpCalloutMock {
        public HTTPResponse respond(HTTPRequest req) {
            HttpResponse res = new HttpResponse();
            res.setHeader('Content-Type', 'application/json');
            res.setBody('{"success": "true" }');
            res.setStatusCode(200);
            return res;
        }
    }
    
}