BPER/DEVF/force-app/main/default/objects/GenesysSetting__c/GenesysSetting__c.object-meta.xml
<CustomObject>
    <label>Genesys Setting</label>
    <nameField>
        <encryptionScheme>None</encryptionScheme>
        <label>Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Genesys Settings</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

BPER/DEVF/force-app/main/default/objects/GenesysSetting__c/fields/G_MEDIA_TYPE__c.field-meta.xml
<CustomField>
    <fullName>G_MEDIA_TYPE__c</fullName>
    <label>Media Type</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>chat</fullName>
            </value>
            <value>
                <fullName>whatsapp</fullName>
            </value>
            <value>
                <fullName>other</fullName>
            </value>
            <value>
                <fullName>web</fullName>
            </value>
            <value>
                <fullName>unbluchat</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

BPER/DEVF/force-app/main/default/objects/GenesysSetting__c/fields/G_PRIORITY__c.field-meta.xml
<CustomField>
    <fullName>G_PRIORITY__c</fullName>
    <label>Priorità Canale</label>
    <precision>3</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

BPER/DEVF/force-app/main/default/objects/GenesysSetting__c/fields/G_QUEUE_ID__c.field-meta.xml
<CustomField>
    <fullName>G_QUEUE_ID__c</fullName>
    <encryptionScheme>None</encryptionScheme>
    <label>ID Coda</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

BPER/DEVF/force-app/main/default/objects/GenesysSetting__c/fields/G_SCHEDULE_GROUP_ID__c.field-meta.xml
<CustomField>
    <fullName>G_SCHEDULE_GROUP_ID__c</fullName>
    <encryptionScheme>None</encryptionScheme>
    <label>ID Scheduling Group Chat</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

BPER/DEVF/force-app/main/default/objects/GenesysSetting__c/fields/S_MESSAGES_TIMEOUT__c.field-meta.xml
<CustomField>
    <fullName>S_MESSAGES_TIMEOUT__c</fullName>
    <encryptionScheme>None</encryptionScheme>
    <label>Timeout Sessione Messaging</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

BPER/DEVF/force-app/main/default/objects/GenesysSetting__c/fields/S_OMNI_ID__c.field-meta.xml
<CustomField>
    <fullName>S_OMNI_ID__c</fullName>
    <encryptionScheme>None</encryptionScheme>
    <label>ID Presence Status Ready</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

BPER/DEVF/force-app/main/default/objects/GenesysSetting__c/recordTypes/Chat.recordType-meta.xml
<RecordType>
    <fullName>Chat</fullName>
    <active>true</active>
    <label>Chat</label>
</RecordType>

BPER/DEVF/force-app/main/default/classes/ConnectorSchedul_Test.cls
@isTest
global class ConnectorSchedul_Test {
    
    @isTest 
    public static void testPostCallout(){
        ConnectorScheduleChat csc = new ConnectorScheduleChat();
        ConnectorMessagesEventPublish.createMessagesEvent();
           
        ExternalRoutingChat erc = new ExternalRoutingChat();
           
        GenesysSetting__c gs = new GenesysSetting__c();
        gs.Name = 'chat';
        gs.G_MEDIA_TYPE__c = 'chat';
        gs.G_PRIORITY__c = 5;
        gs.G_QUEUE_ID__c = '123';
        gs.G_SCHEDULE_GROUP_ID__c = '123';
        gs.S_MESSAGES_TIMEOUT__c = '';
        gs.S_OMNI_ID__c = '0N53X000000GrHK';
        insert gs;
        
        LiveChatVisitor lcv = new LiveChatVisitor();
        insert lcv;
        
        LiveChatTranscript lct = new LiveChatTranscript ();
        lct.LiveChatVisitorId = lcv.Id;
        insert lct;
         
        LiveChatTranscript livechatId = new LiveChatTranscript();
        livechatId = [select id, LiveChatDeploymentId, LiveChatButtonId, SkillId from LiveChatTranscript limit 1];    
        
        Test.startTest();
        ExternalRoutingChat.CalloutOutbound(lct.Id);
        Test.stopTest();
        
        List<String> ids = new List<String>{lct.Id};   
        ExternalRoutingChat.externalRouting(ids);
           
        HTTPResponse res = new HTTPResponse();
                res.setBody('{}');
                res.setStatusCode(200);
           Map<String, Object> params = new Map<String, Object>();
        ExternalRoutingChat.createTaskFromResponse(res, '123abc',params);
    }
}