BPER/DEVF/force-app/main/default/objects/GenesysSetting__c/GenesysSetting__c.object-meta.xml
<CustomObject>
    <label>Genesys Setting</label>
    <nameField>
        <encryptionScheme>None</encryptionScheme>
        <label>Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Genesys Settings</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

BPER/DEVF/force-app/main/default/objects/GenesysSetting__c/fields/G_MEDIA_TYPE__c.field-meta.xml
<CustomField>
    <fullName>G_MEDIA_TYPE__c</fullName>
    <label>Media Type</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>chat</fullName>
            </value>
            <value>
                <fullName>whatsapp</fullName>
            </value>
            <value>
                <fullName>other</fullName>
            </value>
            <value>
                <fullName>web</fullName>
            </value>
            <value>
                <fullName>unbluchat</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

BPER/DEVF/force-app/main/default/objects/GenesysSetting__c/fields/G_PRIORITY__c.field-meta.xml
<CustomField>
    <fullName>G_PRIORITY__c</fullName>
    <label>Priorità Canale</label>
    <precision>3</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

BPER/DEVF/force-app/main/default/objects/GenesysSetting__c/fields/G_QUEUE_ID__c.field-meta.xml
<CustomField>
    <fullName>G_QUEUE_ID__c</fullName>
    <encryptionScheme>None</encryptionScheme>
    <label>ID Coda</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

BPER/DEVF/force-app/main/default/objects/GenesysSetting__c/fields/G_SCHEDULE_GROUP_ID__c.field-meta.xml
<CustomField>
    <fullName>G_SCHEDULE_GROUP_ID__c</fullName>
    <encryptionScheme>None</encryptionScheme>
    <label>ID Scheduling Group Chat</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

BPER/DEVF/force-app/main/default/objects/GenesysSetting__c/fields/G_SKILL__c.field-meta.xml
<CustomField>
    <fullName>G_SKILL__c</fullName>
    <encryptionScheme>None</encryptionScheme>
    <label>Genesys Skill</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

BPER/DEVF/force-app/main/default/objects/GenesysSetting__c/fields/S_CHAT_BUTTON_ID__c.field-meta.xml
<CustomField>
    <fullName>S_CHAT_BUTTON_ID__c</fullName>
    <encryptionScheme>None</encryptionScheme>
    <label>ID Salesforce Chat Button</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

BPER/DEVF/force-app/main/default/objects/GenesysSetting__c/recordTypes/Chat.recordType-meta.xml
<RecordType>
    <fullName>Chat</fullName>
    <active>true</active>
    <label>Chat</label>
</RecordType>

BPER/DEVF/force-app/main/default/objects/GenesysSetting__c/recordTypes/Whatsapp.recordType-meta.xml
<RecordType>
    <fullName>Whatsapp</fullName>
    <active>true</active>
    <label>Whatsapp</label>
</RecordType>

BPER/PROD/force-app/main/default/classes/ExternalRouting_Test.cls
@isTest
global class ExternalRouting_Test {
    
    @isTest static void testExternalRouting(){
        ConnectorMessagesEventPublish.createMessagesEvent();
            
        ExternalRoutingChat erc = new ExternalRoutingChat();
            
        GenesysSetting__c gs = new GenesysSetting__c();
        gs.Name = 'chat';
        gs.G_MEDIA_TYPE__c = 'chat';
        gs.G_PRIORITY__c = 5;
        gs.G_QUEUE_ID__c = '123';
        gs.G_SCHEDULE_GROUP_ID__c = '123';
        gs.G_SKILL__c = 'skill';
        gs.S_CHAT_BUTTON_ID__c = '5733X000000HVuZQAW';
        insert gs;
        
        LiveChatTranscript lct = new LiveChatTranscript();
        lct.LiveChatDeploymentId = '5723X000000HVA8QAO';
        lct.LiveChatButtonId = '5733X000000HVuZQAW';
        lct.LiveChatVisitorId = '5713X0000061zAmQAI';
        insert lct;
        
        ConversationContextEntry cce = new ConversationContextEntry();
        cce.CustomDetailContextKey = 'Nome e cognome';
        cce.CustomDetailContextValue = 'Test Test';
        cce.ParentId = lct.Id;
        insert cce;
        
        List<String> ids = new List<String>{lct.Id}; 
            
        Test.startTest();
        ExternalRoutingChat.externalRouting(ids);
        Test.stopTest();
                
        ExternalRoutingChat.CalloutOutboundRemote(lct.Id);
                
        Object o;    
        HTTPResponse res = new HTTPResponse();
                res.setBody('{}');
                res.setStatusCode(200);
        Map<String, Object> params = new Map<String, Object>();
        ExternalRoutingChat.createTaskFromResponse(res, '123abc', params);
    }
    @isTest static void testExternalRoutingWA(){
        GenesysSetting__c gs = new GenesysSetting__c();
        gs.Name = 'Whatsapp';
        gs.G_MEDIA_TYPE__c = 'whatsapp';
        gs.G_PRIORITY__c = 5;
        gs.G_QUEUE_ID__c = '123';
        gs.G_SCHEDULE_GROUP_ID__c = '123';
        insert gs;
        
        MessagingChannel mc = [SELECT Id from MessagingChannel WHERE DeveloperName LIKE 'Whatsapp_IT_whatsapp%' LIMIT 1];
        
        MessagingEndUser mu = new MessagingEndUser();
        mu.Name = 'test';
        mu.MessagingPlatformKey = 'WhatsApp:+123';
        mu.MessagingChannelId = mc.Id;
        mu.MessageType = 'WhatsApp';
        insert mu;
        
        MessagingSession ms = new MessagingSession ();
        ms.MessagingChannelId = mc.Id;
        ms.MessagingEndUserId = mu.Id;
        ms.Status = 'Waiting';
        insert ms ;
        
        List<String> ids = new List<String>{ms.Id};
            
        Object o;
        
        Test.startTest();
        ExternalRoutingWhatsapp er = new ExternalRoutingWhatsapp(o);
        ExternalRoutingWhatsapp.pushToGcWithTId(ids);
        ExternalRoutingWhatsapp.CalloutOutbound(ms.Id);
        Test.stopTest();
    }
}