BPER/DEVF/force-app/main/default/objects/GenesysSetting__c/GenesysSetting__c.object-meta.xml
<CustomObject>
    <label>Genesys Setting</label>
    <nameField>
        <encryptionScheme>None</encryptionScheme>
        <label>Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Genesys Settings</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

BPER/DEVF/force-app/main/default/objects/GenesysSetting__c/fields/G_MEDIA_TYPE__c.field-meta.xml
<CustomField>
    <fullName>G_MEDIA_TYPE__c</fullName>
    <label>Media Type</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>chat</fullName>
            </value>
            <value>
                <fullName>whatsapp</fullName>
            </value>
            <value>
                <fullName>other</fullName>
            </value>
            <value>
                <fullName>web</fullName>
            </value>
            <value>
                <fullName>unbluchat</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

BPER/DEVF/force-app/main/default/objects/GenesysSetting__c/fields/G_MotivoDiContatto__c.field-meta.xml
<CustomField>
    <fullName>G_MotivoDiContatto__c</fullName>
    <inlineHelpText>Motivi di Contatto del Case</inlineHelpText>
    <label>Motivo di Contatto</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <sorted>true</sorted>
            <value>
                <fullName>Aggiunta carta prepagata in rubrica Smart</fullName>
            </value>
            <value>
                <fullName>Altri prodotti e servizi</fullName>
            </value>
            <value>
                <fullName>Attivazione carta</fullName>
            </value>
            <value>
                <fullName>Attivazione nuovo Internet Banking</fullName>
            </value>
            <value>
                <fullName>Blocco carta</fullName>
            </value>
            <value>
                <fullName>Blocco carta di debito Carige Cash</fullName>
            </value>
            <value>
                <fullName>Blocco credenziali di accesso</fullName>
            </value>
            <value>
                <fullName>Carte di pagamento</fullName>
            </value>
            <value>
                <fullName>Condizioni economiche</fullName>
            </value>
            <value>
                <fullName>Conto corrente</fullName>
            </value>
            <value>
                <fullName>Disposizioni trading Online</fullName>
            </value>
            <value>
                <fullName>Informazioni</fullName>
            </value>
            <value>
                <fullName>Informazioni carta</fullName>
            </value>
            <value>
                <fullName>Informazioni Polizza Sorriso</fullName>
            </value>
            <value>
                <fullName>Informazioni sugli investimenti</fullName>
            </value>
            <value>
                <fullName>Informazioni sui finanziamenti</fullName>
            </value>
            <value>
                <fullName>Internet Banking</fullName>
            </value>
            <value>
                <fullName>OFM</fullName>
            </value>
            <value>
                <fullName>Paga Poi</fullName>
            </value>
            <value>
                <fullName>Prestito Online</fullName>
            </value>
            <value>
                <fullName>Supporto app</fullName>
            </value>
            <value>
                <fullName>Supporto trading Online</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

BPER/DEVF/force-app/main/default/objects/GenesysSetting__c/fields/G_PRIORITY__c.field-meta.xml
<CustomField>
    <fullName>G_PRIORITY__c</fullName>
    <label>Priorità Canale</label>
    <precision>3</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

BPER/DEVF/force-app/main/default/objects/GenesysSetting__c/fields/G_QUEUE_ID__c.field-meta.xml
<CustomField>
    <fullName>G_QUEUE_ID__c</fullName>
    <encryptionScheme>None</encryptionScheme>
    <label>ID Coda</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

BPER/DEVF/force-app/main/default/objects/GenesysSetting__c/recordTypes/Web.recordType-meta.xml
<RecordType>
    <fullName>Web</fullName>
    <active>true</active>
    <description>Canale Web-To-Case</description>
    <label>Web</label>
</RecordType>

BPER/SIT/force-app/main/default/classes/ExternalRoutingWeb_Test.cls
@isTest
public class ExternalRoutingWeb_Test {
    static testMethod void myUnitTest4() {
        ExternalRoutingWeb erw = new ExternalRoutingWeb();
        Case c= new case(CRM_MotivoDellaChat__c='1234567890abcde', SuppliedName='customer name', G_LastAgentRouted__c = 'G_LastAgentRouted__c');
        insert c;
        List<String> ids = new List<String>{c.Id};
            
        Test.startTest();    
        ExternalRoutingWeb.CalloutOutbound(c.Id);
        Test.stopTest(); 
        HTTPResponse res = new HTTPResponse();
                res.setBody('{}');
                res.setStatusCode(200);
        ExternalRoutingWeb.externalRouting (ids);
        
        GenesysSetting__c gs = new GenesysSetting__c();
        gs.Name = 'WebCanale Web-To-Case';
        //gs.RecordTypeId = '0120D000000DyWHQA0';
        gs.RecordTypeId = Schema.SObjectType.GenesysSetting__c.getRecordTypeInfosByName().get('Web').getRecordTypeId();
        gs.G_MEDIA_TYPE__c = 'web';
        gs.G_PRIORITY__c = 5;
        gs.G_QUEUE_ID__c = '123';
        gs.G_MotivoDiContatto__c = 'Altri prodotti e servizi';
        insert gs;
         
        ExternalRoutingWeb.externalRouting (ids);
    }
}