BPER/DEVF/force-app/main/default/objects/CRM_Claims__c/CRM_Claims__c.object-meta.xml
<CustomObject>
    <label>Reclamo</label>
    <nameField>
        <encryptionScheme>None</encryptionScheme>
        <label>Numero Reclamo</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Reclami</pluralLabel>
    <sharingModel>Read</sharingModel>
</CustomObject>

BPER/DEVF/force-app/main/default/objects/CRM_Claims__c/fields/CRM_Account__c.field-meta.xml
<CustomField>
    <fullName>CRM_Account__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Account</label>
    <referenceTo>Account</referenceTo>
    <relationshipLabel>Reclami</relationshipLabel>
    <relationshipName>Claims</relationshipName>
    <type>Lookup</type>
</CustomField>

BPER/DEVF/force-app/main/default/objects/CRM_Claims__c/fields/CRM_Author__c.field-meta.xml
<CustomField>
    <fullName>CRM_Author__c</fullName>
    <encryptionScheme>CaseInsensitiveDeterministicEncryption</encryptionScheme>
    <label>Author</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

BPER/DEVF/force-app/main/default/objects/CRM_Claims__c/fields/CRM_Status__c.field-meta.xml
<CustomField>
    <fullName>CRM_Status__c</fullName>
    <label>Status</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>Open</fullName>
            </value>
            <value>
                <fullName>In progress</fullName>
            </value>
            <value>
                <fullName>Closed</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

BPER/DEVF/force-app/main/default/objects/CRM_Claims__c/fields/CRM_Subject__c.field-meta.xml
<CustomField>
    <fullName>CRM_Subject__c</fullName>
    <encryptionScheme>CaseInsensitiveDeterministicEncryption</encryptionScheme>
    <label>Subject</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

BPER/PROD/force-app/main/default/classes/OnCRMClaimsTriggerHandlerTest.cls
@isTest
public with sharing class OnCRMClaimsTriggerHandlerTest {
    @TestSetup
    public static void setup(){

        Profile profile = [SELECT id FROM Profile WHERE Name =: Label.System_Administrator LIMIT 1];
        User user = AllDataFactory.getUser('01', profile.Id, 'CORPORATE');
        insert user;

        System.runAs(user)
        {

            Account acc = AllDataFactory.getAccount('01', 'GruppoFinanziario');
            insert acc;

            CRM_Claims__c crmClaims = new CRM_Claims__c();
            crmClaims.CRM_Author__c='Administrator';
            crmClaims.CRM_Account__c=acc.id;
            crmClaims.CRM_Status__c='Closed';
            crmClaims.CRM_Subject__c='TEST';
            crmClaims.Name='12559';

            insert crmClaims;
        }

    }

    @IsTest
        static void testCRMClaim(){
            CRM_Claims__c crmClaim = [SELECT id,CRM_Subject__c FROM CRM_Claims__c WHERE name='12559'];
            crmClaim.CRM_Subject__c='TEST2';
            update crmClaim;
        }
}