BPER/DEVF/force-app/main/default/objects/ScheduledJob__c/ScheduledJob__c.object-meta.xml
<CustomObject>
    <label>ScheduledJob</label>
    <nameField>
        <encryptionScheme>None</encryptionScheme>
        <label>Nome ScheduledJob</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>ScheduledJob</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

BPER/DEVF/force-app/main/default/objects/Struttura_Banca__c/Struttura_Banca__c.object-meta.xml
<CustomObject>
    <label>Struttura Banca</label>
    <nameField>
        <encryptionScheme>None</encryptionScheme>
        <label>Nome Struttura Banca</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Struttura Banche</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

BPER/DEVF/force-app/main/default/objects/Struttura_Banca__c/fields/Stato__c.field-meta.xml
<CustomField>
    <fullName>Stato__c</fullName>
    <encryptionScheme>None</encryptionScheme>
    <label>Stato</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

BPER/CIB/force-app/main/default/classes/Batch_SganciaRuoliUtenteTest.cls
@isTest
public class Batch_SganciaRuoliUtenteTest {
    @testSetup static void setup() {
        List<Struttura_Banca__c> sbs = new List<Struttura_Banca__c>();
        Struttura_Banca__c sb1 = new Struttura_Banca__c(
            IdCed__c='12345',
            Stato__c='A'
        );
        Struttura_Banca__c sb2 = new Struttura_Banca__c(
            IdCed__c='12346',
            Stato__c='D'
        );
        sbs.add(sb1);
        sbs.add(sb2);
        
        insert sbs;
    }
    
    @isTest
    static void unitTest() {
        Test.startTest();
        Batch_SganciaRuoliUtente sgr = new Batch_SganciaRuoliUtente();
        sgr.initRunner(new List<ScheduledJob__c>());
        Database.executeBatch(sgr,200);
        Test.stopTest();
    }
}