BPER/DEVF/force-app/main/default/objects/ScheduledJob__c/ScheduledJob__c.object-meta.xml
<CustomObject>
    <label>ScheduledJob</label>
    <nameField>
        <encryptionScheme>None</encryptionScheme>
        <label>Nome ScheduledJob</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>ScheduledJob</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

BPER/DEVF/force-app/main/default/objects/ScheduledJob__c/fields/Descrizione__c.field-meta.xml
<CustomField>
    <fullName>Descrizione__c</fullName>
    <encryptionScheme>None</encryptionScheme>
    <label>Descrizione</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

BPER/DEVF/force-app/main/default/objects/Struttura_Banca__c/Struttura_Banca__c.object-meta.xml
<CustomObject>
    <label>Struttura Banca</label>
    <nameField>
        <encryptionScheme>None</encryptionScheme>
        <label>Nome Struttura Banca</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Struttura Banche</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

BPER/DEVF/force-app/main/default/objects/Struttura_Banca__c/fields/IDCed_Padre__c.field-meta.xml
<CustomField>
    <fullName>IDCed_Padre__c</fullName>
    <encryptionScheme>None</encryptionScheme>
    <label>IDCed Padre</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

BPER/DEVF/force-app/main/default/objects/Struttura_Banca__c/fields/Stato__c.field-meta.xml
<CustomField>
    <fullName>Stato__c</fullName>
    <encryptionScheme>None</encryptionScheme>
    <label>Stato</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

BPER/DEV/force-app/main/default/classes/Batch_CreaGerarchiaRuoli_Test.cls
@isTest
private class Batch_CreaGerarchiaRuoli_Test {
    
    @testSetup static void setup() {
        List<Struttura_Banca__c> sbs = new List<Struttura_Banca__c>();
        Struttura_Banca__c sb1 = new Struttura_Banca__c(
            IdCed__c='12347',
            Descrizione__c ='T12347',
            Stato__c='A'
        );
        Struttura_Banca__c sb2 = new Struttura_Banca__c(
            IdCed__c='12348',
            IDCed_Padre__c='12347',
            Descrizione__c ='T12348T12348T12348T12348T12348T12348T12348T12348T12348T12348T12348T12348T12348T12348T12348T12348T12348T12348T12348T12348T12348T12348',
            Stato__c='A'
        );
        sbs.add(sb1);
        sbs.add(sb2);
        
        insert sbs;
    }
    
    @isTest
    static void unitTest() {
        UserRole ur = new UserRole(
            Name = 'T12347',
            DeveloperName ='RIDCEDT12347'
        );
        insert ur;
        Test.startTest();
        Batch_CreaGerarchiaRuoli sgr = new Batch_CreaGerarchiaRuoli();
        sgr.initRunner(new List<ScheduledJob__c>());
        Database.executeBatch(sgr);
        Batch_CreaGerarchiaRuoli.findUserRoleByDevName(new Set<String>{'RIDCEDT12347'});
        Batch_CreaGerarchiaRuoli.createGroup(new List<UserRole>{ur},new Map<String,Set<String>>{'T12347'=>new Set<String>{'T12347'}});
        Test.stopTest();
    }
    
    @isTest
    static void unitTest1() {
        List<Struttura_Banca__c> sbs = [SELECT Id FROM Struttura_Banca__c];
        delete sbs;
        Test.startTest();
        Batch_CreaGerarchiaRuoli sgr = new Batch_CreaGerarchiaRuoli();
        sgr.initRunner(new List<ScheduledJob__c>());
        Database.executeBatch(sgr);
        Test.stopTest();
    }
}