BPER/DEVF/force-app/main/default/objects/CRM_IndicatoriCliente__c/CRM_IndicatoriCliente__c.object-meta.xml
<CustomObject>
    <description>Indicatori Commerciali, Economici, Reddituali e di Rischio di un cliente</description>
    <label>Indicatori Cliente</label>
    <nameField>
        <encryptionScheme>None</encryptionScheme>
        <label>Indicatori Cliente Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Indicatori Clienti</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

BPER/DEVF/force-app/main/default/objects/CRM_IndicatoriCliente__c/fields/CRM_Account__c.field-meta.xml
<CustomField>
    <fullName>CRM_Account__c</fullName>
    <deleteConstraint>Restrict</deleteConstraint>
    <label>Nome Cliente</label>
    <referenceTo>Account</referenceTo>
    <relationshipName>Rischio</relationshipName>
    <type>Lookup</type>
</CustomField>

BPER/DEVF/force-app/main/default/objects/CRM_IndicatoriCliente__c/fields/CRM_AltreFormeRaccDir__c.field-meta.xml
<CustomField>
    <fullName>CRM_AltreFormeRaccDir__c</fullName>
    <defaultValue>false</defaultValue>
    <label>Altre Forme Raccolta Diretta</label>
    <type>Checkbox</type>
</CustomField>

BPER/DEVF/force-app/main/default/objects/CRM_IndicatoriCliente__c/fields/CRM_CartaCredito__c.field-meta.xml
<CustomField>
    <fullName>CRM_CartaCredito__c</fullName>
    <defaultValue>false</defaultValue>
    <label>Carta di credito</label>
    <type>Checkbox</type>
</CustomField>

BPER/DEVF/force-app/main/default/objects/CRM_IndicatoriCliente__c/fields/CRM_CartaDebito__c.field-meta.xml
<CustomField>
    <fullName>CRM_CartaDebito__c</fullName>
    <defaultValue>false</defaultValue>
    <label>Carta di debito</label>
    <type>Checkbox</type>
</CustomField>

BPER/DEVF/force-app/main/default/objects/CRM_IndicatoriCliente__c/fields/CRM_CertificatiDeposito__c.field-meta.xml
<CustomField>
    <fullName>CRM_CertificatiDeposito__c</fullName>
    <defaultValue>false</defaultValue>
    <label>Certificati deposito</label>
    <type>Checkbox</type>
</CustomField>

BPER/DEVF/force-app/main/default/objects/CRM_IndicatoriCliente__c/fields/CRM_ContoCorrente__c.field-meta.xml
<CustomField>
    <fullName>CRM_ContoCorrente__c</fullName>
    <defaultValue>false</defaultValue>
    <label>Conto corrente</label>
    <type>Checkbox</type>
</CustomField>

BPER/DEVF/force-app/main/default/objects/CRM_IndicatoriCliente__c/fields/CRM_DepositiRisparmio__c.field-meta.xml
<CustomField>
    <fullName>CRM_DepositiRisparmio__c</fullName>
    <defaultValue>false</defaultValue>
    <label>Depositi a risparmio</label>
    <type>Checkbox</type>
</CustomField>

BPER/DEVF/force-app/main/default/objects/CRM_IndicatoriCliente__c/recordTypes/Storico.recordType-meta.xml
<RecordType>
    <fullName>Storico</fullName>
    <active>true</active>
    <label>Storico</label>
</RecordType>

BPER/DEVF/force-app/main/default/objects/CRM_LinkedNDG__c/CRM_LinkedNDG__c.object-meta.xml
<CustomObject>
    <label>NDG collegati</label>
    <nameField>
        <displayFormat>NDGCollegati-{0000000000}</displayFormat>
        <label>Nome NDG collegati</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>NDG collegati</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

BPER/DEVF/force-app/main/default/objects/CRM_LinkedNDG__c/fields/CRM_Account__c.field-meta.xml
<CustomField>
    <fullName>CRM_Account__c</fullName>
    <deleteConstraint>Restrict</deleteConstraint>
    <label>Account</label>
    <referenceTo>Account</referenceTo>
    <relationshipLabel>NDG collegati</relationshipLabel>
    <relationshipName>NDG_collegati</relationshipName>
    <required>true</required>
    <type>Lookup</type>
</CustomField>

BPER/DEVF/force-app/main/default/objects/CRM_LinkedNDG__c/fields/CRM_CheckCodiceCollCompagine__c.field-meta.xml
<CustomField>
    <fullName>CRM_CheckCodiceCollCompagine__c</fullName>
    <formula>OR (
				CRM_LinkCode__c = &apos;102&apos;,
				CRM_LinkCode__c = &apos;103&apos;,
				CRM_LinkCode__c = &apos;104&apos;,
				CRM_LinkCode__c = &apos;105&apos;,
				CRM_LinkCode__c = &apos;106&apos;,
				CRM_LinkCode__c = &apos;107&apos;,
				CRM_LinkCode__c = &apos;108&apos;,
				CRM_LinkCode__c = &apos;109&apos;,
				CRM_LinkCode__c = &apos;110&apos;,
				CRM_LinkCode__c = &apos;111&apos;,
				CRM_LinkCode__c = &apos;112&apos;,
				CRM_LinkCode__c = &apos;113&apos;,
				CRM_LinkCode__c = &apos;116&apos;,
				CRM_LinkCode__c = &apos;117&apos;,
				CRM_LinkCode__c = &apos;121&apos;,
				CRM_LinkCode__c = &apos;122&apos;,
				CRM_LinkCode__c = &apos;123&apos;,
				CRM_LinkCode__c = &apos;134&apos;,
				CRM_LinkCode__c = &apos;135&apos;,
				CRM_LinkCode__c = &apos;137&apos;,
				CRM_LinkCode__c = &apos;139&apos;,
				CRM_LinkCode__c = &apos;164&apos;,
				CRM_LinkCode__c = &apos;165&apos;,
				CRM_LinkCode__c = &apos;166&apos;,
				CRM_LinkCode__c = &apos;167&apos;,
                                CRM_LinkCode__c = &apos;300&apos;,
                                CRM_LinkCode__c = &apos;302&apos;
)</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>Check codice collegamento - compagine</label>
    <type>Checkbox</type>
</CustomField>

BPER/DEVF/force-app/main/default/objects/CRM_LinkedNDG__c/fields/CRM_LinkCode__c.field-meta.xml
<CustomField>
    <fullName>CRM_LinkCode__c</fullName>
    <encryptionScheme>None</encryptionScheme>
    <label>Link Code</label>
    <length>255</length>
    <required>true</required>
    <type>Text</type>
</CustomField>

BPER/DEVF/force-app/main/default/objects/CRM_LinkedNDG__c/fields/CRM_LinkType__c.field-meta.xml
<CustomField>
    <fullName>CRM_LinkType__c</fullName>
    <encryptionScheme>None</encryptionScheme>
    <label>Link Type</label>
    <length>255</length>
    <required>true</required>
    <type>Text</type>
</CustomField>

BPER/DEVF/force-app/main/default/objects/CRM_LinkedNDG__c/fields/CRM_RelatedAccount__c.field-meta.xml
<CustomField>
    <fullName>CRM_RelatedAccount__c</fullName>
    <deleteConstraint>Restrict</deleteConstraint>
    <label>Related Account</label>
    <referenceTo>Account</referenceTo>
    <relationshipLabel>NDG collegati (Related Account)</relationshipLabel>
    <relationshipName>CRM_LinkedNDG</relationshipName>
    <required>true</required>
    <type>Lookup</type>
</CustomField>

BPER/DEVF/force-app/main/default/objects/CRM_LinkedNDG__c/fields/CRM_Status__c.field-meta.xml
<CustomField>
    <fullName>CRM_Status__c</fullName>
    <label>Status</label>
    <required>true</required>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>A</fullName>
            </value>
            <value>
                <fullName>E</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

BPER/PROD/force-app/main/default/classes/DynamicTablesControllerTest.cls
/*
AL 2022-08-24 -- Aggiunta del parametro CRM_NaturaGiuridica__c
                 Aggiunta di un'altra Account  e aggiunta di CRM_LinkedNDG__c
                 Aggiunta chiamata a metodo con atro oggetto 
                 Aggiunta di parametro 
*/

@isTest
public with sharing class DynamicTablesControllerTest {
    
    @TestSetup
    static void setup(){ 
        Account personAccount = AllDataFactory.getAccount('05', 'PersonAccount');
        personAccount.CRM_NaturaGiuridica__c = 'DI'; 
        // AL 2022-08-24 -- Aggiunta del parametro CRM_NaturaGiuridica__c
        // AL 2022-08-24 -- Aggiunta di un'altra Account 
        System.debug('personAccount TESTTTT: '+personAccount);
        Account personAccount1 = AllDataFactory.getAccount('05', 'PersonAccount');
        personAccount1.CRM_NaturaGiuridica__c = 'DI1';
        System.debug('personAccount11111 TESTTTT: '+personAccount1);

        insert new List<Account> { personAccount, personAccount1
        };
        // AL 2022-08-24 -- Fine
        //insert personAccount;
        
        CRM_IndicatoriCliente__c data = new CRM_IndicatoriCliente__c(
            CRM_Account__c = personAccount.Id,
            CRM_ContoCorrente__c = true,
            CRM_CartaDebito__c= false,
        	CRM_CartaCredito__c = false,
        	CRM_DepositiRisparmio__c = false,
        	CRM_CertificatiDeposito__c = false,
        	CRM_AltreFormeRaccDir__c = true);
        
        insert data;
        
        // AL 2022-08-24 -- Aggiunta dell'oggetto CRM_LinkedNDG__c
        CRM_LinkedNDG__c c = new CRM_LinkedNDG__c(
            CRM_RelatedAccount__c = personAccount.id
            , CRM_Account__c = personAccount.id
            , CRM_LinkCode__c = '103' // Per avere CRM_CheckCodiceCollCompagine__c = true 
            , CRM_Status__c = 'A' 
            , CRM_LinkType__c = 'TITOLARE D.I.'
        );
        CRM_LinkedNDG__c c1 = new CRM_LinkedNDG__c(
            CRM_RelatedAccount__c = personAccount.Id
            , CRM_Account__c = personAccount.Id
            , CRM_LinkCode__c = '102' // Per avere CRM_CheckCodiceCollCompagine__c = true 
            , CRM_Status__c = 'A' 
            , CRM_LinkType__c = 'TITOLARE D.I.'
        );
     insert new List<CRM_LinkedNDG__c> { c1, c
        };
        }
        //insert c;

        // AL 2022-08-24 -- Fine 
    
    
    
    @isTest
    static void unitTest1() {
        system.debug('cccc');
        String idAccount = [SELECT CRM_Account__c FROM CRM_IndicatoriCliente__c LIMIT 1].CRM_Account__c;
        System.debug('idAccount '+ idAccount);
        String oggetto = 'CRM_IndicatoriCliente__c';
        String lookup = 'CRM_Account__c';
        String fiejS= 'CRM_TabellaEntiSegnalanti.js';
        String RecordType= 'Storico';
        Map<String,Object> x =new Map<String,Object>();
        Test.startTest();
        try{
           x = DynamicTablesController.getObjectInfos(oggetto ,lookup,idAccount, RecordType
            , fiejS  // AL 2022-08-24 -- Aggiunta di parametro  
            );      
    
            // AL 2022-08-24 -- Aggiunta chiamata a metodo con atro oggetto 
            x = DynamicTablesController.getObjectInfos('oggetto', lookup, idAccount, RecordType, fiejS);      
            // AL 2022-08-24 -- Fine 
        } catch(Exception e) {

        }
        Test.stopTest();
        System.assertEquals(true, x.size()>0);
    }

    @isTest
    static void unitTest2() {
        
        String idAccount = [SELECT  CRM_Account__c FROM CRM_IndicatoriCliente__c LIMIT 1].Id;
        String oggetto = 'CRM_IndicatoriCliente__c';
        String lookup = 'CRM_Account__c';
         String fiejS= 'CRM_TabellaEntiSegnalanti.js';
        String RecordType= 'Storico';
        Map<String,Object> x =new Map<String,Object>();
        Test.startTest();
        try{
		 x = DynamicTablesController.getObjectInfos(oggetto ,lookup,idAccount, RecordType
            , fiejS  // AL 2022-08-24 -- Aggiunta di parametro 
            );
        }
        catch(Exception e) {

        }
        Test.stopTest();
        System.assertEquals(false, x.size()>0);
    }

}