BPER/DEVF/force-app/main/default/objects/CRM_IndicatoriCliente__c/CRM_IndicatoriCliente__c.object-meta.xml
<CustomObject>
    <description>Indicatori Commerciali, Economici, Reddituali e di Rischio di un cliente</description>
    <label>Indicatori Cliente</label>
    <nameField>
        <encryptionScheme>None</encryptionScheme>
        <label>Indicatori Cliente Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Indicatori Clienti</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

BPER/DEVF/force-app/main/default/objects/CRM_IndicatoriCliente__c/fields/CRM_Account__c.field-meta.xml
<CustomField>
    <fullName>CRM_Account__c</fullName>
    <deleteConstraint>Restrict</deleteConstraint>
    <label>Nome Cliente</label>
    <referenceTo>Account</referenceTo>
    <relationshipName>Rischio</relationshipName>
    <type>Lookup</type>
</CustomField>

BPER/DEVF/force-app/main/default/objects/CRM_IndicatoriCliente__c/fields/CRM_CRMeseDiRiferimento__c.field-meta.xml
<CustomField>
    <fullName>CRM_CRMeseDiRiferimento__c</fullName>
    <encryptionScheme>None</encryptionScheme>
    <label>Mese di Riferimento</label>
    <type>Date</type>
</CustomField>

BPER/DEVF/force-app/main/default/objects/CRM_IndicatoriCliente__c/recordTypes/Testa.recordType-meta.xml
<RecordType>
    <fullName>Testa</fullName>
    <active>true</active>
    <label>Testa</label>
</RecordType>

BPER/DEVF/force-app/main/default/objects/CRM_LinkedNDG__c/CRM_LinkedNDG__c.object-meta.xml
<CustomObject>
    <label>NDG collegati</label>
    <nameField>
        <displayFormat>NDGCollegati-{0000000000}</displayFormat>
        <label>Nome NDG collegati</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>NDG collegati</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

BPER/DEVF/force-app/main/default/objects/CRM_LinkedNDG__c/fields/CRM_Account__c.field-meta.xml
<CustomField>
    <fullName>CRM_Account__c</fullName>
    <deleteConstraint>Restrict</deleteConstraint>
    <label>Account</label>
    <referenceTo>Account</referenceTo>
    <relationshipLabel>NDG collegati</relationshipLabel>
    <relationshipName>NDG_collegati</relationshipName>
    <required>true</required>
    <type>Lookup</type>
</CustomField>

BPER/DEVF/force-app/main/default/objects/CRM_LinkedNDG__c/fields/CRM_CheckCodiceCollCompagine__c.field-meta.xml
<CustomField>
    <fullName>CRM_CheckCodiceCollCompagine__c</fullName>
    <formula>OR (
				CRM_LinkCode__c = &apos;102&apos;,
				CRM_LinkCode__c = &apos;103&apos;,
				CRM_LinkCode__c = &apos;104&apos;,
				CRM_LinkCode__c = &apos;105&apos;,
				CRM_LinkCode__c = &apos;106&apos;,
				CRM_LinkCode__c = &apos;107&apos;,
				CRM_LinkCode__c = &apos;108&apos;,
				CRM_LinkCode__c = &apos;109&apos;,
				CRM_LinkCode__c = &apos;110&apos;,
				CRM_LinkCode__c = &apos;111&apos;,
				CRM_LinkCode__c = &apos;112&apos;,
				CRM_LinkCode__c = &apos;113&apos;,
				CRM_LinkCode__c = &apos;116&apos;,
				CRM_LinkCode__c = &apos;117&apos;,
				CRM_LinkCode__c = &apos;121&apos;,
				CRM_LinkCode__c = &apos;122&apos;,
				CRM_LinkCode__c = &apos;123&apos;,
				CRM_LinkCode__c = &apos;134&apos;,
				CRM_LinkCode__c = &apos;135&apos;,
				CRM_LinkCode__c = &apos;137&apos;,
				CRM_LinkCode__c = &apos;139&apos;,
				CRM_LinkCode__c = &apos;164&apos;,
				CRM_LinkCode__c = &apos;165&apos;,
				CRM_LinkCode__c = &apos;166&apos;,
				CRM_LinkCode__c = &apos;167&apos;,
                                CRM_LinkCode__c = &apos;300&apos;,
                                CRM_LinkCode__c = &apos;302&apos;
)</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>Check codice collegamento - compagine</label>
    <type>Checkbox</type>
</CustomField>

BPER/DEVF/force-app/main/default/objects/CRM_LinkedNDG__c/fields/CRM_LinkType__c.field-meta.xml
<CustomField>
    <fullName>CRM_LinkType__c</fullName>
    <encryptionScheme>None</encryptionScheme>
    <label>Link Type</label>
    <length>255</length>
    <required>true</required>
    <type>Text</type>
</CustomField>

BPER/DEVF/force-app/main/default/objects/CRM_LinkedNDG__c/fields/CRM_RelatedAccount__c.field-meta.xml
<CustomField>
    <fullName>CRM_RelatedAccount__c</fullName>
    <deleteConstraint>Restrict</deleteConstraint>
    <label>Related Account</label>
    <referenceTo>Account</referenceTo>
    <relationshipLabel>NDG collegati (Related Account)</relationshipLabel>
    <relationshipName>CRM_LinkedNDG</relationshipName>
    <required>true</required>
    <type>Lookup</type>
</CustomField>

BPER/DEVF/force-app/main/default/objects/CRM_LinkedNDG__c/fields/CRM_Status__c.field-meta.xml
<CustomField>
    <fullName>CRM_Status__c</fullName>
    <label>Status</label>
    <required>true</required>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>A</fullName>
            </value>
            <value>
                <fullName>E</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

BPER/PROD/force-app/main/default/classes/DynamicTablesController.cls
/*
AL 2022-08-24 -- Aggiunta query ad Account e CRM_LinkedNDR__c e condizione sul recordId  
                 Aggiunta di parametro  a getObjectInfos
*/

public with sharing class DynamicTablesController {



    @AuraEnabled
    public static Map<String,Object> getObjectInfos (String obj, String field_lookup, String recordId, String recordTypeDeveloperName
    , String fileJS // AL 2022-08-24 -- Aggiunta di parametro 
    ) {

        System.debug('GB getObjectInfos obj: '+obj);
        System.debug('GB getObjectInfos field_lookup: '+field_lookup);
        System.debug('GB getObjectInfos recordTypeDeveloperName: '+recordTypeDeveloperName);
        System.debug('GB getObjectInfos recordId: '+recordId);
        System.debug('GB getObjectInfos fileJS: '+fileJS);

        String recordTypeDeveloperNameCondition = '';
        Map<String,Object> maptest = new Map<String,Object>();

        if(recordTypeDeveloperName != null && obj != 'CRM_IndicatoriCliente__c'){ recordTypeDeveloperNameCondition = ' AND RecordType.DeveloperName = \'' + String.escapeSingleQuotes(recordTypeDeveloperName) + '\'';}
        // AL 2022-08-24 -- Aggiunta query ad Account e CRM_LinkedNDR__c
        Account acc = [SELECT Id, CRM_NaturaGiuridica__c
                       FROM   Account 
                       WHERE  Id = :recordId];
        List<CRM_LinkedNDG__c> crmlinkeds = new List<CRM_LinkedNDG__c>();                
        if(acc.CRM_NaturaGiuridica__c == 'DI' && fileJS == 'CRM_TabellaEntiSegnalanti.js') {
            crmlinkeds = [SELECT CRM_RelatedAccount__c
                                FROM   CRM_LinkedNDG__c 
                                WHERE  CRM_Account__c = :recordId 
                                AND CRM_CheckCodiceCollCompagine__c = true 
                                AND CRM_Status__c = 'A' 
                                AND CRM_LinkType__c = 'TITOLARE D.I.'];
        }
        // AL 2022-08-24 -- Fine
        String additionalCriterias;
        
        if(obj == 'CRM_IndicatoriCliente__c'){
            additionalCriterias = ' AND RecordType.DeveloperName != \'Testa\' ORDER BY CRM_CRMeseDiRiferimento__c DESC LIMIT 13';
        } else {additionalCriterias = ' LIMIT 1';}
        
        String query = String.escapeSingleQuotes(SV_Utilities.selectAllField(obj));
        
        query += ' WHERE ' + String.escapeSingleQuotes(field_lookup) +  ' = \'' 
            + ( acc.CRM_NaturaGiuridica__c == 'DI' && crmlinkeds.size() > 0 ? String.escapeSingleQuotes(crmlinkeds.get(0).CRM_RelatedAccount__c) : String.escapeSingleQuotes(recordId) ) // AL 2022-08-24 -- Aggiunta condizione sul recordId
            //+ recordId
                + '\'' + recordTypeDeveloperNameCondition + additionalCriterias;
        System.debug(query); 
        try{
            List<sObject> slist = Database.query(query);

            System.debug('GB ObjRecord size: '+slist.size());
            System.debug('GB ObjRecord '+slist);
            
                maptest.put(recordId,slist );

        }
        catch (Exception e) { throw new AuraHandledException('Error Message: '+ e.getMessage());} 
        
        return maptest;
    }
}