BPER/DEVF/force-app/main/default/objects/CampaignMember__c/CampaignMember__c.object-meta.xml
<CustomObject>
    <label>CampaignMember Ghost</label>
    <nameField>
        <displayFormat>CM-{00000}</displayFormat>
        <label>CampaignMember Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>CampaignMembers</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

BPER/DEVF/force-app/main/default/objects/CampaignMember__c/fields/Campaign__c.field-meta.xml
<CustomField>
    <fullName>Campaign__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Campaign</label>
    <referenceTo>Campaign</referenceTo>
    <relationshipLabel>CampaignMembers</relationshipLabel>
    <relationshipName>CampaignMembers</relationshipName>
    <type>Lookup</type>
</CustomField>

BPER/DEVF/force-app/main/default/objects/CampaignMember__c/fields/CRM_Account__c.field-meta.xml
<CustomField>
    <fullName>CRM_Account__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>NDG</label>
    <referenceTo>Account</referenceTo>
    <relationshipLabel>CampaignMembers</relationshipLabel>
    <relationshipName>CampaignMembers</relationshipName>
    <type>Lookup</type>
</CustomField>

BPER/DEVF/force-app/main/default/objects/CampaignMember__c/fields/PTF_Portafoglio__c.field-meta.xml
<CustomField>
    <fullName>PTF_Portafoglio__c</fullName>
    <label>Portafoglio</label>
    <referenceTo>Wallet__c</referenceTo>
    <relationshipLabel>CampaignMembers</relationshipLabel>
    <relationshipName>CampaignMembers</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <reparentableMasterDetail>true</reparentableMasterDetail>
    <type>MasterDetail</type>
</CustomField>

BPER/DEVF/force-app/main/default/objects/Wallet__c/Wallet__c.object-meta.xml
<CustomObject>
    <label>Portafoglio</label>
    <nameField>
        <encryptionScheme>None</encryptionScheme>
        <label>Wallet Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Portafogli</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

BPER/DEVF/force-app/main/default/objects/Wallet__c/fields/PTF_Area__c.field-meta.xml
<CustomField>
    <fullName>PTF_Area__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Area</label>
    <referenceTo>Account</referenceTo>
    <relationshipLabel>Portafogli (Area)</relationshipLabel>
    <relationshipName>Portafogli2</relationshipName>
    <type>Lookup</type>
</CustomField>

BPER/DEVF/force-app/main/default/objects/Wallet__c/fields/PTF_Banca__c.field-meta.xml
<CustomField>
    <fullName>PTF_Banca__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Banca</label>
    <referenceTo>Account</referenceTo>
    <relationshipLabel>Portafogli</relationshipLabel>
    <relationshipName>Portafogli</relationshipName>
    <type>Lookup</type>
</CustomField>

BPER/DEVF/force-app/main/default/objects/Wallet__c/fields/PTF_BranchTypology__c.field-meta.xml
<CustomField>
    <fullName>PTF_BranchTypology__c</fullName>
    <formula>TEXT(PTF_Filiale__r.PTF_BranchTypology__c)</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>BranchTypology</label>
    <type>Text</type>
</CustomField>

BPER/DEVF/force-app/main/default/objects/Wallet__c/fields/PTF_DirezioneRegionale__c.field-meta.xml
<CustomField>
    <fullName>PTF_DirezioneRegionale__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Direzione Regionale</label>
    <referenceTo>Account</referenceTo>
    <relationshipLabel>Portafogli (Direzione Regionale)</relationshipLabel>
    <relationshipName>Portafogli1</relationshipName>
    <type>Lookup</type>
</CustomField>

BPER/DEVF/force-app/main/default/objects/Wallet__c/fields/PTF_Filiale__c.field-meta.xml
<CustomField>
    <fullName>PTF_Filiale__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Filiale</label>
    <referenceTo>Account</referenceTo>
    <relationshipLabel>Portafogli (Filiale)</relationshipLabel>
    <relationshipName>Filiali</relationshipName>
    <type>Lookup</type>
</CustomField>

BPER/DEVF/force-app/main/default/objects/Wallet__c/recordTypes/MicroWallet.recordType-meta.xml
<RecordType>
    <fullName>MicroWallet</fullName>
    <active>true</active>
    <label>Microportafoglio</label>
</RecordType>

BPER/UAT/force-app/main/default/classes/CRM_AttributiCampagneTableControllerTest.cls
@istest
public class CRM_AttributiCampagneTableControllerTest {
    @TestSetup
    static void makeData(){

        Account banca = AllDataFactory.getAccount('01', 'Banca');
        banca.FinServ__BankNumber__c = '05387';
        insert banca;
        Account dir = AllDataFactory.getAccount('02', 'DirezioneRegionale');
        dir.FinServ__BankNumber__c = '05387';
        dir.parentId = banca.Id;
        dir.PTF_Banca__c = banca.Id;
        insert dir;
        Account area = AllDataFactory.getAccount('03', 'Area');
        area.FinServ__BankNumber__c = '05387';
        area.parentId = dir.Id;
        area.PTF_Banca__c = banca.Id;
        area.PTF_DirezioneRegionale__c = dir.Id;
        insert area;
        Account filiale = AllDataFactory.getAccount('04', 'FilialeDiRelazione');
        filiale.FinServ__BankNumber__c = '05387';
        filiale.parentId = area.Id;
        filiale.PTF_BranchTypology__c = 'A';
        filiale.PTF_Banca__c = banca.Id;
        filiale.PTF_DirezioneRegionale__c = dir.Id;
        filiale.PTF_Area__c = area.Id;
        insert filiale;
        
        Profile profile = [SELECT id FROM Profile WHERE  Name =: Label.System_Administrator LIMIT 1];

        User titolare = AllDataFactory.getUser('14', profile.Id, 'CORPORATE');
        titolare.FederationIdentifier = '14';
        titolare.Profilo__c = 'NEC_F.1';
        
        insert titolare;
        
        User refPrivate = AllDataFactory.getUser('15', profile.Id, 'PRIVATE');
        refPrivate.FederationIdentifier = '15';
        refPrivate.PTF_RuoloLDAP__c ='069';
        refPrivate.Profilo__c = 'NEC_F.1';
        
        insert refPrivate;
        Wallet__c microPortafoglioCORPORATE;
		System.runAs(titolare){
            microPortafoglioCORPORATE = AllDataFactory.getWallet('MicroWallet',  filiale.Id, 'CORPORATE');
            insert microPortafoglioCORPORATE;
 		}
        Account business = AllDataFactory.getAccount('05', 'IndustriesBusiness');
        business.PTF_Portafoglio__c = microPortafoglioCORPORATE.Id;
        business.PTF_Filiale__c = filiale.Id;
        business.CRM_Filiale__c = filiale.Id;
        business.CRM_NDG__c = 'Account05';
        insert business;

        

        String recordTypeTopDownMono = Schema.SObjectType.Campaign.getRecordTypeInfosByName().get('Top-Down - Monostep').getRecordTypeId();
        Campaign campaign = AllDataFactory.getCampaign('01', titolare.Id, recordTypeTopDownMono);
        campaign.CRM_NomeAttributo1__c =null;
        campaign.CRM_NomeAttributo2__c =null;
        insert campaign;

        System.runAs(titolare){
            
            Contact contact = AllDataFactory.getContact('01', titolare.Id, filiale.id);
            contact.PTF_ProfiloLDAP__c='NEC_F.1';
            Contact referente = AllDataFactory.getContact('02', null, business.id);
            insert new List<Contact>{contact, referente};
            
            CampaignMember campaignMember = AllDataFactory.getCampaignMember('01', campaign.Id, referente.Id, titolare.Id);
            campaignMember.CRM_Portafoglio__c = microPortafoglioCORPORATE.Id;
            insert CampaignMember;
            
            CampaignMember__c cmg = New CampaignMember__c();
            cmg.Campaign__c = campaign.Id;
            cmg.PTF_Portafoglio__c = microPortafoglioCORPORATE.Id;
            cmg.CRM_Account__c = business.id;
            insert cmg;
        }
    }

    @IsTest
    public static void testGetCampaignmember(){

        User titolare = [SELECT Id FROM User WHERE FederationIdentifier = '14' LIMIT 1];
        Campaign campaign = [SELECT Id FROM Campaign LIMIT 1];
        System.runAs(titolare){
        test.startTest();
            CRM_AttributiCampagneTableController.WrapperObj response = CRM_AttributiCampagneTableController.getCampaignMember(null);
            response = CRM_AttributiCampagneTableController.getCampaignMember(campaign.Id);
        
        test.stopTest();
            System.assertEquals(true, response != null);
        }
    }
    
    @IsTest
    public static void testGetCampaignmember2(){

        User gestorePrivate = [SELECT Id FROM User WHERE FederationIdentifier = '15' LIMIT 1];
        Campaign campaign = [SELECT Id FROM Campaign LIMIT 1];
        System.runAs(gestorePrivate){
        test.startTest();
            CRM_AttributiCampagneTableController.WrapperObj response = CRM_AttributiCampagneTableController.getCampaignMember(null);
            response = CRM_AttributiCampagneTableController.getCampaignMember(campaign.Id);
        
        test.stopTest();
            System.assertEquals(true, response != null);
        }
    }
}