BPER/DEVF/force-app/main/default/objects/Knowledge__kav/Knowledge__kav.object-meta.xml
<CustomObject>
    <articleTypeChannelDisplay>
        <articleTypeTemplates>
            <channel>App</channel>
            <template>Tab</template>
        </articleTypeTemplates>
        <articleTypeTemplates>
            <channel>Prm</channel>
            <template>Tab</template>
        </articleTypeTemplates>
        <articleTypeTemplates>
            <channel>Csp</channel>
            <template>Tab</template>
        </articleTypeTemplates>
        <articleTypeTemplates>
            <channel>Pkb</channel>
            <template>Toc</template>
        </articleTypeTemplates>
    </articleTypeChannelDisplay>
    <label>Knowledge</label>
    <pluralLabel>Knowledge</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

BPER/DEVF/force-app/main/default/objects/Knowledge__kav/fields/CRM_Answer__c.field-meta.xml
<CustomField>
    <fullName>CRM_Answer__c</fullName>
    <encryptionScheme>None</encryptionScheme>
    <label>Answer</label>
    <length>32768</length>
    <type>Html</type>
</CustomField>

BPER/DEVF/force-app/main/default/objects/Knowledge__kav/fields/CRM_Area__c.field-meta.xml
<CustomField>
    <fullName>CRM_Area__c</fullName>
    <label>Area</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Digital Services</fullName>
            </value>
            <value>
                <fullName>Cards</fullName>
            </value>
            <value>
                <fullName>Other products and services</fullName>
            </value>
            <value>
                <fullName>Channels</fullName>
            </value>
            <value>
                <fullName>BPER Group</fullName>
            </value>
            <value>
                <fullName>Extraordinary operations</fullName>
            </value>
            <value>
                <fullName>Guida operativa</fullName>
            </value>
            <value>
                <fullName>Guida applicativo</fullName>
            </value>
            <value>
                <fullName>Guida Salesforce</fullName>
            </value>
            <value>
                <fullName>Not Classifiable</fullName>
            </value>
            <value>
                <fullName>Email Sent</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

BPER/DEVF/force-app/main/default/objects/Knowledge__kav/fields/CRM_Level1__c.field-meta.xml
<CustomField>
    <fullName>CRM_Level1__c</fullName>
    <label>1° Level</label>
    <type>Picklist</type>
    <valueSet>
        <controllingField>CRM_Scope__c</controllingField>
        <restricted>true</restricted>
        <valueSetDefinition>
            <sorted>true</sorted>
            <value>
                <fullName>3D Secure</fullName>
            </value>
            <value>
                <fullName>Accesso</fullName>
            </value>
            <value>
                <fullName>Accesso e navigazione</fullName>
            </value>
            <value>
                <fullName>Accesso e navigazione IB</fullName>
            </value>
            <value>
                <fullName>Accesso e navigazione wizard</fullName>
            </value>
            <value>
                <fullName>Accesso IB</fullName>
            </value>
            <value>
                <fullName>Aggiornamento documento</fullName>
            </value>
            <value>
                <fullName>Aggiornamento prodotti</fullName>
                <isActive>false</isActive>
                <label>Aggiornamento prodotti</label>
            </value>
            <value>
                <fullName>Allineamento disponibilità</fullName>
            </value>
            <value>
                <fullName>Altre comunicazioni</fullName>
            </value>
            <value>
                <fullName>Altri prodotti e servizi</fullName>
            </value>
            <value>
                <fullName>Altro</fullName>
            </value>
            <value>
                <fullName>Altro blocco</fullName>
            </value>
            <value>
                <fullName>Ambiente e logistica</fullName>
            </value>
            <value>
                <fullName>App Tocca a me</fullName>
            </value>
            <value>
                <fullName>Area riservata disattivata</fullName>
            </value>
            <value>
                <fullName>Assicurazioni</fullName>
            </value>
            <value>
                <fullName>ATM</fullName>
            </value>
            <value>
                <fullName>Attivazione carta</fullName>
            </value>
            <value>
                <fullName>Biglietti</fullName>
            </value>
            <value>
                <fullName>Temporaneo</fullName>
                <label>Blocco Temporaneo</label>
            </value>
            <value>
                <fullName>Body Card</fullName>
            </value>
            <value>
                <fullName>Cambio Filiale</fullName>
            </value>
            <value>
                <fullName>Cambio IBAN</fullName>
            </value>
            <value>
                <fullName>Canali disponibili</fullName>
            </value>
            <value>
                <fullName>Caratteristiche prodotto</fullName>
            </value>
            <value>
                <fullName>Carte</fullName>
            </value>
            <value>
                <fullName>Carte di credito</fullName>
                <isActive>false</isActive>
                <label>Carte di credito</label>
            </value>
            <value>
                <fullName>Carte di debito</fullName>
                <isActive>false</isActive>
                <label>Carte di debito</label>
            </value>
            <value>
                <fullName>Carte prepagate</fullName>
                <isActive>false</isActive>
                <label>Carte prepagate</label>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

BPER/DEVF/force-app/main/default/objects/Knowledge__kav/fields/CRM_Level2__c.field-meta.xml
<CustomField>
    <fullName>CRM_Level2__c</fullName>
    <label>2° Level</label>
    <type>Picklist</type>
    <valueSet>
        <controllingField>CRM_Level1__c</controllingField>
        <restricted>true</restricted>
        <valueSetDefinition>
            <sorted>true</sorted>
            <value>
                <fullName>3D Secure</fullName>
            </value>
            <value>
                <fullName>Acquisizione documenti</fullName>
            </value>
            <value>
                <fullName>Adeguata Verifica</fullName>
            </value>
            <value>
                <fullName>Altro</fullName>
            </value>
            <value>
                <fullName>Anticipo fatture</fullName>
            </value>
            <value>
                <fullName>Apri Conto</fullName>
            </value>
            <value>
                <fullName>Attivazione carte</fullName>
            </value>
            <value>
                <fullName>Attivazione nuovo piano</fullName>
            </value>
            <value>
                <fullName>Biometria</fullName>
            </value>
            <value>
                <fullName>Biometria e Smart PIN</fullName>
            </value>
            <value>
                <fullName>Bollettini CBILL-PagoPa</fullName>
            </value>
            <value>
                <fullName>Bollettini MAV/RAV/Freccia</fullName>
            </value>
            <value>
                <fullName>Bollettini postali</fullName>
            </value>
            <value>
                <fullName>Bollo auto</fullName>
            </value>
            <value>
                <fullName>Bonifico</fullName>
            </value>
            <value>
                <fullName>Carta non funzionante</fullName>
            </value>
            <value>
                <fullName>Carte</fullName>
            </value>
            <value>
                <fullName>Carte di credito</fullName>
            </value>
            <value>
                <fullName>Carte di debito</fullName>
            </value>
            <value>
                <fullName>Carte prepagate</fullName>
            </value>
            <value>
                <fullName>Carte visualizzate</fullName>
            </value>
            <value>
                <fullName>Certificazione contatti</fullName>
            </value>
            <value>
                <fullName>Codice di sicurezza</fullName>
            </value>
            <value>
                <fullName>Codice utente</fullName>
            </value>
            <value>
                <fullName>Comprensibilità/Fruibilità</fullName>
            </value>
            <value>
                <fullName>Comunicazioni e documenti</fullName>
            </value>
            <value>
                <fullName>Condizioni e coperture</fullName>
            </value>
            <value>
                <fullName>Consensi</fullName>
            </value>
            <value>
                <fullName>Consensi Privacy</fullName>
            </value>
            <value>
                <fullName>Consutazione piani attivi</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

BPER/DEVF/force-app/main/default/objects/Knowledge__kav/fields/CRM_Level3__c.field-meta.xml
<CustomField>
    <fullName>CRM_Level3__c</fullName>
    <label>3° Level</label>
    <type>Picklist</type>
    <valueSet>
        <controllingField>CRM_Level2__c</controllingField>
        <restricted>true</restricted>
        <valueSetDefinition>
            <sorted>true</sorted>
            <value>
                <fullName>3D Secure</fullName>
            </value>
            <value>
                <fullName>Accredito stipendio/pensione</fullName>
            </value>
            <value>
                <fullName>Aggiornamento documento d&apos;identità</fullName>
            </value>
            <value>
                <fullName>Altro</fullName>
            </value>
            <value>
                <fullName>Area riservata disattivata</fullName>
            </value>
            <value>
                <fullName>Assegni</fullName>
            </value>
            <value>
                <fullName>Attivazione/disattivazione Posta on line</fullName>
            </value>
            <value>
                <fullName>Bollo auto e moto</fullName>
            </value>
            <value>
                <fullName>Budget</fullName>
            </value>
            <value>
                <fullName>Caricamento/invio documenti</fullName>
            </value>
            <value>
                <fullName>Categorie</fullName>
            </value>
            <value>
                <fullName>Certificazione interessi passivi</fullName>
            </value>
            <value>
                <fullName>Codice di sicurezza</fullName>
            </value>
            <value>
                <fullName>Collegamento carta in rubrica</fullName>
            </value>
            <value>
                <fullName>Condizioni applicate</fullName>
            </value>
            <value>
                <fullName>Configurazione prodotti</fullName>
            </value>
            <value>
                <fullName>Consensi</fullName>
            </value>
            <value>
                <fullName>Consultazione</fullName>
            </value>
            <value>
                <fullName>Credenziali errate</fullName>
            </value>
            <value>
                <fullName>Disponibilità e archiviazione</fullName>
            </value>
            <value>
                <fullName>Domiciliazione utenze</fullName>
            </value>
            <value>
                <fullName>Estinzione Finanziamento</fullName>
            </value>
            <value>
                <fullName>Gestione ordini</fullName>
            </value>
            <value>
                <fullName>Importo rateizzato</fullName>
            </value>
            <value>
                <fullName>Impostazioni</fullName>
            </value>
            <value>
                <fullName>Info stato Pratica</fullName>
            </value>
            <value>
                <fullName>Inserimento</fullName>
            </value>
            <value>
                <fullName>Key6</fullName>
            </value>
            <value>
                <fullName>Modifica contatti</fullName>
            </value>
            <value>
                <fullName>Modifica rata</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

BPER/DEVF/force-app/main/default/objects/Knowledge__kav/fields/CRM_Scope__c.field-meta.xml
<CustomField>
    <fullName>CRM_Scope__c</fullName>
    <label>Scope</label>
    <type>Picklist</type>
    <valueSet>
        <controllingField>CRM_Area__c</controllingField>
        <restricted>true</restricted>
        <valueSetDefinition>
            <sorted>true</sorted>
            <value>
                <fullName>Aggiornamento prodotti</fullName>
            </value>
            <value>
                <fullName>Altre informazioni</fullName>
            </value>
            <value>
                <fullName>Altri prodotti e servizi</fullName>
            </value>
            <value>
                <fullName>Altro</fullName>
            </value>
            <value>
                <fullName>Ambito migrazione</fullName>
            </value>
            <value>
                <fullName>Anagrafica BPERCard</fullName>
            </value>
            <value>
                <fullName>Area riservata e Smart BPERCard</fullName>
            </value>
            <value>
                <fullName>Assicurazioni</fullName>
            </value>
            <value>
                <fullName>ATM</fullName>
            </value>
            <value>
                <fullName>Attivazione nuova plastica (sblocco Poker)</fullName>
            </value>
            <value>
                <fullName>Blocco/sblocco</fullName>
            </value>
            <value>
                <fullName>Carta Conto</fullName>
            </value>
            <value>
                <fullName>CBI</fullName>
            </value>
            <value>
                <fullName>Collaborazioni</fullName>
            </value>
            <value>
                <fullName>Comunicazioni cartacee</fullName>
            </value>
            <value>
                <fullName>Condizioni economiche</fullName>
                <label>Condizioni economiche/Info Operative</label>
            </value>
            <value>
                <fullName>Contact Center</fullName>
            </value>
            <value>
                <fullName>Contatti uffici interni/centralino</fullName>
            </value>
            <value>
                <fullName>Contatto Private Banker</fullName>
            </value>
            <value>
                <fullName>Conti correnti</fullName>
            </value>
            <value>
                <fullName>Continuità operativa prodotti</fullName>
            </value>
            <value>
                <fullName>Conto On Demand</fullName>
            </value>
            <value>
                <fullName>DEM</fullName>
            </value>
            <value>
                <fullName>Documentazione ricevuta</fullName>
            </value>
            <value>
                <fullName>Documenti (EC, giacenza…)</fullName>
            </value>
            <value>
                <fullName>Eventi</fullName>
            </value>
            <value>
                <fullName>Filiale</fullName>
            </value>
            <value>
                <fullName>Filiali</fullName>
            </value>
            <value>
                <fullName>Finanziamenti</fullName>
            </value>
            <value>
                <fullName>Incassi e pagamenti aziendali</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

BPER/SIT/force-app/main/default/classes/KnowledgeController.cls
public class KnowledgeController {
    public virtual class BaseException extends Exception {}
    public class OtherException extends BaseException {}

    @AuraEnabled
    public static List<String> getAllArea() {
        List<String> aree = new List<String>();
        SObjectField picklistUsingGlobal = Knowledge__kav.fields.CRM_Area__c;
        List<PicklistEntry> entries = picklistUsingGlobal.getDescribe().getPicklistValues();
        for (PicklistEntry pe : entries) aree.add(pe.getLabel());

        return aree;
    }



    @AuraEnabled
    public static Map<String, SObject> getOpenAreaChild(List<String> picklistValue){
        System.debug('SV getOpenAreaChild: ' + picklistValue);

        List<String> picklistValueTranslated = new list<String>();
        Map<String,String> areeMap = new Map<String,String>();
        SObjectField picklistUsingGlobal = Knowledge__kav.fields.CRM_Area__c;
        List<PicklistEntry> entries = picklistUsingGlobal.getDescribe().getPicklistValues();
        for (PicklistEntry pe : entries){
        areeMap.put(pe.getLabel(),pe.getValue());
        }
        for(String str : picklistValue){
        picklistValueTranslated.add(areeMap.get(str));

        }
        
        Map<String, SObject> knowledge1 = new Map<String, SObject>();
        try { 

            knowledge1 = SV_Utilities.keyBy([ SELECT Id, Title, ArticleNumber, LastPublishedDate, PublishStatus, 
                                                toLabel(CRM_Area__c), CRM_Scope__c, CRM_Level1__c, CRM_Level2__c,
                                                CRM_Level3__c, CRM_Answer__c, CRM_Question__c, RecordType.Name
                    FROM Knowledge__kav
                    WHERE CRM_Area__c IN : picklistValueTranslated AND PublishStatus = 'Online' ], '{CRM_Area__c}_{CRM_Scope__c}_{Id}', true);
            System.debug('SV AssignAccMap: ' + knowledge1);


        } catch (BaseException e) {  
            // This catches the OtherException
            System.debug('SV BaseException ' + e);

        } 

        return knowledge1;

    }

    @AuraEnabled
    public static Map<String, SObject> getOpenScopeChild(List<String> picklistValue){
        System.debug('SV getOpenAreaChild');
        Map<String, SObject> knowledge1 = new Map<String, SObject>();
        try { 

            knowledge1 = SV_Utilities.keyBy([ SELECT Id, Title, ArticleNumber, LastPublishedDate, PublishStatus, 
                                            CRM_Area__c, CRM_Scope__c, CRM_Level1__c, CRM_Level2__c,
                                            CRM_Level3__c, CRM_Answer__c, CRM_Question__c, RecordType.Name
                    FROM Knowledge__kav
                    WHERE CRM_Scope__c IN : picklistValue AND PublishStatus = 'Online' ], '{CRM_Scope__c}_{CRM_Level1__c}_{Id}', true);
            System.debug('SV AssignAccMap: ' + knowledge1);


        } catch (BaseException e) {  
            // This catches the OtherException
            System.debug('SV BaseException ' + e);

        } 

        return knowledge1;

    }

    @AuraEnabled
    public static Map<String, SObject> getOpenLevel1Child(List<String> picklistValue){
        System.debug('SV getOpenAreaChild');
        Map<String, SObject> knowledge1 = new Map<String, SObject>();
        try { 

            knowledge1 = SV_Utilities.keyBy([ SELECT Id, Title, ArticleNumber, LastPublishedDate, PublishStatus, 
                                            CRM_Area__c, CRM_Scope__c, CRM_Level1__c, CRM_Level2__c,
                                            CRM_Level3__c, CRM_Answer__c, CRM_Question__c, RecordType.Name
                    FROM Knowledge__kav
                    WHERE CRM_Level1__c IN : picklistValue AND PublishStatus = 'Online' ], '{CRM_Level1__c}_{CRM_Level2__c}_{Id}', true);
            System.debug('SV AssignAccMap: ' + knowledge1);


        } catch (BaseException e) {  
            // This catches the OtherException
            System.debug('SV BaseException ' + e);

        } 

        return knowledge1;

    }

    @AuraEnabled
    public static Map<String, SObject> getOpenLevel2Child(List<String> picklistValue){
        System.debug('SV getOpenAreaChild');
        Map<String, SObject> knowledge1 = new Map<String, SObject>();
        try { 

            knowledge1 = SV_Utilities.keyBy([ SELECT Id, Title, ArticleNumber, LastPublishedDate, PublishStatus, 
                                    CRM_Area__c, CRM_Scope__c, CRM_Level1__c, CRM_Level2__c,
                                    CRM_Level3__c, CRM_Answer__c, CRM_Question__c, RecordType.Name 
                    FROM Knowledge__kav
                    WHERE CRM_Level2__c IN : picklistValue AND PublishStatus = 'Online' ], '{CRM_Level2__c}_{CRM_Level3__c}_{Id}', true);
            System.debug('SV AssignAccMap: ' + knowledge1);


        } catch (BaseException e) {  
            // This catches the OtherException
            System.debug('SV BaseException ' + e);

        } 

        return knowledge1;

    }

    @AuraEnabled
    public static Map<String, SObject> getOpenLevel3Child(List<String> picklistValue){
        System.debug('SV getOpenAreaChild');
        Map<String, SObject> knowledge1 = new Map<String, SObject>();
        try { 

            knowledge1 = SV_Utilities.keyBy([ SELECT Id, Title, ArticleNumber, LastPublishedDate, PublishStatus, 
                                    CRM_Area__c, CRM_Scope__c, CRM_Level1__c, CRM_Level2__c,
                                    CRM_Level3__c, CRM_Answer__c, CRM_Question__c, RecordType.Name 
                    FROM Knowledge__kav
                    WHERE CRM_Level3__c IN : picklistValue AND PublishStatus = 'Online' ], '{Id}', true);
            System.debug('SV AssignAccMap: ' + knowledge1);


        } catch (BaseException e) {  
            // This catches the OtherException
            System.debug('SV BaseException ' + e);

        } 

        return knowledge1;

    }

    @AuraEnabled
    public static User getUserInfo(){
        return [ SELECT Id, Name, Profile.Name FROM User WHERE Id =: UserInfo.getUserId() ];
        
    }

    @AuraEnabled
    public static List<RecordType> getActiveRecordType(){
        return [ SELECT Id, Name, DeveloperName FROM RecordType WHERE SobjectType = 'Knowledge__kav' AND IsActive = TRUE ];
        
    }

    @AuraEnabled
    public static Map<String, SObject> getAllDataFromText(String queryTerm){
        System.debug('SV queryTerm: ' + queryTerm);
        Map<String, SObject> result = new Map<String, SObject>();

        try{

            String sQuery = 'SELECT Id, RecordType.Name, Title, ArticleNumber, LastPublishedDate, PublishStatus, CRM_Area__c, ' +
            'CRM_Scope__c, ' +
            'CRM_Level1__c, ' + 
            'CRM_Level2__c, ' + 
            'CRM_Level3__c, ' +
            'CRM_Answer__c, ' +
            'CRM_Question__c, ' +
            'CRM_Description__c ' +
            'FROM Knowledge__kav';
            sQuery = sQuery + ' WHERE (CRM_Scope__c LIKE \'' + String.escapeSingleQuotes(queryTerm) + '%\' OR CRM_Level1__c LIKE \'' + String.escapeSingleQuotes(queryTerm) + '%\' OR CRM_Level2__c LIKE \'' + String.escapeSingleQuotes(queryTerm) + '%\' OR CRM_Level3__c LIKE \'' + String.escapeSingleQuotes(queryTerm) + '%\' OR CRM_Area__c LIKE \'' + String.escapeSingleQuotes(queryTerm) + '%\'';
            // sQuery = sQuery + ' OR CRM_Answer__c LIKE \'%' + queryTerm + '%\'';
            sQuery = sQuery + ' OR CRM_Question__c LIKE \'%' + String.escapeSingleQuotes(queryTerm) + '%\'';
            sQuery = sQuery + ' OR Title LIKE \'%' + String.escapeSingleQuotes(queryTerm) + '%\')';
            // sQuery = sQuery + ' OR CRM_Description__c LIKE \'%' + queryTerm + '%\')';
            sQuery = sQuery + ' AND PublishStatus =\'Online\'';
            sQuery = sQuery + ' ORDER BY createdDate DESC';
            System.debug('SV sQuery: ' + sQuery);
            
            List < sObject > lstOfRecords = Database.query(sQuery);
            System.debug('SV lstOfRecords: ' + lstOfRecords);

            result = SV_Utilities.keyBy(lstOfRecords, 'Id', false);




        } catch (Exception e){
            throw new AuraHandledException(e.getMessage());       
        }


        return result;
        
    }

    @AuraEnabled
    public static Map<String, SObject> getAllDataForCase(String recordId){
        System.debug('SV getAllDataForCase recordId: ' + recordId);
        Map<String, SObject> result = new Map<String, SObject>();

        try{
            List<String> conditionList = new List<String>();
            List<Case> caseRecord = [ SELECT Id, CRM_Area__c, CRM_Scope__c, CRM_Level1__c, CRM_Level2__c, CRM_Level3__c FROM Case WHERE Id =: recordId ];

            String sQuery = 'SELECT Id, RecordType.Name, Title, ArticleNumber, LastPublishedDate, PublishStatus, ' +
            'CRM_Area__c, ' +
            'CRM_Scope__c, ' +
            'CRM_Level1__c, ' + 
            'CRM_Level2__c, ' + 
            'CRM_Level3__c, ' +
            'CRM_Answer__c, ' +
            'CRM_Question__c, ' +
            'CRM_Description__c ' +
            'FROM Knowledge__kav  WHERE PublishStatus =\'Online\'';
            if(String.isNotEmpty(caseRecord[0].CRM_Area__c)) conditionList.add('CRM_Area__c = \'' + String.escapeSingleQuotes(caseRecord[0].CRM_Area__c) + '\'') ;
            if(String.isNotEmpty(caseRecord[0].CRM_Scope__c)) conditionList.add('CRM_Scope__c = \'' + String.escapeSingleQuotes(caseRecord[0].CRM_Scope__c) + '\''); 
            if(String.isNotEmpty(caseRecord[0].CRM_Level1__c)) conditionList.add('CRM_Level1__c = \'' + String.escapeSingleQuotes(caseRecord[0].CRM_Level1__c) + '\'')  ;
            if(String.isNotEmpty(caseRecord[0].CRM_Level2__c))  conditionList.add('CRM_Level2__c = \'' + String.escapeSingleQuotes(caseRecord[0].CRM_Level2__c) + '\'');
            if(String.isNotEmpty(caseRecord[0].CRM_Level3__c)) conditionList.add('CRM_Level3__c = \'' + String.escapeSingleQuotes(caseRecord[0].CRM_Level3__c) + '\'');
            // sQuery = sQuery + ' OR CRM_Answer__c LIKE \'%' + queryTerm + '%\'';
            // sQuery = sQuery + ' OR CRM_Question__c LIKE \'%' + queryTerm + '%\'';
            // sQuery = sQuery + ' OR CRM_Description__c LIKE \'%' + queryTerm + '%\')';
            if(!conditionList.isEmpty()){
                sQuery= sQuery + ' AND '+String.join(conditionList, ' AND ');
            }
            
            sQuery = sQuery + ' ORDER BY createdDate DESC';
            System.debug('SV sQuery: ' + sQuery);
            
            List < sObject > lstOfRecords = Database.query(sQuery);
            System.debug('SV lstOfRecords: ' + lstOfRecords);

            result = SV_Utilities.keyBy(lstOfRecords, 'Id', false);




        } catch (Exception e){
            throw new AuraHandledException(e.getMessage());       
        }


        return result;
        
    }

    @AuraEnabled
    public static Map<String, SObject> getAllDataFromTextHCI(String queryTerm){
        System.debug('SV queryTerm: ' + queryTerm);
        Map<String, SObject> result = new Map<String, SObject>();

        try{

            String sQuery = 'SELECT Id, RecordType.Name, Title, ArticleNumber, LastPublishedDate, PublishStatus, CRM_Area__c, ' +
            'CRM_Scope__c, ' +
            'CRM_Level1__c, ' + 
            'CRM_Level2__c, ' + 
            'CRM_Level3__c, ' +
            'CRM_Answer__c, ' +
            'CRM_Question__c, ' +
            'CRM_Description__c, ' +
            'CRM_AmbitoCluster__c, ' +
            'CRM_Cluster__c '+
            'FROM Knowledge__kav';
            sQuery = sQuery + ' WHERE (CRM_Scope__c LIKE \'' + String.escapeSingleQuotes(queryTerm) + '%\' OR CRM_Level1__c LIKE \'' + String.escapeSingleQuotes(queryTerm) + '%\' OR CRM_Level2__c LIKE \'' + String.escapeSingleQuotes(queryTerm) + '%\' OR CRM_Level3__c LIKE \'' + String.escapeSingleQuotes(queryTerm) + '%\' OR CRM_Area__c LIKE \'' + String.escapeSingleQuotes(queryTerm) + '%\'';
            // sQuery = sQuery + ' OR CRM_Answer__c LIKE \'%' + queryTerm + '%\'';
            sQuery = sQuery + ' OR Title LIKE \'%' + String.escapeSingleQuotes(queryTerm) + '%\'';
            sQuery = sQuery + ' OR CRM_AmbitoCluster__c LIKE \'%' + String.escapeSingleQuotes(queryTerm) + '%\'';
            sQuery = sQuery + ' OR CRM_Cluster__c LIKE \'%' + String.escapeSingleQuotes(queryTerm) + '%\'';
            sQuery = sQuery + ' OR CRM_Question__c LIKE \'%' + String.escapeSingleQuotes(queryTerm) + '%\')';
            // sQuery = sQuery + ' OR CRM_Description__c LIKE \'%' + queryTerm + '%\')';
            sQuery = sQuery + ' AND PublishStatus =\'Online\'';
            sQuery = sQuery + 'AND (CRM_Portale__c = \'Tutti\' OR CRM_Portale__c = \'Solo portale interno\') AND IsVisibleInPkb = TRUE';
            sQuery = sQuery + ' ORDER BY createdDate DESC';
            System.debug('SV sQuery: ' + sQuery);
            
            List < sObject > lstOfRecords = Database.query(sQuery);
            System.debug('SV lstOfRecords: ' + lstOfRecords);

            result = SV_Utilities.keyBy(lstOfRecords, 'Id', false);




        } catch (Exception e){
            throw new AuraHandledException(e.getMessage());       
        }


        return result;
        
    }

    @AuraEnabled
    public static Map<String, SObject> getAllDataFromTextHCE(String queryTerm){
        System.debug('SV queryTerm: ' + queryTerm);
        Map<String, SObject> result = new Map<String, SObject>();

        try{

            String sQuery = 'SELECT Id, RecordType.Name, Title, ArticleNumber, LastPublishedDate, PublishStatus, CRM_Area__c, ' +
            'CRM_Scope__c, ' +
            'CRM_Level1__c, ' + 
            'CRM_Level2__c, ' + 
            'CRM_Level3__c, ' +
            'CRM_Answer__c, ' +
            'CRM_Question__c, ' +
            'CRM_Description__c, ' +
            'CRM_AmbitoCluster__c, ' +
            'CRM_Cluster__c '+
            'FROM Knowledge__kav';
            sQuery = sQuery + ' WHERE (CRM_Scope__c LIKE \'' + String.escapeSingleQuotes(queryTerm) + '%\' OR CRM_Level1__c LIKE \'' + String.escapeSingleQuotes(queryTerm) + '%\' OR CRM_Level2__c LIKE \'' + String.escapeSingleQuotes(queryTerm) + '%\' OR CRM_Level3__c LIKE \'' + String.escapeSingleQuotes(queryTerm) + '%\' OR CRM_Area__c LIKE \'' + String.escapeSingleQuotes(queryTerm) + '%\'';
            // sQuery = sQuery + ' OR CRM_Answer__c LIKE \'%' + queryTerm + '%\'';
            sQuery = sQuery + ' OR Title LIKE \'%' + String.escapeSingleQuotes(queryTerm) + '%\'';
            sQuery = sQuery + ' OR CRM_AmbitoCluster__c LIKE \'%' + String.escapeSingleQuotes(queryTerm) + '%\'';
            sQuery = sQuery + ' OR CRM_Cluster__c LIKE \'%' + String.escapeSingleQuotes(queryTerm) + '%\'';
            sQuery = sQuery + ' OR CRM_Question__c LIKE \'%' + String.escapeSingleQuotes(queryTerm) + '%\')';
            // sQuery = sQuery + ' OR CRM_Description__c LIKE \'%' + queryTerm + '%\')';
            sQuery = sQuery + ' AND PublishStatus =\'Online\'';
            sQuery = sQuery + 'AND (CRM_Portale__c = \'Tutti\' OR CRM_Portale__c = \'Solo portale esterno\') AND IsVisibleInPkb = TRUE';
            sQuery = sQuery + ' ORDER BY createdDate DESC';
            System.debug('SV sQuery: ' + sQuery);
            
            List < sObject > lstOfRecords = Database.query(sQuery);
            System.debug('SV lstOfRecords: ' + lstOfRecords);

            result = SV_Utilities.keyBy(lstOfRecords, 'Id', false);




        } catch (Exception e){
            throw new AuraHandledException(e.getMessage());       
        }


        return result;
        
    }

    @AuraEnabled
    public static Map<String, SObject> getAllDataFromTextExUBI(String queryTerm){
        System.debug('SV queryTerm: ' + queryTerm);
        Map<String, SObject> result = new Map<String, SObject>();

        try{

            String sQuery = 'SELECT Id, RecordType.Name, Title, ArticleNumber, LastPublishedDate, PublishStatus, CRM_Area__c, ' +
            'CRM_Scope__c, ' +
            'CRM_Level1__c, ' + 
            'CRM_Level2__c, ' + 
            'CRM_Level3__c, ' +
            'CRM_Answer__c, ' +
            'CRM_Question__c, ' +
            'CRM_Description__c, ' +
            'CRM_AmbitoCluster__c, ' +
            'CRM_Cluster__c '+
            'FROM Knowledge__kav';
            sQuery = sQuery + ' WHERE (CRM_Scope__c LIKE \'' + String.escapeSingleQuotes(queryTerm) + '%\' OR CRM_Level1__c LIKE \'' + String.escapeSingleQuotes(queryTerm) + '%\' OR CRM_Level2__c LIKE \'' + String.escapeSingleQuotes(queryTerm) + '%\' OR CRM_Level3__c LIKE \'' + String.escapeSingleQuotes(queryTerm) + '%\' OR CRM_Area__c LIKE \'' + String.escapeSingleQuotes(queryTerm) + '%\'';
            // sQuery = sQuery + ' OR CRM_Answer__c LIKE \'%' + queryTerm + '%\'';
            sQuery = sQuery + ' OR Title LIKE \'%' + String.escapeSingleQuotes(queryTerm) + '%\'';
            sQuery = sQuery + ' OR CRM_AmbitoCluster__c LIKE \'%' + String.escapeSingleQuotes(queryTerm) + '%\'';
            sQuery = sQuery + ' OR CRM_Cluster__c LIKE \'%' + String.escapeSingleQuotes(queryTerm) + '%\'';
            sQuery = sQuery + ' OR CRM_Question__c LIKE \'%' + String.escapeSingleQuotes(queryTerm) + '%\')';
            // sQuery = sQuery + ' OR CRM_Description__c LIKE \'%' + queryTerm + '%\')';
            sQuery = sQuery + ' AND PublishStatus =\'Online\'';
            sQuery = sQuery + 'AND (CRM_Portale__c = \'Tutti\' OR CRM_Portale__c = \'Solo portale Ex-UBI\') AND IsVisibleInPkb = TRUE';
            sQuery = sQuery + ' ORDER BY createdDate DESC';
            System.debug('SV sQuery: ' + sQuery);
            
            List < sObject > lstOfRecords = Database.query(sQuery);
            System.debug('SV lstOfRecords: ' + lstOfRecords);

            result = SV_Utilities.keyBy(lstOfRecords, 'Id', false);




        } catch (Exception e){
            throw new AuraHandledException(e.getMessage());       
        }


        return result;
        
    }

    @AuraEnabled
    public static Map<String, SObject> getAllDataFromTextExISP(String queryTerm){
        System.debug('SV queryTerm: ' + queryTerm);
        Map<String, SObject> result = new Map<String, SObject>();

        try{

            String sQuery = 'SELECT Id, RecordType.Name, Title, ArticleNumber, LastPublishedDate, PublishStatus, CRM_Area__c, ' +
            'CRM_Scope__c, ' +
            'CRM_Level1__c, ' + 
            'CRM_Level2__c, ' + 
            'CRM_Level3__c, ' +
            'CRM_Answer__c, ' +
            'CRM_Question__c, ' +
            'CRM_Description__c, ' +
            'CRM_AmbitoCluster__c, ' +
            'CRM_Cluster__c '+
            'FROM Knowledge__kav';
            sQuery = sQuery + ' WHERE (CRM_Scope__c LIKE \'' + String.escapeSingleQuotes(queryTerm) + '%\' OR CRM_Level1__c LIKE \'' + String.escapeSingleQuotes(queryTerm) + '%\' OR CRM_Level2__c LIKE \'' + String.escapeSingleQuotes(queryTerm) + '%\' OR CRM_Level3__c LIKE \'' + String.escapeSingleQuotes(queryTerm) + '%\' OR CRM_Area__c LIKE \'' + String.escapeSingleQuotes(queryTerm) + '%\'';
            // sQuery = sQuery + ' OR CRM_Answer__c LIKE \'%' + queryTerm + '%\'';
            sQuery = sQuery + ' OR Title LIKE \'%' + String.escapeSingleQuotes(queryTerm) + '%\'';
            sQuery = sQuery + ' OR CRM_AmbitoCluster__c LIKE \'%' + String.escapeSingleQuotes(queryTerm) + '%\'';
            sQuery = sQuery + ' OR CRM_Cluster__c LIKE \'%' + String.escapeSingleQuotes(queryTerm) + '%\'';
            sQuery = sQuery + ' OR CRM_Question__c LIKE \'%' + String.escapeSingleQuotes(queryTerm) + '%\')';
            // sQuery = sQuery + ' OR CRM_Description__c LIKE \'%' + queryTerm + '%\')';
            sQuery = sQuery + ' AND PublishStatus =\'Online\'';
            sQuery = sQuery + 'AND (CRM_Portale__c = \'Tutti\' OR CRM_Portale__c = \'Solo portale Ex-ISP\') AND IsVisibleInPkb = TRUE';
            sQuery = sQuery + ' ORDER BY createdDate DESC';
            System.debug('SV sQuery: ' + sQuery);
            
            List < sObject > lstOfRecords = Database.query(sQuery);
            System.debug('SV lstOfRecords: ' + lstOfRecords);

            result = SV_Utilities.keyBy(lstOfRecords, 'Id', false);




        } catch (Exception e){
            throw new AuraHandledException(e.getMessage());       
        }


        return result;
        
    }
}